<script lang="ts">
	import Card from '$lib/components/ui/Card.svelte';
	import {
		Settings as SettingsIcon,
		ShieldCheck,
		Search,
		BarChart3,
		Code2,
		Building2,
		Server,
		Cloud,
		Globe,
		FileCode,
		FileText,
		Bot,
		Sparkles,
		Lock
	} from 'lucide-svelte';
	import type { Site } from '$lib/api/types';

	let { data }: { data: { site: Site } } = $props();

	const siteID = $derived(data.site.id);

	// Files atomicsite generates on every build. Each entry is rendered once
	// the site goes live; the path is what curl <domain>/<path> would hit.
	// Keep this list in sync with internal/builder/{config,security,layouts}.go.
	const generatedFiles: { path: string; label: string; description: string; icon: typeof FileCode }[] = [
		{ path: '/sitemap-index.xml', label: 'XML Sitemap', description: 'Auto-generated by @astrojs/sitemap from every published page.', icon: FileCode },
		{ path: '/robots.txt', label: 'robots.txt', description: 'AI-training bots blocked by default (GPTBot, ClaudeBot, etc). Override via SEO settings.', icon: FileText },
		{ path: '/.well-known/security.txt', label: 'security.txt', description: 'RFC 9116 contact published when Profile sets a security email.', icon: Lock },
		{ path: '/llms.txt', label: 'llms.txt', description: 'AI search readiness (Perplexity, ChatGPT). Built from your published pages.', icon: Bot },
		{ path: '/humans.txt', label: 'humans.txt', description: 'Team + site metadata for the humans behind the build.', icon: FileText },
		{ path: '/favicon.ico', label: 'Favicon', description: 'Linked in every page. Upload a .ico to the brand folder in Media.', icon: Sparkles },
		{ path: '/apple-touch-icon.png', label: 'Apple touch icon', description: 'iOS home-screen icon. Drop a 180x180 PNG into the brand folder.', icon: Sparkles },
		{ path: 'JSON-LD Organization (in <head>)', label: 'Organization schema', description: 'Auto-emitted from Profile (business name, address, sameAs URLs). Anchors your entity in AI knowledge graphs.', icon: Bot },
		{ path: 'JSON-LD BreadcrumbList (in <head>)', label: 'BreadcrumbList schema', description: 'Per-page (depth >= 2). Drives SERP breadcrumb rendering.', icon: Bot },
		{ path: 'JSON-LD Article (in <head>)', label: 'Article schema', description: 'Article-type pages get datePublished + dateModified + author wired from your Profile.', icon: Bot },
		{ path: 'OG + Twitter Card (in <head>)', label: 'Social meta', description: 'og:title/description/image/site_name/locale + twitter:card=summary_large_image. og:image dimensions 1200x630.', icon: Sparkles }
	];
</script>

{#snippet sectionCard(
	href: string,
	title: string,
	subtitle: string,
	IconCmp: typeof SettingsIcon,
	danger: boolean = false
)}
	<a {href} class="block">
		<Card padding="md" hoverable class={danger ? 'border-danger/30' : ''}>
			<div class="flex items-start gap-3">
				<span
					class="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-border-light {danger
						? 'text-danger bg-danger/5'
						: 'text-text-secondary bg-bg-elevated'}"
				>
					<IconCmp size={16} strokeWidth={1.5} />
				</span>
				<div class="flex flex-col gap-0.5 min-w-0">
					<p class="text-[13px] font-medium {danger ? 'text-danger' : 'text-text-primary'}">
						{title}
					</p>
					<p class="text-[12px] text-text-muted">{subtitle}</p>
				</div>
			</div>
		</Card>
	</a>
{/snippet}

<div class="mx-auto max-w-7xl px-6 py-8">
	<header class="flex flex-col gap-1.5">
		<h1 class="font-display text-3xl font-extralight tracking-tight text-text-primary">
			Settings
		</h1>
		<p class="text-[13px] text-text-secondary">
			Configure how this site behaves, ships, and surfaces in search.
		</p>
	</header>

	<section class="mt-8 grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
		{@render sectionCard(
			`/sites/${siteID}/settings/general`,
			'General',
			'Site name, domain, language, defaults.',
			SettingsIcon
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/agent`,
			'Agent',
			'Inventory of what an AI agent connected via MCP can see and do.',
			Bot
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/domains`,
			'Domains',
			'Custom hostnames, verification, TLS, canonical URL.',
			Globe
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/security`,
			'Security',
			'HSTS, CSP, frame options, referrer policy.',
			ShieldCheck
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/seo`,
			'SEO',
			'Meta templates, sitemap, robots, hreflang.',
			Search
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/analytics`,
			'Analytics',
			'CookieProof, GA4, Umami, CRM webhook.',
			BarChart3
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/allowed-scripts`,
			'Trusted external domains',
			'Whitelist iframes (cal.com), scripts, CDNs in CSP.',
			Code2
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/profile`,
			'Profile',
			'Business info, legal contacts, address.',
			Building2
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/nginx`,
			'Nginx',
			'Preview the generated server config.',
			Server
		)}
		{@render sectionCard(
			`/sites/${siteID}/settings/deployment`,
			'Deployment',
			'Targets for publishing built sites.',
			Cloud
		)}
	</section>

	<p class="mt-6 text-[12px] text-text-muted">
		Looking for "Delete this site"? It's now in
		<a href="/account" class="text-accent underline-offset-2 hover:underline">Account settings</a>
		so destructive cross-site actions live in one place.
	</p>

	<section class="mt-10">
		<header class="flex flex-col gap-1.5">
			<h2 class="text-[11px] font-mono uppercase tracking-[0.2em] text-text-muted">
				Generated files
			</h2>
			<p class="text-[13px] text-text-secondary">
				Atomicsite builds these for every site automatically. Most pull
				values from your Profile, SEO settings, and Branding so there's
				nothing to maintain by hand. The build pipeline writes them on
				every deploy.
			</p>
		</header>
		<div class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">
			{#each generatedFiles as f (f.path)}
				<Card padding="md">
					<div class="flex items-start gap-3">
						<span
							class="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-border-light bg-bg-elevated text-text-secondary"
						>
							<f.icon size={14} strokeWidth={1.5} />
						</span>
						<div class="min-w-0 flex-1">
							<p class="text-[13px] font-medium text-text-primary">{f.label}</p>
							<p class="mt-0.5 truncate font-mono text-[11px] text-text-muted">{f.path}</p>
							<p class="mt-1.5 text-[12px] text-text-secondary">{f.description}</p>
						</div>
					</div>
				</Card>
			{/each}
		</div>
		<p class="mt-4 text-[11.5px] text-text-muted">
			Plus full security headers (CSP, HSTS, X-Frame-Options, Referrer-Policy,
			Permissions-Policy, COOP, CORP, COEP) emitted on every response via
			both the
			<code class="font-mono text-[11px]">_headers</code>
			file (Caddy / Netlify / Cloudflare Pages) and
			<code class="font-mono text-[11px]">nginx.conf</code>
			(Dockyard / self-hosted). Edit them in
			<a
				href={`/sites/${siteID}/settings/security`}
				class="text-accent underline-offset-2 hover:underline"
			>
				Security
			</a>
			and whitelist iframes / CDNs / scripts in
			<a
				href={`/sites/${siteID}/settings/allowed-scripts`}
				class="text-accent underline-offset-2 hover:underline"
			>
				Trusted external domains
			</a>.
		</p>
	</section>
</div>
