// Package domains owns the custom-hostname pipeline:
//
//	nginx fragment writer  (this file: edge.go)
//	verification poller    (verify.go)
//	certbot orchestration  (certbot.go)
//	Cloudflare helper      (cloudflare.go)
//	reconcile loop          (reconciler.go)
//
// The handlers package owns the HTTP CRUD surface and the public verify
// endpoint; this package owns the side-effects: writing nginx server
// blocks, shelling out to certbot, calling DNS providers, polling the
// hostname for liveness, and signaling nginx to reload.
//
// Why a separate package: the reconciler is a long-lived background
// goroutine and writes to the host filesystem. Keeping it out of
// handlers/ avoids accidental coupling (handlers must not block on
// shell-outs) and makes the boundary easy to mock in tests.
package domains

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/brightinteraction/atomicsite/internal/store"
)

// EdgeWriter writes per-domain nginx fragments to disk. Paths come
// from config; when any path is empty the writer becomes a no-op so
// local dev (and OSS deploys without root on the host) keep working
// without crashing every time a domain row is created.
type EdgeWriter struct {
	NginxConfDir   string // /etc/nginx/conf.d
	NginxSitesDir  string // /etc/nginx/sites-enabled
	AcmeWebrootDir string // /var/www/acme
	// SlugSuffix is the wildcard tenant suffix the existing nginx
	// vhost terminates (e.g. ".tenants.example.com"). Set via the
	// BUILT_SITE_SUFFIX env var. Custom-domain proxy_pass uses
	// Host: <slug><SlugSuffix> so the upstream Caddy's existing
	// {labels.3} routing finds the right dist dir without a separate
	// per-tenant Caddy block. Empty disables the rewrite.
	SlugSuffix string
	// HeadersSnippet is the include path for the global A+ headers
	// fragment (e.g. /etc/nginx/snippets/atomicsite-headers.conf).
	// Empty means the per-domain block emits headers inline.
	HeadersSnippet string
	// CaddyUpstream is the address Caddy listens on for plain HTTP
	// from nginx (default 127.0.0.1:8080).
	CaddyUpstream string
}

// Enabled reports whether the writer has enough config to actually
// touch the host filesystem. Callers use this to skip work in dev.
func (e *EdgeWriter) Enabled() bool {
	return e.NginxConfDir != "" && e.NginxSitesDir != ""
}

// AcmeBlockPath returns the conf.d path for the global ACME-challenge
// helper block. We render the same content every time the reconciler
// runs (idempotent) so it survives manual edits.
func (e *EdgeWriter) AcmeBlockPath() string {
	return filepath.Join(e.NginxConfDir, "atomicsite-acme.conf")
}

// DomainMapPath returns the conf.d path for the auto-generated map
// directive that extends $atomicsite_slug to know about custom
// domains. The wildcard server block already references this var.
func (e *EdgeWriter) DomainMapPath() string {
	return filepath.Join(e.NginxConfDir, "atomicsite-domain-map.conf")
}

// VhostPath returns the per-domain server-block file path.
func (e *EdgeWriter) VhostPath(domainID string) string {
	return filepath.Join(e.NginxSitesDir, "atomicsite-domain-"+domainID+".conf")
}

// WriteAcmeBlock writes the global port-80 helper that serves both
// /.well-known/acme-challenge/ (certbot webroot) and
// /.well-known/atomic-verify/ (proxied to the atomicsite app on
// localhost:8091). Idempotent.
func (e *EdgeWriter) WriteAcmeBlock(appUpstream string) error {
	if !e.Enabled() {
		return nil
	}
	body := fmt.Sprintf(`# Auto-generated by atomicsite. Do not edit by hand.
#
# Global port-80 helper for custom-domain provisioning.
#
#  - /.well-known/acme-challenge/  -> webroot for certbot HTTP-01.
#  - /.well-known/atomic-verify/   -> proxied to the atomicsite app
#    so the verification poller can prove ownership before TLS exists.
#  - everything else               -> 301 redirect to https.
#
# This block listens on port 80 with the default_server flag; nginx
# falls back to it for any unknown hostname, which is what we want
# for newly-pointed custom domains during the verification step.

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root %s;
        try_files $uri =404;
    }

    location ^~ /.well-known/atomic-verify/ {
        proxy_pass %s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
`, e.AcmeWebrootDir, appUpstream)
	return writeIfChanged(e.AcmeBlockPath(), body)
}

// WriteDomainMap regenerates the slug-derivation map covering both the
// wildcard tenant suffix and every live custom domain. The map is the
// canonical source for "which tenant does $host belong to?" inside
// nginx (used by the access_log filename + any future per-tenant
// rules). Output is sorted so diffs stay clean across reconciles.
func (e *EdgeWriter) WriteDomainMap(domains []store.SiteDomain, sitesByID map[string]string) error {
	if !e.Enabled() {
		return nil
	}
	type entry struct{ host, slug string }
	rows := []entry{}
	for _, d := range domains {
		if d.Status != "live" && d.Status != "cert_ready" {
			continue
		}
		slug := sitesByID[d.SiteID]
		if slug == "" {
			continue
		}
		rows = append(rows, entry{host: d.Hostname, slug: slug})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].host < rows[j].host })

	var b strings.Builder
	b.WriteString("# Auto-generated by atomicsite. Do not edit by hand.\n")
	b.WriteString("# Extends $atomicsite_slug (defined in atomicsite-tracking.conf)\n")
	b.WriteString("# with custom-domain entries. Order matters: nginx prefers the\n")
	b.WriteString("# first matching pattern, so exact custom-domain rules sit\n")
	b.WriteString("# above the wildcard suffix regex inherited from -tracking.conf.\n\n")
	b.WriteString("map $host $atomicsite_custom_slug {\n")
	for _, r := range rows {
		b.WriteString(fmt.Sprintf("    %s %s;\n", quoteForMap(r.host), quoteForMap(r.slug)))
	}
	b.WriteString("    default \"\";\n")
	b.WriteString("}\n")
	return writeIfChanged(e.DomainMapPath(), b.String())
}

// WriteDomainVhost renders the 443 server block for one verified
// custom domain. The cert path comes from the certbot step; until
// then the row stays at status='verified' and this is not called.
//
// The block:
//   - terminates TLS with the LE cert,
//   - includes the global A+ headers snippet (when configured),
//   - proxy_passes to Caddy on 8080 with Host: <slug><suffix> so
//     Caddy's existing {labels.3} routing finds the right dist dir
//     without us touching the Caddyfile.
func (e *EdgeWriter) WriteDomainVhost(d store.SiteDomain, slug, certDir string) error {
	if !e.Enabled() {
		return nil
	}
	upstream := e.CaddyUpstream
	if upstream == "" {
		upstream = "127.0.0.1:8080"
	}
	hostHeader := slug + e.SlugSuffix
	include := ""
	if e.HeadersSnippet != "" {
		include = "    include " + e.HeadersSnippet + ";\n"
	}
	body := fmt.Sprintf(`# Auto-generated by atomicsite for site_domain %s. Do not edit by hand.
#
# Hostname: %s
# Tenant slug: %s
# Cert: %s
#
# Routing: TLS terminates here, A+ headers come from the shared
# snippet, request proxies to Caddy on %s with the wildcard Host
# header so the existing per-slug dist-dir routing applies.

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name %s;

%s    ssl_certificate %s/fullchain.pem;
    ssl_certificate_key %s/privkey.pem;

    location / {
        proxy_pass http://%s;
        proxy_http_version 1.1;
        proxy_set_header Host %s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Atomicsite-Custom-Host $host;
        client_max_body_size 100m;
    }
}
`, d.ID, d.Hostname, slug, certDir, upstream, d.Hostname, include, certDir, certDir, upstream, hostHeader)
	return writeIfChanged(e.VhostPath(d.ID), body)
}

// RemoveDomainVhost deletes a per-domain block. Idempotent: missing
// file is not an error.
func (e *EdgeWriter) RemoveDomainVhost(domainID string) error {
	if !e.Enabled() {
		return nil
	}
	p := e.VhostPath(domainID)
	if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// SweepOrphanVhosts removes per-domain server-block files whose
// domainID is not in liveIDs. Called from the reconcile sweep so a
// row deleted by the admin (or by site cascade) cleans up its nginx
// fragment without requiring the handler to know about the edge
// writer. Returns the number of files removed (for telemetry).
func (e *EdgeWriter) SweepOrphanVhosts(liveIDs map[string]struct{}) (int, error) {
	if !e.Enabled() {
		return 0, nil
	}
	entries, err := os.ReadDir(e.NginxSitesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	const prefix = "atomicsite-domain-"
	const suffix = ".conf"
	removed := 0
	for _, en := range entries {
		name := en.Name()
		if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, suffix) {
			continue
		}
		id := strings.TrimSuffix(strings.TrimPrefix(name, prefix), suffix)
		if _, ok := liveIDs[id]; ok {
			continue
		}
		_ = os.Remove(filepath.Join(e.NginxSitesDir, name))
		removed++
	}
	return removed, nil
}

// writeIfChanged writes body to path only when the existing contents
// differ. Avoids spurious nginx reloads when reconcile fires often.
func writeIfChanged(path, body string) error {
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == body {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

// quoteForMap wraps map keys/values in double quotes with internal
// quote escaping. nginx's map directive accepts unquoted strings for
// simple identifiers, but we always quote so a hostname or slug
// containing a hyphen / dot reads identically.
func quoteForMap(s string) string {
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
