// Package builder: caddy_fragment.go (Phase 30.3, Cloud Tier MVP, 2026-05-06).
//
// Emits a per-tenant Caddyfile fragment alongside the _headers file
// so a host Caddy can import the fragment and apply the right
// security headers without re-deriving them.
//
// Usage on the host (one of these patterns):
//
//   1. Wildcard subdomain server with per-tenant fragment import:
//
//        *.atomicsite.example.com {
//            tls { on_demand }
//            @tenant header_regexp host Host ^([^.]+)\.atomicsite\.brightinteraction\.com$
//            handle @tenant {
//                root * /srv/atomicsite/{re.host.1}/dist
//                import /srv/atomicsite/{re.host.1}/dist/Caddyfile
//                file_server
//            }
//        }
//
//   2. One vhost per custom domain (auto-managed by atomicsite via
//      the DomainReconciler in Phase 30.5):
//
//        :443 {
//            tls { on_demand }
//            root * /srv/atomicsite/<slug>/dist
//            import /srv/atomicsite/<slug>/dist/Caddyfile
//            file_server
//        }
//
// The fragment never declares a server block (no host/port). It
// ships only the directives that go inside one: `header { ... }`,
// `encode`, plus per-path `route` blocks for cache lifetime
// directives. Re-declaring the server would conflict with the host's
// outer block; a fragment that only adds directives composes safely.
package builder

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/brightinteraction/atomicsite/internal/store"
)

// RenderCaddyFragment writes a per-tenant Caddyfile fragment based on
// the site's computed security headers. Mirrors RenderSecurityHeaders
// (which writes _headers for Netlify/Cloudflare Pages style hosts) so
// both formats stay in sync from one source of truth.
//
// Output path: <wsDir>/public/Caddyfile. After the Astro build the
// public/ folder is copied to dist/, so the fragment lands at
// dist/Caddyfile alongside index.html. Operators import that path
// from their host Caddyfile.
func RenderCaddyFragment(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	h, err := BuildSecurityHeaders(ctx, queries, siteID)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by Atomicsite. Per-tenant Caddyfile fragment.\n")
	b.WriteString("# Import this from a host Caddy server block:\n")
	b.WriteString("#   import /srv/atomicsite/<slug>/dist/Caddyfile\n")
	b.WriteString("# The fragment only emits header + encode + route directives;\n")
	b.WriteString("# it never declares a server. Outer block owns hostname / TLS.\n\n")

	// Security headers. Caddy's header directive accepts both `name value`
	// (sets the header on every response) and `+name value` / `>name value`
	// (add / set-without-overwrite). We use the plain form so the fragment
	// fully owns the response header set for these names; downstream
	// directives can still add Cache-Control etc.
	b.WriteString("header {\n")
	writeCaddyHeader := func(name, value string) {
		if value == "" {
			return
		}
		// Quote the value so `;`, `=`, spaces, and `'unsafe-inline'`
		// pass through verbatim.
		b.WriteString(fmt.Sprintf("    %s %s\n", name, caddyQuote(value)))
	}
	writeCaddyHeader("Content-Security-Policy", h.CSP)
	writeCaddyHeader("Strict-Transport-Security", h.HSTS)
	writeCaddyHeader("X-Frame-Options", h.XFrameOptions)
	writeCaddyHeader("X-Content-Type-Options", h.XContentTypeOptions)
	writeCaddyHeader("Referrer-Policy", h.ReferrerPolicy)
	writeCaddyHeader("Permissions-Policy", h.PermissionsPolicy)
	writeCaddyHeader("Cross-Origin-Opener-Policy", h.COOP)
	writeCaddyHeader("Cross-Origin-Resource-Policy", h.CORP)
	writeCaddyHeader("Cross-Origin-Embedder-Policy", h.COEP)
	writeCaddyHeader("X-Permitted-Cross-Domain-Policies", h.XPermittedCrossDomainPolicies)
	writeCaddyHeader("X-XSS-Protection", h.XXSSProtection)
	b.WriteString("    # Strip Server header so we don't advertise atomicsite version.\n")
	b.WriteString("    -Server\n")
	b.WriteString("}\n\n")

	// Compression. Brotli > gzip when the client supports it.
	b.WriteString("encode zstd br gzip\n\n")

	// Long-cache for hashed assets and media (content-addressed).
	b.WriteString("@long_cache path_regexp ^/(_assets|media)/\n")
	b.WriteString("header @long_cache Cache-Control \"public, max-age=31536000, immutable\"\n\n")

	// Short-cache for HTML so content updates take effect quickly.
	b.WriteString("@html path_regexp \\.html$\n")
	b.WriteString("header @html Cache-Control \"public, max-age=300\"\n")

	return WriteFile(filepath.Join(wsDir, "public", "Caddyfile"), b.String())
}

// caddyQuote wraps a value in double quotes and escapes embedded
// quotes + backslashes. Caddy's directive parser treats unquoted
// arguments as space-separated tokens; CSP and Permissions-Policy
// values contain spaces and special chars and MUST be quoted.
func caddyQuote(v string) string {
	v = strings.ReplaceAll(v, `\`, `\\`)
	v = strings.ReplaceAll(v, `"`, `\"`)
	return `"` + v + `"`
}
