package builder

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/brightinteraction/atomicsite/internal/store"
)

// RenderConfig generates astro.config.mjs, robots.txt, and other static config files.
func RenderConfig(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	site, err := queries.GetSiteByID(ctx, siteID)
	if err != nil {
		return fmt.Errorf("get site: %w", err)
	}

	settings, _ := queries.ListSettingsBySite(ctx, siteID)
	settingsMap := make(map[string]string)
	for _, s := range settings {
		settingsMap[s.Category+"."+s.Key] = s.Value
	}

	redirects, _ := queries.ListRedirectsBySite(ctx, siteID)

	domain := site.Domain
	if domain == "" {
		domain = "localhost"
	}
	if !strings.HasPrefix(domain, "http") {
		domain = "https://" + domain
	}

	// astro.config.mjs. Sitemap is on by default; flip seo.sitemap_enabled=0
	// to drop the integration entirely (sitemap-index.xml will not be emitted).
	sitemapEnabled := boolSetting(settingsMap["seo.sitemap_enabled"], true)
	var astroConfig string
	if sitemapEnabled {
		astroConfig = fmt.Sprintf(`// Auto-generated by Atomicsite
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: '%s',
  output: 'static',
  integrations: [sitemap()],
  build: {
    assets: '_assets',
  },
});
`, domain)
	} else {
		astroConfig = fmt.Sprintf(`// Auto-generated by Atomicsite
import { defineConfig } from 'astro/config';

export default defineConfig({
  site: '%s',
  output: 'static',
  integrations: [],
  build: {
    assets: '_assets',
  },
});
`, domain)
	}
	if err := WriteFile(filepath.Join(wsDir, "astro.config.mjs"), astroConfig); err != nil {
		return err
	}

	// robots.txt. Two override paths:
	//   seo.robots_txt        full override (replaces the auto-generated body)
	//   seo.robots_txt_extra  appended to the auto-generated body
	// The frontend SEO settings page writes the _extra variant by default;
	// the full override is reserved for power users who want to author the
	// whole file by hand. Both can be set together (the override wins).
	robotsTxt := settingsMap["seo.robots_txt"]
	if robotsTxt == "" {
		robotsTxt = fmt.Sprintf("User-agent: *\nAllow: /\n\nSitemap: %s/sitemap-index.xml\n", domain)

		// Block AI training bots by default
		robotsTxt += "\n# AI Training Bots\n"
		for _, bot := range []string{"GPTBot", "ChatGPT-User", "OAI-SearchBot", "anthropic-ai", "Claude-Web", "ClaudeBot", "Google-Extended", "CCBot", "PerplexityBot", "Bytespider"} {
			robotsTxt += fmt.Sprintf("User-agent: %s\nDisallow: /\n\n", bot)
		}
		if extra := strings.TrimSpace(settingsMap["seo.robots_txt_extra"]); extra != "" {
			robotsTxt += "\n# Operator-supplied directives (seo.robots_txt_extra)\n" + extra + "\n"
		}
	}
	if err := WriteFile(filepath.Join(wsDir, "public", "robots.txt"), robotsTxt); err != nil {
		return err
	}

	// _redirects file. Built from two sources:
	//   1. site_redirects rows (manual page-level rewrites managed in Pages)
	//   2. general.domain_aliases CSV (each alias 301-redirects all paths to
	//      the primary domain). Format aligns with Caddy / Netlify / Cloudflare
	//      Pages: "<from-pattern> <to-pattern> <status>".
	var rb strings.Builder
	for _, r := range redirects {
		rb.WriteString(fmt.Sprintf("%s %s %d\n", r.FromPath, r.ToPath, r.StatusCode))
	}
	if aliases := strings.TrimSpace(settingsMap["general.domain_aliases"]); aliases != "" {
		primary := strings.TrimRight(domain, "/")
		for _, raw := range strings.Split(aliases, ",") {
			alias := strings.TrimSpace(raw)
			if alias == "" {
				continue
			}
			// Strip protocol if the operator typed it; the alias rule needs to
			// match host-only so the deploy target's reverse proxy can route
			// any-scheme requests at the alias to the primary.
			alias = strings.TrimPrefix(alias, "https://")
			alias = strings.TrimPrefix(alias, "http://")
			alias = strings.TrimRight(alias, "/")
			if alias == "" {
				continue
			}
			rb.WriteString(fmt.Sprintf("https://%s/* %s/:splat 301\n", alias, primary))
		}
	}
	if rb.Len() > 0 {
		if err := WriteFile(filepath.Join(wsDir, "public", "_redirects"), rb.String()); err != nil {
			return err
		}
	}

	// security.txt — scrub CRLF from email to prevent header injection
	profile, _ := queries.GetSiteProfile(ctx, siteID)
	if email := stripCtl(profile.SecurityEmail); email != "" {
		secTxt := fmt.Sprintf("Contact: mailto:%s\nPreferred-Languages: en\n", email)
		if err := WriteFile(filepath.Join(wsDir, "public", ".well-known", "security.txt"), secTxt); err != nil {
			return err
		}
	}

	return nil
}
