package builder

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/brightinteraction/atomicsite/internal/store"
)

// RenderConfig generates astro.config.mjs, robots.txt, and other static config files.
func RenderConfig(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	site, err := queries.GetSiteByID(ctx, siteID)
	if err != nil {
		return fmt.Errorf("get site: %w", err)
	}

	settings, _ := queries.ListSettingsBySite(ctx, siteID)
	settingsMap := make(map[string]string)
	for _, s := range settings {
		settingsMap[s.Category+"."+s.Key] = s.Value
	}

	redirects, _ := queries.ListRedirectsBySite(ctx, siteID)

	domain := site.Domain
	if domain == "" {
		domain = "localhost"
	}
	if !strings.HasPrefix(domain, "http") {
		domain = "https://" + domain
	}

	// astro.config.mjs
	astroConfig := fmt.Sprintf(`// Auto-generated by Atomicsite
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: '%s',
  output: 'static',
  integrations: [sitemap()],
  build: {
    assets: '_assets',
  },
});
`, domain)
	if err := WriteFile(filepath.Join(wsDir, "astro.config.mjs"), astroConfig); err != nil {
		return err
	}

	// robots.txt
	robotsTxt := settingsMap["seo.robots_txt"]
	if robotsTxt == "" {
		robotsTxt = fmt.Sprintf("User-agent: *\nAllow: /\n\nSitemap: %s/sitemap-index.xml\n", domain)

		// Block AI training bots by default
		robotsTxt += "\n# AI Training Bots\n"
		for _, bot := range []string{"GPTBot", "ChatGPT-User", "OAI-SearchBot", "anthropic-ai", "Claude-Web", "ClaudeBot", "Google-Extended", "CCBot", "PerplexityBot", "Bytespider"} {
			robotsTxt += fmt.Sprintf("User-agent: %s\nDisallow: /\n\n", bot)
		}
	}
	if err := WriteFile(filepath.Join(wsDir, "public", "robots.txt"), robotsTxt); err != nil {
		return err
	}

	// _redirects file (for Caddy/Netlify/Cloudflare Pages)
	if len(redirects) > 0 {
		var rb strings.Builder
		for _, r := range redirects {
			rb.WriteString(fmt.Sprintf("%s %s %d\n", r.FromPath, r.ToPath, r.StatusCode))
		}
		if err := WriteFile(filepath.Join(wsDir, "public", "_redirects"), rb.String()); err != nil {
			return err
		}
	}

	// security.txt
	profile, _ := queries.GetSiteProfile(ctx, siteID)
	if profile.SecurityEmail != "" {
		secTxt := fmt.Sprintf("Contact: mailto:%s\nPreferred-Languages: en\n", profile.SecurityEmail)
		if err := WriteFile(filepath.Join(wsDir, "public", ".well-known", "security.txt"), secTxt); err != nil {
			return err
		}
	}

	return nil
}
