package builder

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/brightinteraction/atomicsite/internal/store"
)

// RenderCSS generates the global.css file from site branding and CSS classes.
func RenderCSS(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	site, err := queries.GetSiteByID(ctx, siteID)
	if err != nil {
		return fmt.Errorf("get site: %w", err)
	}

	classes, err := queries.ListCSSClassesBySite(ctx, siteID)
	if err != nil {
		return fmt.Errorf("list css classes: %w", err)
	}

	settings, _ := queries.ListSettingsBySite(ctx, siteID)
	sm := make(map[string]string, len(settings))
	for _, s := range settings {
		sm[s.Category+"."+s.Key] = s.Value
	}

	// Container width: enum value -> CSS unit. Operator picks via
	// general.container_width setting. Default 72rem matches most marketing
	// sites including brightinteraction.com.
	containerWidth := "72rem"
	switch sm["general.container_width"] {
	case "narrow":
		containerWidth = "64rem"
	case "wide":
		containerWidth = "80rem"
	case "fluid":
		containerWidth = "100%"
	}
	mobileBP := orDefault(sm["general.mobile_breakpoint"], "640") + "px"
	tabletBP := orDefault(sm["general.tablet_breakpoint"], "1024") + "px"

	var b strings.Builder

	// CSS custom properties from branding
	b.WriteString("/* Auto-generated by Atomicsite */\n\n")
	b.WriteString(":root {\n")
	b.WriteString(fmt.Sprintf("  --container-width: %s;\n", containerWidth))
	b.WriteString(fmt.Sprintf("  --bp-mobile: %s;\n", mobileBP))
	b.WriteString(fmt.Sprintf("  --bp-tablet: %s;\n", tabletBP))
	b.WriteString(fmt.Sprintf("  --color-primary: %s;\n", site.PrimaryColor))
	b.WriteString(fmt.Sprintf("  --color-secondary: %s;\n", site.SecondaryColor))
	b.WriteString(fmt.Sprintf("  --color-bg: %s;\n", site.BgColor))
	b.WriteString(fmt.Sprintf("  --color-text: %s;\n", site.TextColor))
	// Phase 12.9 colour slots. accent_color="" falls back to primary so
	// existing styles that read `color: var(--color-accent)` keep working.
	if site.SurfaceColor != "" {
		b.WriteString(fmt.Sprintf("  --color-surface: %s;\n", site.SurfaceColor))
	}
	if site.BorderColor != "" {
		b.WriteString(fmt.Sprintf("  --color-border: %s;\n", site.BorderColor))
	}
	if site.MutedColor != "" {
		b.WriteString(fmt.Sprintf("  --color-muted: %s;\n", site.MutedColor))
	}
	if site.AccentColor != "" {
		b.WriteString(fmt.Sprintf("  --color-accent: %s;\n", site.AccentColor))
	} else {
		b.WriteString("  --color-accent: var(--color-primary);\n")
	}
	if site.OnPrimaryColor != "" {
		b.WriteString(fmt.Sprintf("  --color-on-primary: %s;\n", site.OnPrimaryColor))
	}
	b.WriteString(fmt.Sprintf("  --font-heading: '%s', system-ui, sans-serif;\n", site.FontHeading))
	b.WriteString(fmt.Sprintf("  --font-body: '%s', system-ui, sans-serif;\n", site.FontBody))
	b.WriteString("}\n\n")

	// Reset
	b.WriteString("*, *::before, *::after { box-sizing: border-box; margin: 0; }\n")
	b.WriteString("html { font-family: var(--font-body); color: var(--color-text); background-color: var(--color-bg); line-height: 1.6; -webkit-font-smoothing: antialiased; }\n")
	b.WriteString("body { min-height: 100dvh; }\n")
	b.WriteString("h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); line-height: 1.15; letter-spacing: -0.01em; }\n")
	b.WriteString("a { color: var(--color-primary); text-decoration: none; }\n")
	b.WriteString("a:hover { text-decoration: underline; }\n")
	b.WriteString("img { max-width: 100%; height: auto; display: block; }\n\n")

	// Baseline utility layer. These classes are common across most starter
	// kits and components, so the build pipeline ships them by default
	// regardless of which CSS rows the site has registered. Sites can
	// override any of these by writing a class with the same name in their
	// css_classes table; the user-defined block runs after this layer.
	b.WriteString("/* --- Atomicsite baseline utilities --- */\n\n")
	b.WriteString(".container { width: 100%; max-width: var(--container-width); margin-inline: auto; padding-inline: 1.5rem; }\n")
	b.WriteString("main { display: block; }\n")
	b.WriteString("section { padding-block: 4rem; }\n")
	b.WriteString(".lede { font-size: 1.25rem; color: color-mix(in oklab, var(--color-text) 75%, transparent); max-width: 60ch; margin-block-start: 1rem; }\n")
	b.WriteString(".actions { display: flex; flex-wrap: wrap; gap: 1rem; margin-block-start: 1.75rem; }\n")
	b.WriteString(".btn { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.75rem 1.25rem; border-radius: 0.5rem; font-weight: 500; transition: transform 150ms ease-out, background-color 150ms ease-out, border-color 150ms ease-out; }\n")
	b.WriteString(".btn:active { transform: scale(0.98); }\n")
	b.WriteString(".btn-primary { background: var(--color-primary); color: white; text-decoration: none; }\n")
	b.WriteString(".btn-primary:hover { background: color-mix(in oklab, var(--color-primary) 85%, black); text-decoration: none; }\n")
	b.WriteString(".btn-secondary { background: transparent; color: var(--color-text); border: 1px solid color-mix(in oklab, var(--color-text) 18%, transparent); text-decoration: none; }\n")
	b.WriteString(".btn-secondary:hover { background: color-mix(in oklab, var(--color-text) 5%, transparent); text-decoration: none; }\n")
	b.WriteString(".btn-link { background: transparent; color: var(--color-primary); padding-inline: 0; }\n")
	b.WriteString(".services-grid, .feature-grid, .team-grid, .project-grid { list-style: none; padding: 0; display: grid; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)); gap: 1.5rem; margin-block-start: 2rem; }\n")
	b.WriteString(".service-card, .feature-tile, .feature-grid-item, .project-card { list-style: none; padding: 1.75rem; border: 1px solid color-mix(in oklab, var(--color-text) 10%, transparent); border-radius: 0.875rem; background: color-mix(in oklab, var(--color-bg) 95%, white); transition: transform 200ms ease-out, box-shadow 200ms ease-out, border-color 200ms ease-out; }\n")
	b.WriteString(".service-card:hover, .feature-tile:hover, .feature-grid-item:hover, .project-card:hover { transform: translateY(-2px); box-shadow: 0 8px 24px color-mix(in oklab, var(--color-text) 8%, transparent); border-color: color-mix(in oklab, var(--color-primary) 30%, transparent); }\n")
	b.WriteString(".service-card h3, .feature-tile h3, .feature-grid-item h3, .project-card h3 { font-size: 1.125rem; margin-block-end: 0.5rem; line-height: 1.3; }\n")
	b.WriteString(".service-card p, .feature-tile p, .feature-grid-item p, .project-card p { color: color-mix(in oklab, var(--color-text) 70%, transparent); margin: 0; font-size: 0.9375rem; line-height: 1.55; }\n")
	b.WriteString(".role { font-size: 0.875rem; color: color-mix(in oklab, var(--color-text) 60%, transparent); text-transform: uppercase; letter-spacing: 0.05em; }\n")
	b.WriteString(".bio { font-size: 0.9375rem; color: color-mix(in oklab, var(--color-text) 75%, transparent); }\n")
	b.WriteString(".gdpr-notice { font-size: 0.875rem; color: color-mix(in oklab, var(--color-text) 65%, transparent); margin-block-start: 1rem; }\n")
	b.WriteString(".pricing-table { display: grid; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)); gap: 1.5rem; margin-block-start: 2rem; }\n")
	b.WriteString(".faq-accordion { margin-block-start: 2rem; }\n")
	b.WriteString("h2 { font-size: clamp(1.75rem, 3vw, 2.25rem); margin-block-end: 1rem; }\n")
	b.WriteString("h3 { font-size: 1.25rem; }\n\n")

	// --- Block layouts. Each block_type renders into <section class="block block--TYPE">.
	// All blocks live inside a centred max-width column; hero + cta + feature_grid get
	// wider columns; text + quote stay narrow for readability.
	b.WriteString("/* --- Block layouts --- */\n")
	b.WriteString(".block { padding-block: 4rem; padding-inline: 1.5rem; max-width: var(--container-width); margin-inline: auto; }\n")
	b.WriteString(".block .eyebrow { text-transform: uppercase; letter-spacing: 0.08em; font-size: 0.75rem; color: var(--color-primary); font-weight: 600; margin-block-end: 0.5rem; }\n")
	b.WriteString(".block .subheading { font-size: 1.0625rem; color: color-mix(in oklab, var(--color-text) 70%, transparent); max-width: 60ch; margin-block-end: 1.5rem; }\n\n")

	// Hero: centred, large headline, optional image below subheading, CTA row.
	b.WriteString(".block--hero { text-align: center; max-width: 56rem; padding-block: 5rem 4rem; }\n")
	b.WriteString(".block--hero .eyebrow { margin-inline: auto; }\n")
	b.WriteString(".block--hero h1 { font-size: clamp(2.25rem, 5vw, 3.75rem); font-weight: 700; line-height: 1.05; letter-spacing: -0.02em; margin-block: 0.75rem 1rem; }\n")
	b.WriteString(".block--hero .subheading { font-size: 1.25rem; max-width: 50ch; margin-inline: auto; }\n")
	b.WriteString(".block--hero img { max-width: 100%; max-height: 26rem; width: auto; margin: 2rem auto 1rem; border-radius: 1rem; box-shadow: 0 12px 40px color-mix(in oklab, var(--color-text) 12%, transparent); }\n")
	b.WriteString(".block--hero a.btn-primary, .block--hero a.btn-secondary { margin: 0.5rem 0.5rem 0 0.5rem; }\n\n")

	// Feature grid: heading top-left, grid below.
	b.WriteString(".block--feature_grid { max-width: 72rem; }\n")
	b.WriteString(".block--feature_grid > h2 { margin-block-end: 0.5rem; }\n\n")

	// Text: long-form column.
	b.WriteString(".block--text { max-width: 42rem; }\n")
	b.WriteString(".block--text h2 { margin-block-end: 1rem; }\n")
	b.WriteString(".block--text p { font-size: 1.0625rem; line-height: 1.65; }\n")
	b.WriteString(".block--text p + p { margin-block-start: 1.25rem; }\n")
	b.WriteString(".block--text a.btn-primary { margin-block-start: 1.5rem; }\n\n")

	// CTA: tinted banner card.
	b.WriteString(".block--cta { text-align: center; max-width: 56rem; padding: 4rem 1.5rem; margin-block: 3rem; background: color-mix(in oklab, var(--color-bg) 80%, var(--color-primary)); border-radius: 1.25rem; }\n")
	b.WriteString(".block--cta h2 { margin-block-end: 0.75rem; }\n")
	b.WriteString(".block--cta p { max-width: 44ch; margin-inline: auto; margin-block-end: 1.5rem; color: color-mix(in oklab, var(--color-text) 80%, transparent); }\n")
	b.WriteString(".block--cta-secondary { background: color-mix(in oklab, var(--color-bg) 92%, var(--color-text)); }\n\n")

	// Image: centred figure with optional caption.
	b.WriteString(".block--image { max-width: 64rem; }\n")
	b.WriteString(".block--image img { margin-inline: auto; border-radius: 0.875rem; box-shadow: 0 8px 24px color-mix(in oklab, var(--color-text) 8%, transparent); }\n")
	b.WriteString(".block--image .caption { font-size: 0.875rem; color: color-mix(in oklab, var(--color-text) 60%, transparent); text-align: center; margin-block-start: 0.75rem; font-style: italic; }\n\n")

	// Quote: editorial pull quote.
	b.WriteString(".block--quote { max-width: 48rem; padding-block: 4rem; }\n")
	b.WriteString(".block--quote blockquote { font-size: 1.5rem; font-weight: 500; line-height: 1.4; margin: 0; padding-inline-start: 1.25rem; border-inline-start: 3px solid var(--color-primary); }\n")
	b.WriteString(".block--quote blockquote p { margin: 0; }\n")
	b.WriteString(".block--quote cite { display: block; margin-block-start: 1.25rem; padding-inline-start: 1.25rem; font-size: 0.9375rem; color: color-mix(in oklab, var(--color-text) 65%, transparent); font-style: normal; }\n\n")

	// Lucide icon SVG inside feature_grid items: tinted square badge above the title.
	b.WriteString(".feature-grid-item .icon { display: inline-flex; align-items: center; justify-content: center; width: 2.75rem; height: 2.75rem; padding: 0.625rem; border-radius: 0.625rem; background: color-mix(in oklab, var(--color-bg) 80%, var(--color-primary)); color: var(--color-primary); margin-block-end: 1rem; }\n")
	b.WriteString(".feature-grid-item .icon svg, .feature-grid-item .icon { box-sizing: border-box; }\n\n")

	// Visual rhythm: every other block--feature_grid gets a tinted background so sections don't blur into one continuous column. Alternate via :nth-of-type.
	b.WriteString(".block--feature_grid:nth-of-type(even) { background: color-mix(in oklab, var(--color-bg) 96%, var(--color-text)); border-radius: 1.25rem; }\n")
	b.WriteString(".block--text + .block--feature_grid, .block--feature_grid + .block--text { margin-block-start: 0; }\n\n")

	// Site-wide spacing: more generous block padding so sections breathe.
	b.WriteString(".block + .block { margin-block-start: 0; }\n\n")

	// --- New block layouts (split_hero, stat_grid, accordion_faq, pricing, logo_strip, code_block, form, embed) ---
	// split_hero: side-by-side on desktop (image right, text left), stacks on mobile.
	b.WriteString(".block--split_hero { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; align-items: center; padding-block: 5rem 4rem; max-width: var(--container-width); }\n")
	b.WriteString(".block--split_hero .split-hero-content { min-width: 0; }\n")
	b.WriteString(".block--split_hero h1 { font-size: clamp(2rem, 4.5vw, 3.5rem); font-weight: 700; line-height: 1.05; letter-spacing: -0.02em; margin-block: 0.75rem 1rem; }\n")
	b.WriteString(".block--split_hero .subheading { font-size: 1.125rem; max-width: 36ch; margin-block-end: 1.75rem; }\n")
	b.WriteString(".block--split_hero img, .block--split_hero picture { width: 100%; max-width: 100%; height: auto; border-radius: 1rem; box-shadow: 0 16px 48px color-mix(in oklab, var(--color-text) 14%, transparent); }\n")
	b.WriteString(".block--split_hero a.btn-primary, .block--split_hero a.btn-secondary { margin-right: 0.75rem; margin-block-start: 0.5rem; }\n\n")

	// stat_grid: 4-up large numbers row. Used for trust signals, social proof.
	b.WriteString(".block--stat_grid { padding-block: 3rem; }\n")
	b.WriteString(".block--stat_grid > h2 { text-align: center; margin-block-end: 0.5rem; }\n")
	b.WriteString(".block--stat_grid > .subheading { text-align: center; margin-inline: auto; margin-block-end: 2.5rem; }\n")
	b.WriteString(".stat-grid { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr)); gap: 2rem; text-align: center; }\n")
	b.WriteString(".stat-grid-item { padding: 1.5rem; }\n")
	b.WriteString(".stat-grid-item .stat-value { font-family: var(--font-heading); font-size: clamp(2.25rem, 4vw, 3rem); font-weight: 700; line-height: 1; color: var(--color-primary); margin-block-end: 0.5rem; letter-spacing: -0.02em; }\n")
	b.WriteString(".stat-grid-item .stat-label { font-size: 0.9375rem; color: color-mix(in oklab, var(--color-text) 70%, transparent); line-height: 1.4; }\n\n")

	// accordion_faq: native <details> / <summary> accordion. No JS needed.
	b.WriteString(".block--accordion_faq { max-width: 56rem; }\n")
	b.WriteString(".block--accordion_faq > h2 { margin-block-end: 2rem; }\n")
	b.WriteString(".faq-accordion { display: flex; flex-direction: column; gap: 0.75rem; }\n")
	b.WriteString(".faq-item { border: 1px solid color-mix(in oklab, var(--color-text) 10%, transparent); border-radius: 0.75rem; background: color-mix(in oklab, var(--color-bg) 96%, white); overflow: hidden; }\n")
	b.WriteString(".faq-item summary { padding: 1.25rem 1.5rem; font-weight: 600; cursor: pointer; list-style: none; display: flex; align-items: center; justify-content: space-between; gap: 1rem; user-select: none; }\n")
	b.WriteString(".faq-item summary::-webkit-details-marker { display: none; }\n")
	b.WriteString(".faq-item summary::after { content: '+'; font-size: 1.5rem; color: var(--color-primary); transition: transform 200ms ease-out; }\n")
	b.WriteString(".faq-item[open] summary::after { transform: rotate(45deg); }\n")
	b.WriteString(".faq-item .faq-body { padding: 0 1.5rem 1.25rem; color: color-mix(in oklab, var(--color-text) 80%, transparent); line-height: 1.6; }\n\n")

	// pricing tiers: 3-up cards with bullet lists + per-tier CTA. featured tier gets primary border.
	b.WriteString(".block--pricing { max-width: var(--container-width); }\n")
	b.WriteString(".block--pricing > h2 { text-align: center; margin-block-end: 0.5rem; }\n")
	b.WriteString(".block--pricing > .subheading { text-align: center; margin-inline: auto; margin-block-end: 2.5rem; }\n")
	b.WriteString(".pricing-grid { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); gap: 1.5rem; align-items: stretch; }\n")
	b.WriteString(".pricing-tier { display: flex; flex-direction: column; padding: 2rem; border: 1px solid color-mix(in oklab, var(--color-text) 12%, transparent); border-radius: 1rem; background: color-mix(in oklab, var(--color-bg) 96%, white); }\n")
	b.WriteString(".pricing-tier.is-featured { border-color: var(--color-primary); border-width: 2px; box-shadow: 0 12px 32px color-mix(in oklab, var(--color-primary) 18%, transparent); }\n")
	b.WriteString(".pricing-tier .tier-name { font-family: var(--font-heading); font-weight: 700; font-size: 1.25rem; margin-block-end: 0.5rem; }\n")
	b.WriteString(".pricing-tier .tier-price { font-size: 2rem; font-weight: 700; color: var(--color-primary); line-height: 1; margin-block-end: 0.25rem; }\n")
	b.WriteString(".pricing-tier .tier-price-period { font-size: 0.875rem; color: color-mix(in oklab, var(--color-text) 60%, transparent); margin-block-end: 1.25rem; }\n")
	b.WriteString(".pricing-tier .tier-description { font-size: 0.9375rem; color: color-mix(in oklab, var(--color-text) 75%, transparent); margin-block-end: 1.25rem; line-height: 1.5; }\n")
	b.WriteString(".pricing-tier ul.tier-features { list-style: none; padding: 0; margin: 0 0 1.5rem 0; flex: 1; }\n")
	b.WriteString(".pricing-tier ul.tier-features li { padding-left: 1.5rem; position: relative; margin-block-end: 0.5rem; font-size: 0.9375rem; line-height: 1.5; }\n")
	b.WriteString(".pricing-tier ul.tier-features li::before { content: '✓'; position: absolute; left: 0; color: var(--color-primary); font-weight: 700; }\n")
	b.WriteString(".pricing-tier .tier-cta { margin-block-start: auto; }\n\n")

	// logo_strip: row of customer logos / partner logos.
	b.WriteString(".block--logo_strip { padding-block: 3rem; text-align: center; }\n")
	b.WriteString(".block--logo_strip .logo-strip-label { font-size: 0.8125rem; text-transform: uppercase; letter-spacing: 0.1em; color: color-mix(in oklab, var(--color-text) 55%, transparent); margin-block-end: 1.5rem; }\n")
	b.WriteString(".logo-strip { list-style: none; padding: 0; margin: 0; display: flex; flex-wrap: wrap; align-items: center; justify-content: center; gap: 2.5rem; opacity: 0.75; }\n")
	b.WriteString(".logo-strip li img { height: 2rem; width: auto; max-width: 8rem; filter: grayscale(100%) opacity(0.7); transition: filter 200ms ease-out; }\n")
	b.WriteString(".logo-strip li img:hover { filter: grayscale(0) opacity(1); }\n\n")

	// code_block: monospace code presentation, optional language label.
	b.WriteString(".block--code_block { max-width: 56rem; }\n")
	b.WriteString(".block--code_block pre { background: color-mix(in oklab, var(--color-bg) 88%, var(--color-text)); color: color-mix(in oklab, var(--color-text) 92%, transparent); border-radius: 0.75rem; padding: 1.5rem; overflow-x: auto; font-family: ui-monospace, 'SF Mono', Monaco, Menlo, monospace; font-size: 0.875rem; line-height: 1.6; }\n")
	b.WriteString(".block--code_block .code-label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em; color: color-mix(in oklab, var(--color-text) 55%, transparent); margin-block-end: 0.5rem; }\n\n")

	// form block: built-in fields + submit. Posts to action URL agent supplies.
	b.WriteString(".block--form { max-width: 36rem; }\n")
	b.WriteString(".block--form > h2 { margin-block-end: 1rem; }\n")
	b.WriteString(".block--form .form-field { display: flex; flex-direction: column; gap: 0.375rem; margin-block-end: 1rem; }\n")
	b.WriteString(".block--form label { font-size: 0.875rem; font-weight: 500; }\n")
	b.WriteString(".block--form input, .block--form textarea, .block--form select { padding: 0.75rem 1rem; border: 1px solid color-mix(in oklab, var(--color-text) 18%, transparent); border-radius: 0.5rem; font-size: 1rem; background: var(--color-bg); color: var(--color-text); transition: border-color 150ms ease-out; }\n")
	b.WriteString(".block--form input:focus, .block--form textarea:focus, .block--form select:focus { outline: none; border-color: var(--color-primary); box-shadow: 0 0 0 3px color-mix(in oklab, var(--color-primary) 18%, transparent); }\n")
	b.WriteString(".block--form textarea { resize: vertical; min-height: 6rem; }\n")
	b.WriteString(".block--form button[type=submit] { padding: 0.75rem 1.5rem; background: var(--color-primary); color: white; border: 0; border-radius: 0.5rem; font-weight: 500; cursor: pointer; transition: background-color 150ms ease-out; }\n")
	b.WriteString(".block--form button[type=submit]:hover { background: color-mix(in oklab, var(--color-primary) 85%, black); }\n\n")

	// embed: iframe-friendly wrapper with aspect ratio + responsive sizing.
	b.WriteString(".block--embed { max-width: 64rem; }\n")
	b.WriteString(".embed-wrapper { position: relative; width: 100%; aspect-ratio: 16 / 9; border-radius: 0.875rem; overflow: hidden; box-shadow: 0 8px 24px color-mix(in oklab, var(--color-text) 8%, transparent); }\n")
	b.WriteString(".embed-wrapper iframe { position: absolute; inset: 0; width: 100%; height: 100%; border: 0; }\n\n")

	// Multi-column footer: when global_blocks data carries `columns: [...]`, footer renders as a 4-up grid with a copyright row underneath.
	b.WriteString(".site-footer .footer-columns { display: grid; grid-template-columns: 2fr 1fr 1fr 1fr; gap: 2rem; margin-block-end: 2.5rem; }\n")
	b.WriteString(".site-footer .footer-column h4 { font-family: var(--font-heading); font-size: 0.8125rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: color-mix(in oklab, var(--color-text) 65%, transparent); margin-block-end: 1rem; }\n")
	b.WriteString(".site-footer .footer-column ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.625rem; }\n")
	b.WriteString(".site-footer .footer-column ul a { font-size: 0.9375rem; }\n")
	b.WriteString(".site-footer .footer-bottom { display: flex; flex-wrap: wrap; gap: 1.5rem; justify-content: space-between; align-items: center; padding-block-start: 1.5rem; border-top: 1px solid color-mix(in oklab, var(--color-text) 8%, transparent); }\n")
	b.WriteString(".site-footer .footer-tagline { font-size: 0.875rem; color: color-mix(in oklab, var(--color-text) 60%, transparent); margin: 0; max-width: 24rem; }\n")
	b.WriteString(".site-footer .footer-social { display: flex; gap: 1rem; align-items: center; }\n")
	b.WriteString(".site-footer .footer-social a { color: color-mix(in oklab, var(--color-text) 65%, transparent); }\n")
	b.WriteString(".site-footer .footer-social a:hover { color: var(--color-primary); }\n\n")

	// Header brand mark: image takes precedence over the first nav link's text when set.
	b.WriteString(".site-header .brand-mark { display: inline-flex; align-items: center; gap: 0.625rem; font-family: var(--font-heading); font-weight: 700; font-size: 1.0625rem; letter-spacing: -0.01em; text-decoration: none; color: var(--color-text); margin-right: auto; }\n")
	b.WriteString(".site-header .brand-mark img { height: 1.75rem; width: auto; }\n\n")

	// Lang switcher: small pill row that the operator can swap into the header global block.
	b.WriteString(".lang-switcher { display: inline-flex; gap: 0.25rem; padding: 0.25rem; background: color-mix(in oklab, var(--color-bg) 88%, var(--color-text)); border-radius: 0.5rem; }\n")
	b.WriteString(".lang-switcher a { font-size: 0.8125rem; padding: 0.25rem 0.625rem; border-radius: 0.375rem; text-transform: uppercase; letter-spacing: 0.05em; color: color-mix(in oklab, var(--color-text) 70%, transparent); }\n")
	b.WriteString(".lang-switcher a.is-active { background: var(--color-bg); color: var(--color-text); font-weight: 600; }\n\n")

	// --- Responsive breakpoints. Mobile-first: collapse multi-column blocks below tablet_breakpoint. ---
	b.WriteString("@media (max-width: " + tabletBP + ") {\n")
	b.WriteString("  .block--split_hero { grid-template-columns: 1fr; gap: 2rem; }\n")
	b.WriteString("  .site-footer .footer-columns { grid-template-columns: 1fr 1fr; gap: 1.5rem; }\n")
	b.WriteString("  .pricing-grid { grid-template-columns: 1fr; }\n")
	b.WriteString("}\n\n")
	b.WriteString("@media (max-width: " + mobileBP + ") {\n")
	b.WriteString("  .block { padding-block: 3rem; padding-inline: 1.25rem; }\n")
	b.WriteString("  .block--hero { padding-block: 3rem; }\n")
	b.WriteString("  .block--hero h1 { font-size: clamp(1.875rem, 7vw, 2.5rem); }\n")
	b.WriteString("  .block--split_hero h1 { font-size: clamp(1.875rem, 7vw, 2.5rem); }\n")
	b.WriteString("  .services-grid, .feature-grid, .team-grid, .project-grid, .stat-grid { grid-template-columns: 1fr; gap: 1rem; }\n")
	b.WriteString("  .site-footer .footer-columns { grid-template-columns: 1fr; }\n")
	b.WriteString("  .site-nav ul { gap: 1rem; }\n")
	b.WriteString("  .site-nav li:first-child a { font-size: 1rem; }\n")
	b.WriteString("  .site-footer .footer-bottom { flex-direction: column; align-items: flex-start; }\n")
	b.WriteString("  .stat-grid-item .stat-value { font-size: clamp(1.875rem, 8vw, 2.5rem); }\n")
	b.WriteString("}\n\n")

	// Site header + footer chrome (rendered from global blocks).
	b.WriteString(".site-header { padding-block: 1.25rem; padding-inline: 1.5rem; border-bottom: 1px solid color-mix(in oklab, var(--color-text) 8%, transparent); position: sticky; top: 0; background: color-mix(in oklab, var(--color-bg) 88%, white); backdrop-filter: blur(12px); z-index: 10; }\n")
	b.WriteString(".site-header > .container, .site-header > div { max-width: 72rem; margin-inline: auto; display: flex; align-items: center; justify-content: space-between; }\n")
	b.WriteString(".site-nav { width: 100%; }\n")
	b.WriteString(".site-nav ul { display: flex; flex-wrap: wrap; gap: 1.75rem; list-style: none; padding: 0; margin: 0; align-items: center; justify-content: flex-end; }\n")
	b.WriteString(".site-nav a { color: var(--color-text); font-weight: 500; font-size: 0.9375rem; text-decoration: none; }\n")
	b.WriteString(".site-nav a:hover { color: var(--color-primary); }\n")
	// First nav link doubles as the brand mark (pull it left, bolder type, no underline). Conventionally agents put the site name with href=/ as the first link.
	b.WriteString(".site-nav li:first-child { margin-right: auto; }\n")
	b.WriteString(".site-nav li:first-child a { font-family: var(--font-heading); font-weight: 700; font-size: 1.0625rem; letter-spacing: -0.01em; }\n")
	// Last nav link auto-styles as the primary CTA pill (book audit / sign up / etc.).
	b.WriteString(".site-nav li:last-child a { background: var(--color-primary); color: white; padding: 0.5rem 1rem; border-radius: 0.5rem; }\n")
	b.WriteString(".site-nav li:last-child a:hover { background: color-mix(in oklab, var(--color-primary) 85%, black); color: white; }\n")
	b.WriteString(".site-footer { padding-block: 3rem; padding-inline: 1.5rem; margin-block-start: 6rem; border-top: 1px solid color-mix(in oklab, var(--color-text) 8%, transparent); }\n")
	b.WriteString(".site-footer > .container, .site-footer > div { max-width: 72rem; margin-inline: auto; }\n")
	b.WriteString(".site-footer nav ul { display: flex; flex-wrap: wrap; gap: 1.5rem; list-style: none; padding: 0; margin: 0 0 1rem 0; font-size: 0.875rem; }\n")
	b.WriteString(".site-footer a { color: color-mix(in oklab, var(--color-text) 70%, transparent); text-decoration: none; }\n")
	b.WriteString(".site-footer a:hover { color: var(--color-primary); }\n")
	b.WriteString(".site-footer-copy { font-size: 0.8125rem; color: color-mix(in oklab, var(--color-text) 55%, transparent); margin: 0; }\n\n")

	// User-defined CSS classes
	if len(classes) > 0 {
		b.WriteString("/* --- Site CSS Classes --- */\n\n")
		currentCategory := ""
		for _, cc := range classes {
			if cc.Category != currentCategory {
				currentCategory = cc.Category
				b.WriteString(fmt.Sprintf("/* %s */\n", currentCategory))
			}
			if cc.UsageNote != "" {
				b.WriteString(fmt.Sprintf("/* %s */\n", cc.UsageNote))
			}
			b.WriteString(cc.Css)
			b.WriteString("\n\n")
		}
	}

	return WriteFile(filepath.Join(wsDir, "src", "styles", "global.css"), b.String())
}
