package builder

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/bright-interaction/slab/internal/store"
)

// nginxLogDir returns the directory nginx writes per-site JSON access logs to.
// Defaults to /var/log/slab; overridable via SLAB_LOG_DIR for tests
// and dev environments without /var/log write access.
func nginxLogDir() string {
	if d := strings.TrimSpace(envSlab("SLAB_LOG_DIR")); d != "" {
		return d
	}
	return "/var/log/slab"
}

// envSlab reads a SLAB_ environment variable, falling back to the pre-rename
// ATOMICSITE_ name so an existing env-file keeps working after the Slab
// rename. Local to the builder package to avoid an import edge to config; it
// mirrors config.Env. The legacy name is derived (not a literal) so a
// prefix-migration guard treats it as a fallback read.
func envSlab(key string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	if suffix, ok := strings.CutPrefix(key, "SLAB_"); ok {
		return os.Getenv("ATOMICSITE_" + suffix)
	}
	return ""
}

// nginxLogPath returns the canonical JSON access log path for a site, keyed by
// slug because that's what the host nginx can derive from $host (the leftmost
// label of the configured wildcard tenant suffix, e.g. *<BUILT_SITE_SUFFIX>).
// The parser tails this file and writes visit_events rows scoped to the
// matching site_id.
func nginxLogPath(slug string) string {
	return filepath.Join(nginxLogDir(), slug+".json.log")
}

// NginxLogPath is the exported version of nginxLogPath for use by the analytics
// parser/manager which needs to know where Nginx will be writing log lines.
// Takes slug, not site_id, because nginx writes the file via $host without
// knowing the internal site_id.
func NginxLogPath(slug string) string {
	return nginxLogPath(slug)
}

// NginxLogDir is the exported log directory for callers that need to ensure
// the directory exists before tailing.
func NginxLogDir() string {
	return nginxLogDir()
}

// RenderNginxConfig writes an nginx.conf snippet to the workspace root. Deployment
// targets that use nginx can include this file. It emits all security headers,
// gzip/brotli, and caching rules derived from site_settings.
//
// Output is written to {wsDir}/nginx.conf (not inside dist/ to avoid shipping
// server config to clients). Deployment is responsible for picking it up.
func RenderNginxConfig(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	settings, _ := queries.ListSettingsBySite(ctx, siteID)
	sm := make(map[string]string)
	for _, s := range settings {
		sm[s.Category+"."+s.Key] = s.Value
	}

	site, err := queries.GetSiteByID(ctx, siteID)
	if err != nil {
		return fmt.Errorf("get site for nginx config: %w", err)
	}

	headers, err := BuildSecurityHeaders(ctx, queries, siteID)
	if err != nil {
		return err
	}

	gzipEnabled := boolSetting(sm["server.gzip_enabled"], true)
	brotliEnabled := boolSetting(sm["server.brotli_enabled"], false) // brotli module often unavailable
	staticTTL := orDefault(sm["server.cache_static_max_age"], "31536000")
	htmlTTL := orDefault(sm["server.cache_html_max_age"], "3600")
	rateLimitEnabled := boolSetting(sm["server.rate_limit_enabled"], false)
	rateLimitRPS := orDefault(sm["server.rate_limit_rps"], "10")

	// Analytics: enable JSON access logs whenever cookieproof or slab
	// tracking is on. The parser tails the file and inserts rows into visit_events.
	analyticsEnabled := boolSetting(sm["analytics.cookieproof_enabled"], false) ||
		boolSetting(sm["analytics.slab_tracking_enabled"], false)

	var b strings.Builder
	b.WriteString("# Auto-generated by Slab. Include in your nginx server block.\n\n")

	// Rate limit zone (must be at http{} level, but we'll include it commented
	// so operators know to hoist it).
	if rateLimitEnabled {
		b.WriteString("# NOTE: the following limit_req_zone must go inside http{} (not server{}):\n")
		b.WriteString(fmt.Sprintf("# limit_req_zone $binary_remote_addr zone=slab_%s:10m rate=%srequests;\n\n", siteID, rateLimitRPS))
	}

	// Gzip
	if gzipEnabled {
		b.WriteString("gzip on;\n")
		b.WriteString("gzip_vary on;\n")
		b.WriteString("gzip_min_length 1024;\n")
		b.WriteString("gzip_types text/plain text/css text/xml application/javascript application/json application/xml application/rss+xml image/svg+xml;\n\n")
	}

	// Brotli
	if brotliEnabled {
		b.WriteString("# Requires ngx_brotli module\n")
		b.WriteString("brotli on;\n")
		b.WriteString("brotli_comp_level 6;\n")
		b.WriteString("brotli_types text/plain text/css application/javascript application/json image/svg+xml;\n\n")
	}

	// Security headers (use always so they apply to error responses too)
	b.WriteString("# Security headers\n")
	writeNginxHeader(&b, "Content-Security-Policy", headers.CSP)
	writeNginxHeader(&b, "Strict-Transport-Security", headers.HSTS)
	writeNginxHeader(&b, "X-Frame-Options", headers.XFrameOptions)
	writeNginxHeader(&b, "X-Content-Type-Options", headers.XContentTypeOptions)
	writeNginxHeader(&b, "Referrer-Policy", headers.ReferrerPolicy)
	writeNginxHeader(&b, "Permissions-Policy", headers.PermissionsPolicy)
	writeNginxHeader(&b, "Cross-Origin-Opener-Policy", headers.COOP)
	writeNginxHeader(&b, "Cross-Origin-Resource-Policy", headers.CORP)
	writeNginxHeader(&b, "Cross-Origin-Embedder-Policy", headers.COEP)
	writeNginxHeader(&b, "X-Permitted-Cross-Domain-Policies", headers.XPermittedCrossDomainPolicies)
	writeNginxHeader(&b, "X-XSS-Protection", headers.XXSSProtection)
	b.WriteString("\n")

	// Rate limit
	if rateLimitEnabled {
		b.WriteString(fmt.Sprintf("limit_req zone=slab_%s burst=20 nodelay;\n\n", siteID))
	}

	// Analytics: JSON-formatted access log consumed by the analytics parser.
	// log_format must be inside http{} in real nginx; we still emit it here so
	// operators can hoist or include it. escape=json keeps strings safe.
	if analyticsEnabled {
		b.WriteString("# Slab analytics: JSON access log (parsed by Go log tail)\n")
		b.WriteString("# NOTE: log_format must be inside http{} block. Hoist if including this snippet inside server{}.\n")
		b.WriteString("log_format slab_json escape=json '{'\n")
		b.WriteString("  '\"ts\":\"$time_iso8601\",'\n")
		b.WriteString(fmt.Sprintf("  '\"site_id\":\"%s\",'\n", siteID))
		b.WriteString("  '\"ip\":\"$remote_addr\",'\n")
		b.WriteString("  '\"ua\":\"$http_user_agent\",'\n")
		b.WriteString("  '\"al\":\"$http_accept_language\",'\n")
		b.WriteString("  '\"path\":\"$request_uri\",'\n")
		b.WriteString("  '\"status\":$status,'\n")
		b.WriteString("  '\"ms\":$request_time,'\n")
		b.WriteString("  '\"ref\":\"$http_referer\",'\n")
		// CF-IPCountry is the standard ISO 3166-1 alpha-2 country code
		// Cloudflare adds to every request when the site is fronted by CF.
		// Empty for non-CF deployments. The analytics parser drops empties
		// rather than poisoning the country breakdown.
		b.WriteString("  '\"country\":\"$http_cf_ipcountry\"'\n")
		b.WriteString("'}';\n")
		b.WriteString(fmt.Sprintf("access_log %s slab_json;\n\n", nginxLogPath(site.Slug)))
	}

	// Redirects emit BEFORE cache locations: nginx evaluates regex `location`
	// blocks in source order and the first match wins. A redirect rule like
	// `~ ^/old-path/(.*)$` must be checked before `~* \.html$` or the redirect
	// would never fire on /old-path/page.html. Exact matches (`location =`)
	// take absolute priority regardless of order so this is harmless for them.
	redirects, _ := queries.ListRedirectsBySite(ctx, siteID)
	b.WriteString(BuildRedirectBlock(redirects))

	// Hashed assets: long-cache immutable
	b.WriteString("location /_assets/ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", staticTTL))
	b.WriteString("    add_header Cache-Control \"public, immutable\" always;\n")
	b.WriteString("}\n\n")

	// Media: long-cache (content-addressed)
	b.WriteString("location /media/ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", staticTTL))
	b.WriteString("    add_header Cache-Control \"public, immutable\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("}\n\n")

	// CookieProof widget bundle. Filename is content-addressed (hash
	// covers widget bytes + per-site config prefix), so revisions and
	// branding/copy edits produce a fresh filename. Long-cache + must-
	// revalidate so visitors still pick up the next file when the
	// site rebuilds.
	b.WriteString("location ~* ^/_ccb\\.[a-f0-9]+\\.js$ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", staticTTL))
	b.WriteString("    add_header Cache-Control \"public, immutable\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("}\n\n")

	// HTML: short cache (allow quick content updates)
	b.WriteString("location ~* \\.html$ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", htmlTTL))
	b.WriteString("    add_header Cache-Control \"public\" always;\n")
	b.WriteString("}\n")

	return WriteFile(filepath.Join(wsDir, "nginx.conf"), b.String())
}

func writeNginxHeader(b *strings.Builder, name, value string) {
	if value == "" {
		return
	}
	// Escape double quotes in header values
	escaped := strings.ReplaceAll(value, `"`, `\"`)
	b.WriteString(fmt.Sprintf("add_header %s \"%s\" always;\n", name, escaped))
}
