package builder

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/bright-interaction/slab/internal/store"
)

// nginxLogDir returns the directory nginx writes per-site JSON access logs to.
// Defaults to /var/log/atomicsite; overridable via ATOMICSITE_LOG_DIR for tests
// and dev environments without /var/log write access.
func nginxLogDir() string {
	if d := strings.TrimSpace(os.Getenv("ATOMICSITE_LOG_DIR")); d != "" {
		return d
	}
	return "/var/log/atomicsite"
}

// nginxLogPath returns the canonical JSON access log path for a site.
// Centralised so the builder + analytics parser stay in sync.
func nginxLogPath(siteID string) string {
	return filepath.Join(nginxLogDir(), siteID+".json.log")
}

// NginxLogPath is the exported version of nginxLogPath for use by the analytics
// parser/manager which needs to know where Nginx will be writing log lines.
func NginxLogPath(siteID string) string {
	return nginxLogPath(siteID)
}

// NginxLogDir is the exported log directory for callers that need to ensure
// the directory exists before tailing.
func NginxLogDir() string {
	return nginxLogDir()
}

// RenderNginxConfig writes an nginx.conf snippet to the workspace root. Deployment
// targets that use nginx can include this file. It emits all security headers,
// gzip/brotli, and caching rules derived from site_settings.
//
// Output is written to {wsDir}/nginx.conf (not inside dist/ to avoid shipping
// server config to clients). Deployment is responsible for picking it up.
func RenderNginxConfig(ctx context.Context, queries *store.Queries, siteID string, wsDir string) error {
	settings, _ := queries.ListSettingsBySite(ctx, siteID)
	sm := make(map[string]string)
	for _, s := range settings {
		sm[s.Category+"."+s.Key] = s.Value
	}

	headers, err := BuildSecurityHeaders(ctx, queries, siteID)
	if err != nil {
		return err
	}

	gzipEnabled := boolSetting(sm["server.gzip_enabled"], true)
	brotliEnabled := boolSetting(sm["server.brotli_enabled"], false) // brotli module often unavailable
	staticTTL := orDefault(sm["server.cache_static_max_age"], "31536000")
	htmlTTL := orDefault(sm["server.cache_html_max_age"], "3600")
	rateLimitEnabled := boolSetting(sm["server.rate_limit_enabled"], false)
	rateLimitRPS := orDefault(sm["server.rate_limit_rps"], "10")

	// Analytics: enable JSON access logs whenever cookieproof or atomicsite
	// tracking is on. The parser tails the file and inserts rows into visit_events.
	analyticsEnabled := boolSetting(sm["analytics.cookieproof_enabled"], false) ||
		boolSetting(sm["analytics.atomicsite_tracking_enabled"], false)

	var b strings.Builder
	b.WriteString("# Auto-generated by Atomicsite. Include in your nginx server block.\n\n")

	// Rate limit zone (must be at http{} level, but we'll include it commented
	// so operators know to hoist it).
	if rateLimitEnabled {
		b.WriteString("# NOTE: the following limit_req_zone must go inside http{} (not server{}):\n")
		b.WriteString(fmt.Sprintf("# limit_req_zone $binary_remote_addr zone=atomicsite_%s:10m rate=%srequests;\n\n", siteID, rateLimitRPS))
	}

	// Gzip
	if gzipEnabled {
		b.WriteString("gzip on;\n")
		b.WriteString("gzip_vary on;\n")
		b.WriteString("gzip_min_length 1024;\n")
		b.WriteString("gzip_types text/plain text/css text/xml application/javascript application/json application/xml application/rss+xml image/svg+xml;\n\n")
	}

	// Brotli
	if brotliEnabled {
		b.WriteString("# Requires ngx_brotli module\n")
		b.WriteString("brotli on;\n")
		b.WriteString("brotli_comp_level 6;\n")
		b.WriteString("brotli_types text/plain text/css application/javascript application/json image/svg+xml;\n\n")
	}

	// Security headers (use always so they apply to error responses too)
	b.WriteString("# Security headers\n")
	writeNginxHeader(&b, "Content-Security-Policy", headers.CSP)
	writeNginxHeader(&b, "Strict-Transport-Security", headers.HSTS)
	writeNginxHeader(&b, "X-Frame-Options", headers.XFrameOptions)
	writeNginxHeader(&b, "X-Content-Type-Options", headers.XContentTypeOptions)
	writeNginxHeader(&b, "Referrer-Policy", headers.ReferrerPolicy)
	writeNginxHeader(&b, "Permissions-Policy", headers.PermissionsPolicy)
	writeNginxHeader(&b, "Cross-Origin-Opener-Policy", headers.COOP)
	writeNginxHeader(&b, "Cross-Origin-Resource-Policy", headers.CORP)
	writeNginxHeader(&b, "Cross-Origin-Embedder-Policy", headers.COEP)
	b.WriteString("\n")

	// Rate limit
	if rateLimitEnabled {
		b.WriteString(fmt.Sprintf("limit_req zone=atomicsite_%s burst=20 nodelay;\n\n", siteID))
	}

	// Analytics: JSON-formatted access log consumed by the analytics parser.
	// log_format must be inside http{} in real nginx; we still emit it here so
	// operators can hoist or include it. escape=json keeps strings safe.
	if analyticsEnabled {
		b.WriteString("# Atomicsite analytics: JSON access log (parsed by Go log tail)\n")
		b.WriteString("# NOTE: log_format must be inside http{} block. Hoist if including this snippet inside server{}.\n")
		b.WriteString("log_format atomicsite_json escape=json '{'\n")
		b.WriteString("  '\"ts\":\"$time_iso8601\",'\n")
		b.WriteString(fmt.Sprintf("  '\"site_id\":\"%s\",'\n", siteID))
		b.WriteString("  '\"ip\":\"$remote_addr\",'\n")
		b.WriteString("  '\"ua\":\"$http_user_agent\",'\n")
		b.WriteString("  '\"al\":\"$http_accept_language\",'\n")
		b.WriteString("  '\"path\":\"$request_uri\",'\n")
		b.WriteString("  '\"status\":$status,'\n")
		b.WriteString("  '\"ms\":$request_time,'\n")
		b.WriteString("  '\"ref\":\"$http_referer\"'\n")
		b.WriteString("'}';\n")
		b.WriteString(fmt.Sprintf("access_log %s atomicsite_json;\n\n", nginxLogPath(siteID)))
	}

	// Hashed assets: long-cache immutable
	b.WriteString("location /_assets/ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", staticTTL))
	b.WriteString("    add_header Cache-Control \"public, immutable\" always;\n")
	b.WriteString("}\n\n")

	// Media: long-cache (content-addressed)
	b.WriteString("location /media/ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", staticTTL))
	b.WriteString("    add_header Cache-Control \"public, immutable\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("}\n\n")

	// HTML: short cache (allow quick content updates)
	b.WriteString("location ~* \\.html$ {\n")
	b.WriteString(fmt.Sprintf("    expires %ss;\n", htmlTTL))
	b.WriteString("    add_header Cache-Control \"public\" always;\n")
	b.WriteString("}\n")

	return WriteFile(filepath.Join(wsDir, "nginx.conf"), b.String())
}

func writeNginxHeader(b *strings.Builder, name, value string) {
	if value == "" {
		return
	}
	// Escape double quotes in header values
	escaped := strings.ReplaceAll(value, `"`, `\"`)
	b.WriteString(fmt.Sprintf("add_header %s \"%s\" always;\n", name, escaped))
}
