// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_keys.sql

package store

import (
	"context"
)

const createAgentKey = `-- name: CreateAgentKey :exec
INSERT INTO agent_keys (id, site_id, name, key_hash, capabilities, is_active, created_at)
VALUES (?, ?, ?, ?, ?, 1, datetime('now'))
`

type CreateAgentKeyParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	KeyHash      string `json:"key_hash"`
	Capabilities string `json:"capabilities"`
}

func (q *Queries) CreateAgentKey(ctx context.Context, arg CreateAgentKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAgentKey,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.KeyHash,
		arg.Capabilities,
	)
	return err
}

const deactivateAgentKey = `-- name: DeactivateAgentKey :exec
UPDATE agent_keys SET is_active = 0 WHERE id = ?
`

func (q *Queries) DeactivateAgentKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivateAgentKey, id)
	return err
}

const deleteAgentKey = `-- name: DeleteAgentKey :exec
DELETE FROM agent_keys WHERE id = ?
`

func (q *Queries) DeleteAgentKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentKey, id)
	return err
}

const getAgentKeyByHash = `-- name: GetAgentKeyByHash :one
SELECT id, site_id, name, key_hash, capabilities, is_active, last_used_at, created_at
FROM agent_keys
WHERE key_hash = ? AND is_active = 1
`

func (q *Queries) GetAgentKeyByHash(ctx context.Context, keyHash string) (AgentKey, error) {
	row := q.db.QueryRowContext(ctx, getAgentKeyByHash, keyHash)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.KeyHash,
		&i.Capabilities,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentKeyByID = `-- name: GetAgentKeyByID :one
SELECT id, site_id, name, key_hash, capabilities, is_active, last_used_at, created_at
FROM agent_keys
WHERE id = ?
`

func (q *Queries) GetAgentKeyByID(ctx context.Context, id string) (AgentKey, error) {
	row := q.db.QueryRowContext(ctx, getAgentKeyByID, id)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.KeyHash,
		&i.Capabilities,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentKeysBySite = `-- name: ListAgentKeysBySite :many
SELECT id, site_id, name, capabilities, is_active, last_used_at, created_at
FROM agent_keys
WHERE site_id = ? ORDER BY created_at DESC
`

type ListAgentKeysBySiteRow struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	Capabilities string `json:"capabilities"`
	IsActive     int64  `json:"is_active"`
	LastUsedAt   string `json:"last_used_at"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) ListAgentKeysBySite(ctx context.Context, siteID string) ([]ListAgentKeysBySiteRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentKeysBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentKeysBySiteRow{}
	for rows.Next() {
		var i ListAgentKeysBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Capabilities,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentKeyLastUsed = `-- name: UpdateAgentKeyLastUsed :exec
UPDATE agent_keys SET last_used_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateAgentKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAgentKeyLastUsed, id)
	return err
}
