// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package store

import (
	"context"
)

const bumpSiteAppInstallLastUsed = `-- name: BumpSiteAppInstallLastUsed :exec
UPDATE site_app_installs SET last_used_at = datetime('now'), updated_at = datetime('now')
WHERE site_id = ? AND app_id = ?
`

type BumpSiteAppInstallLastUsedParams struct {
	SiteID string `json:"site_id"`
	AppID  string `json:"app_id"`
}

func (q *Queries) BumpSiteAppInstallLastUsed(ctx context.Context, arg BumpSiteAppInstallLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, bumpSiteAppInstallLastUsed, arg.SiteID, arg.AppID)
	return err
}

const deactivateApp = `-- name: DeactivateApp :exec
UPDATE apps SET is_active = 0, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) DeactivateApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivateApp, id)
	return err
}

const deleteSiteAppInstall = `-- name: DeleteSiteAppInstall :exec
DELETE FROM site_app_installs WHERE site_id = ? AND app_id = ?
`

type DeleteSiteAppInstallParams struct {
	SiteID string `json:"site_id"`
	AppID  string `json:"app_id"`
}

func (q *Queries) DeleteSiteAppInstall(ctx context.Context, arg DeleteSiteAppInstallParams) error {
	_, err := q.db.ExecContext(ctx, deleteSiteAppInstall, arg.SiteID, arg.AppID)
	return err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, slug, name, description, category, publisher, icon_url, mcp_url, docs_url, version, credentials_schema_json, is_curated, is_active, created_at, updated_at FROM apps WHERE id = ?
`

func (q *Queries) GetAppByID(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Publisher,
		&i.IconUrl,
		&i.McpUrl,
		&i.DocsUrl,
		&i.Version,
		&i.CredentialsSchemaJson,
		&i.IsCurated,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, slug, name, description, category, publisher, icon_url, mcp_url, docs_url, version, credentials_schema_json, is_curated, is_active, created_at, updated_at FROM apps WHERE slug = ?
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Publisher,
		&i.IconUrl,
		&i.McpUrl,
		&i.DocsUrl,
		&i.Version,
		&i.CredentialsSchemaJson,
		&i.IsCurated,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteAppInstall = `-- name: GetSiteAppInstall :one
SELECT site_id, app_id, status, credentials_json, installed_by, last_used_at, notes, created_at, updated_at FROM site_app_installs WHERE site_id = ? AND app_id = ?
`

type GetSiteAppInstallParams struct {
	SiteID string `json:"site_id"`
	AppID  string `json:"app_id"`
}

func (q *Queries) GetSiteAppInstall(ctx context.Context, arg GetSiteAppInstallParams) (SiteAppInstall, error) {
	row := q.db.QueryRowContext(ctx, getSiteAppInstall, arg.SiteID, arg.AppID)
	var i SiteAppInstall
	err := row.Scan(
		&i.SiteID,
		&i.AppID,
		&i.Status,
		&i.CredentialsJson,
		&i.InstalledBy,
		&i.LastUsedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveApps = `-- name: ListActiveApps :many
SELECT id, slug, name, description, category, publisher, icon_url, mcp_url, docs_url, version, credentials_schema_json, is_curated, is_active, created_at, updated_at FROM apps WHERE is_active = 1 ORDER BY category ASC, name ASC
`

func (q *Queries) ListActiveApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listActiveApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Publisher,
			&i.IconUrl,
			&i.McpUrl,
			&i.DocsUrl,
			&i.Version,
			&i.CredentialsSchemaJson,
			&i.IsCurated,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByCategory = `-- name: ListAppsByCategory :many
SELECT id, slug, name, description, category, publisher, icon_url, mcp_url, docs_url, version, credentials_schema_json, is_curated, is_active, created_at, updated_at FROM apps WHERE is_active = 1 AND category = ? ORDER BY name ASC
`

func (q *Queries) ListAppsByCategory(ctx context.Context, category string) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Publisher,
			&i.IconUrl,
			&i.McpUrl,
			&i.DocsUrl,
			&i.Version,
			&i.CredentialsSchemaJson,
			&i.IsCurated,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteAppInstalls = `-- name: ListSiteAppInstalls :many
SELECT i.site_id, i.app_id, i.status, i.credentials_json, i.installed_by, i.last_used_at, i.notes, i.created_at, i.updated_at, a.slug as app_slug, a.name as app_name, a.description as app_description,
       a.category as app_category, a.icon_url as app_icon_url, a.publisher as app_publisher,
       a.version as app_version
FROM site_app_installs i
JOIN apps a ON a.id = i.app_id
WHERE i.site_id = ?
ORDER BY a.category ASC, a.name ASC
`

type ListSiteAppInstallsRow struct {
	SiteID          string `json:"site_id"`
	AppID           string `json:"app_id"`
	Status          string `json:"status"`
	CredentialsJson string `json:"credentials_json"`
	InstalledBy     string `json:"installed_by"`
	LastUsedAt      string `json:"last_used_at"`
	Notes           string `json:"notes"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	AppSlug         string `json:"app_slug"`
	AppName         string `json:"app_name"`
	AppDescription  string `json:"app_description"`
	AppCategory     string `json:"app_category"`
	AppIconUrl      string `json:"app_icon_url"`
	AppPublisher    string `json:"app_publisher"`
	AppVersion      string `json:"app_version"`
}

func (q *Queries) ListSiteAppInstalls(ctx context.Context, siteID string) ([]ListSiteAppInstallsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSiteAppInstalls, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteAppInstallsRow{}
	for rows.Next() {
		var i ListSiteAppInstallsRow
		if err := rows.Scan(
			&i.SiteID,
			&i.AppID,
			&i.Status,
			&i.CredentialsJson,
			&i.InstalledBy,
			&i.LastUsedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppSlug,
			&i.AppName,
			&i.AppDescription,
			&i.AppCategory,
			&i.AppIconUrl,
			&i.AppPublisher,
			&i.AppVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteAppInstallStatus = `-- name: SetSiteAppInstallStatus :exec
UPDATE site_app_installs SET status = ?, updated_at = datetime('now')
WHERE site_id = ? AND app_id = ?
`

type SetSiteAppInstallStatusParams struct {
	Status string `json:"status"`
	SiteID string `json:"site_id"`
	AppID  string `json:"app_id"`
}

func (q *Queries) SetSiteAppInstallStatus(ctx context.Context, arg SetSiteAppInstallStatusParams) error {
	_, err := q.db.ExecContext(ctx, setSiteAppInstallStatus, arg.Status, arg.SiteID, arg.AppID)
	return err
}

const upsertApp = `-- name: UpsertApp :exec
INSERT INTO apps (id, slug, name, description, category, publisher, icon_url, mcp_url, docs_url, version, credentials_schema_json, is_curated, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    slug = excluded.slug,
    name = excluded.name,
    description = excluded.description,
    category = excluded.category,
    publisher = excluded.publisher,
    icon_url = excluded.icon_url,
    mcp_url = excluded.mcp_url,
    docs_url = excluded.docs_url,
    version = excluded.version,
    credentials_schema_json = excluded.credentials_schema_json,
    is_curated = excluded.is_curated,
    is_active = excluded.is_active,
    updated_at = datetime('now')
`

type UpsertAppParams struct {
	ID                    string `json:"id"`
	Slug                  string `json:"slug"`
	Name                  string `json:"name"`
	Description           string `json:"description"`
	Category              string `json:"category"`
	Publisher             string `json:"publisher"`
	IconUrl               string `json:"icon_url"`
	McpUrl                string `json:"mcp_url"`
	DocsUrl               string `json:"docs_url"`
	Version               string `json:"version"`
	CredentialsSchemaJson string `json:"credentials_schema_json"`
	IsCurated             int64  `json:"is_curated"`
	IsActive              int64  `json:"is_active"`
}

func (q *Queries) UpsertApp(ctx context.Context, arg UpsertAppParams) error {
	_, err := q.db.ExecContext(ctx, upsertApp,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Publisher,
		arg.IconUrl,
		arg.McpUrl,
		arg.DocsUrl,
		arg.Version,
		arg.CredentialsSchemaJson,
		arg.IsCurated,
		arg.IsActive,
	)
	return err
}

const upsertSiteAppInstall = `-- name: UpsertSiteAppInstall :exec
INSERT INTO site_app_installs (site_id, app_id, status, credentials_json, installed_by, notes)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(site_id, app_id) DO UPDATE SET
    status = excluded.status,
    credentials_json = excluded.credentials_json,
    installed_by = excluded.installed_by,
    notes = excluded.notes,
    updated_at = datetime('now')
`

type UpsertSiteAppInstallParams struct {
	SiteID          string `json:"site_id"`
	AppID           string `json:"app_id"`
	Status          string `json:"status"`
	CredentialsJson string `json:"credentials_json"`
	InstalledBy     string `json:"installed_by"`
	Notes           string `json:"notes"`
}

func (q *Queries) UpsertSiteAppInstall(ctx context.Context, arg UpsertSiteAppInstallParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteAppInstall,
		arg.SiteID,
		arg.AppID,
		arg.Status,
		arg.CredentialsJson,
		arg.InstalledBy,
		arg.Notes,
	)
	return err
}
