// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package store

import (
	"context"
)

const deleteAuditLogOlderThan = `-- name: DeleteAuditLogOlderThan :execrows
DELETE FROM audit_log WHERE created_at < ?
`

func (q *Queries) DeleteAuditLogOlderThan(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditLogOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAuditLogByResource = `-- name: ListAuditLogByResource :many
SELECT id, actor_user_id, actor_role, actor_ip,
       site_id, action, resource_type, resource_id, changes_json, created_at
FROM audit_log
WHERE resource_type = ? AND resource_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditLogByResourceParams struct {
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByResource, arg.ResourceType, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorIp,
			&i.SiteID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ChangesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogBySite = `-- name: ListAuditLogBySite :many
SELECT id, actor_user_id, actor_role, actor_ip,
       site_id, action, resource_type, resource_id, changes_json, created_at
FROM audit_log
WHERE site_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditLogBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAuditLogBySite(ctx context.Context, arg ListAuditLogBySiteParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorIp,
			&i.SiteID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ChangesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogGlobal = `-- name: ListAuditLogGlobal :many
SELECT id, actor_user_id, actor_role, actor_ip,
       site_id, action, resource_type, resource_id, changes_json, created_at
FROM audit_log
ORDER BY created_at DESC
LIMIT ?
`

// Used by the workspace-admin "everything that happened" feed. site_id
// can be empty for non-site-scoped actions (member invites, secret
// rotations).
func (q *Queries) ListAuditLogGlobal(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogGlobal, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorIp,
			&i.SiteID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ChangesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_log (
    id, actor_user_id, actor_role, actor_ip,
    site_id, action, resource_type, resource_id, changes_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type WriteAuditLogParams struct {
	ID           string `json:"id"`
	ActorUserID  string `json:"actor_user_id"`
	ActorRole    string `json:"actor_role"`
	ActorIp      string `json:"actor_ip"`
	SiteID       string `json:"site_id"`
	Action       string `json:"action"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	ChangesJson  string `json:"changes_json"`
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, writeAuditLog,
		arg.ID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorIp,
		arg.SiteID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ChangesJson,
	)
	return err
}
