// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_events.sql

package store

import (
	"context"
)

const getBillingEventByExternalID = `-- name: GetBillingEventByExternalID :one
SELECT id, workspace_id, provider, external_event_id, event_type,
       payload_json, processed_at, error, created_at
FROM billing_events
WHERE provider = ? AND external_event_id = ?
`

type GetBillingEventByExternalIDParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetBillingEventByExternalID(ctx context.Context, arg GetBillingEventByExternalIDParams) (BillingEvent, error) {
	row := q.db.QueryRowContext(ctx, getBillingEventByExternalID, arg.Provider, arg.ExternalEventID)
	var i BillingEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalEventID,
		&i.EventType,
		&i.PayloadJson,
		&i.ProcessedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedBillingEvents = `-- name: ListUnprocessedBillingEvents :many
SELECT id, workspace_id, provider, external_event_id, event_type,
       payload_json, processed_at, error, created_at
FROM billing_events
WHERE processed_at = ''
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) ListUnprocessedBillingEvents(ctx context.Context) ([]BillingEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUnprocessedBillingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingEvent{}
	for rows.Next() {
		var i BillingEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ExternalEventID,
			&i.EventType,
			&i.PayloadJson,
			&i.ProcessedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingEventProcessed = `-- name: MarkBillingEventProcessed :exec
UPDATE billing_events
SET processed_at = datetime('now'), error = ?
WHERE id = ?
`

type MarkBillingEventProcessedParams struct {
	Error string `json:"error"`
	ID    string `json:"id"`
}

func (q *Queries) MarkBillingEventProcessed(ctx context.Context, arg MarkBillingEventProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markBillingEventProcessed, arg.Error, arg.ID)
	return err
}

const purgeOldBillingEvents = `-- name: PurgeOldBillingEvents :exec
DELETE FROM billing_events
WHERE processed_at != '' AND processed_at < ?
`

// Run by retention.Manager. 30-day retention; processed events older
// than the cutoff are dropped. Unprocessed events stay forever so the
// operator can investigate.
func (q *Queries) PurgeOldBillingEvents(ctx context.Context, processedAt string) error {
	_, err := q.db.ExecContext(ctx, purgeOldBillingEvents, processedAt)
	return err
}

const recordBillingEvent = `-- name: RecordBillingEvent :exec
INSERT OR IGNORE INTO billing_events (id, workspace_id, provider, external_event_id, event_type, payload_json)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordBillingEventParams struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
	EventType       string `json:"event_type"`
	PayloadJson     string `json:"payload_json"`
}

// UNIQUE(provider, external_event_id) makes duplicate inserts no-op
// via INSERT OR IGNORE. Idempotency at the schema layer means handlers
// don't need a separate "have we seen this id" check.
func (q *Queries) RecordBillingEvent(ctx context.Context, arg RecordBillingEventParams) error {
	_, err := q.db.ExecContext(ctx, recordBillingEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.ExternalEventID,
		arg.EventType,
		arg.PayloadJson,
	)
	return err
}
