// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: block_locales.sql

package store

import (
	"context"
)

const deleteBlockLocale = `-- name: DeleteBlockLocale :exec
DELETE FROM block_locales WHERE block_id = ? AND locale = ?
`

type DeleteBlockLocaleParams struct {
	BlockID string `json:"block_id"`
	Locale  string `json:"locale"`
}

func (q *Queries) DeleteBlockLocale(ctx context.Context, arg DeleteBlockLocaleParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockLocale, arg.BlockID, arg.Locale)
	return err
}

const deleteBlockLocalesByLocale = `-- name: DeleteBlockLocalesByLocale :exec
DELETE FROM block_locales WHERE block_id IN (
    SELECT b.id FROM blocks b
    JOIN pages p ON p.id = b.page_id
    WHERE p.site_id = ?
) AND locale = ?
`

type DeleteBlockLocalesByLocaleParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) DeleteBlockLocalesByLocale(ctx context.Context, arg DeleteBlockLocalesByLocaleParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockLocalesByLocale, arg.SiteID, arg.Locale)
	return err
}

const getBlockLocale = `-- name: GetBlockLocale :one
SELECT block_id, locale, data_json, is_visible, created_at, updated_at FROM block_locales WHERE block_id = ? AND locale = ?
`

type GetBlockLocaleParams struct {
	BlockID string `json:"block_id"`
	Locale  string `json:"locale"`
}

func (q *Queries) GetBlockLocale(ctx context.Context, arg GetBlockLocaleParams) (BlockLocale, error) {
	row := q.db.QueryRowContext(ctx, getBlockLocale, arg.BlockID, arg.Locale)
	var i BlockLocale
	err := row.Scan(
		&i.BlockID,
		&i.Locale,
		&i.DataJson,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockLocalesByBlock = `-- name: ListBlockLocalesByBlock :many
SELECT block_id, locale, data_json, is_visible, created_at, updated_at FROM block_locales WHERE block_id = ? ORDER BY locale ASC
`

func (q *Queries) ListBlockLocalesByBlock(ctx context.Context, blockID string) ([]BlockLocale, error) {
	rows, err := q.db.QueryContext(ctx, listBlockLocalesByBlock, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockLocale{}
	for rows.Next() {
		var i BlockLocale
		if err := rows.Scan(
			&i.BlockID,
			&i.Locale,
			&i.DataJson,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockLocalesByPage = `-- name: ListBlockLocalesByPage :many
SELECT bl.block_id, bl.locale, bl.data_json, bl.is_visible, bl.created_at, bl.updated_at FROM block_locales bl
JOIN blocks b ON b.id = bl.block_id
WHERE b.page_id = ?
ORDER BY b.sort_order ASC, bl.locale ASC
`

func (q *Queries) ListBlockLocalesByPage(ctx context.Context, pageID string) ([]BlockLocale, error) {
	rows, err := q.db.QueryContext(ctx, listBlockLocalesByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockLocale{}
	for rows.Next() {
		var i BlockLocale
		if err := rows.Scan(
			&i.BlockID,
			&i.Locale,
			&i.DataJson,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlockLocale = `-- name: UpsertBlockLocale :exec
INSERT INTO block_locales (block_id, locale, data_json, is_visible)
VALUES (?, ?, ?, ?)
ON CONFLICT(block_id, locale) DO UPDATE SET
    data_json = excluded.data_json,
    is_visible = excluded.is_visible,
    updated_at = datetime('now')
`

type UpsertBlockLocaleParams struct {
	BlockID   string `json:"block_id"`
	Locale    string `json:"locale"`
	DataJson  string `json:"data_json"`
	IsVisible int64  `json:"is_visible"`
}

func (q *Queries) UpsertBlockLocale(ctx context.Context, arg UpsertBlockLocaleParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlockLocale,
		arg.BlockID,
		arg.Locale,
		arg.DataJson,
		arg.IsVisible,
	)
	return err
}
