// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clarifications.sql

package store

import (
	"context"
)

const cancelClarification = `-- name: CancelClarification :exec
UPDATE clarifications
SET status = 'cancelled',
    resolved_by = ?,
    resolved_at = datetime('now')
WHERE id = ? AND site_id = ? AND status = 'pending'
`

type CancelClarificationParams struct {
	ResolvedBy string `json:"resolved_by"`
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
}

func (q *Queries) CancelClarification(ctx context.Context, arg CancelClarificationParams) error {
	_, err := q.db.ExecContext(ctx, cancelClarification, arg.ResolvedBy, arg.ID, arg.SiteID)
	return err
}

const countPendingClarificationsBySite = `-- name: CountPendingClarificationsBySite :one
SELECT COUNT(*) FROM clarifications WHERE site_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingClarificationsBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingClarificationsBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClarification = `-- name: CreateClarification :exec
INSERT INTO clarifications (id, site_id, requested_by, question, context, options_json, status, resolution_option, resolution_text, resolved_by, created_at, resolved_at)
VALUES (?, ?, ?, ?, ?, ?, 'pending', -1, '', '', datetime('now'), '')
`

type CreateClarificationParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	RequestedBy string `json:"requested_by"`
	Question    string `json:"question"`
	Context     string `json:"context"`
	OptionsJson string `json:"options_json"`
}

func (q *Queries) CreateClarification(ctx context.Context, arg CreateClarificationParams) error {
	_, err := q.db.ExecContext(ctx, createClarification,
		arg.ID,
		arg.SiteID,
		arg.RequestedBy,
		arg.Question,
		arg.Context,
		arg.OptionsJson,
	)
	return err
}

const getClarificationByID = `-- name: GetClarificationByID :one
SELECT id, site_id, requested_by, question, context, options_json, status, resolution_option, resolution_text, resolved_by, created_at, resolved_at FROM clarifications WHERE id = ? AND site_id = ?
`

type GetClarificationByIDParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) GetClarificationByID(ctx context.Context, arg GetClarificationByIDParams) (Clarification, error) {
	row := q.db.QueryRowContext(ctx, getClarificationByID, arg.ID, arg.SiteID)
	var i Clarification
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.RequestedBy,
		&i.Question,
		&i.Context,
		&i.OptionsJson,
		&i.Status,
		&i.ResolutionOption,
		&i.ResolutionText,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listAllClarificationsBySite = `-- name: ListAllClarificationsBySite :many
SELECT id, site_id, requested_by, question, context, options_json, status, resolution_option, resolution_text, resolved_by, created_at, resolved_at FROM clarifications WHERE site_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListAllClarificationsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAllClarificationsBySite(ctx context.Context, arg ListAllClarificationsBySiteParams) ([]Clarification, error) {
	rows, err := q.db.QueryContext(ctx, listAllClarificationsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clarification{}
	for rows.Next() {
		var i Clarification
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.RequestedBy,
			&i.Question,
			&i.Context,
			&i.OptionsJson,
			&i.Status,
			&i.ResolutionOption,
			&i.ResolutionText,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingClarificationsByAgent = `-- name: ListPendingClarificationsByAgent :many
SELECT id, site_id, requested_by, question, context, options_json, status, resolution_option, resolution_text, resolved_by, created_at, resolved_at FROM clarifications WHERE site_id = ? AND requested_by = ? AND status = 'pending' ORDER BY created_at DESC LIMIT ?
`

type ListPendingClarificationsByAgentParams struct {
	SiteID      string `json:"site_id"`
	RequestedBy string `json:"requested_by"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListPendingClarificationsByAgent(ctx context.Context, arg ListPendingClarificationsByAgentParams) ([]Clarification, error) {
	rows, err := q.db.QueryContext(ctx, listPendingClarificationsByAgent, arg.SiteID, arg.RequestedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clarification{}
	for rows.Next() {
		var i Clarification
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.RequestedBy,
			&i.Question,
			&i.Context,
			&i.OptionsJson,
			&i.Status,
			&i.ResolutionOption,
			&i.ResolutionText,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingClarificationsBySite = `-- name: ListPendingClarificationsBySite :many
SELECT id, site_id, requested_by, question, context, options_json, status, resolution_option, resolution_text, resolved_by, created_at, resolved_at FROM clarifications WHERE site_id = ? AND status = 'pending' ORDER BY created_at DESC LIMIT ?
`

type ListPendingClarificationsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListPendingClarificationsBySite(ctx context.Context, arg ListPendingClarificationsBySiteParams) ([]Clarification, error) {
	rows, err := q.db.QueryContext(ctx, listPendingClarificationsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clarification{}
	for rows.Next() {
		var i Clarification
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.RequestedBy,
			&i.Question,
			&i.Context,
			&i.OptionsJson,
			&i.Status,
			&i.ResolutionOption,
			&i.ResolutionText,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveClarification = `-- name: ResolveClarification :exec
UPDATE clarifications
SET status = 'resolved',
    resolution_option = ?,
    resolution_text = ?,
    resolved_by = ?,
    resolved_at = datetime('now')
WHERE id = ? AND site_id = ? AND status = 'pending'
`

type ResolveClarificationParams struct {
	ResolutionOption int64  `json:"resolution_option"`
	ResolutionText   string `json:"resolution_text"`
	ResolvedBy       string `json:"resolved_by"`
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
}

func (q *Queries) ResolveClarification(ctx context.Context, arg ResolveClarificationParams) error {
	_, err := q.db.ExecContext(ctx, resolveClarification,
		arg.ResolutionOption,
		arg.ResolutionText,
		arg.ResolvedBy,
		arg.ID,
		arg.SiteID,
	)
	return err
}
