// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package store

import (
	"context"
)

const countItemsByCollection = `-- name: CountItemsByCollection :one
SELECT COUNT(*) AS total FROM collection_items WHERE collection_id = ?
`

func (q *Queries) CountItemsByCollection(ctx context.Context, collectionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByCollection, collectionID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCollection = `-- name: CreateCollection :exec
INSERT INTO collections (id, site_id, name, slug, schema_json, settings_json, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCollectionParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	SchemaJson   string `json:"schema_json"`
	SettingsJson string `json:"settings_json"`
	SortOrder    int64  `json:"sort_order"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.Slug,
		arg.SchemaJson,
		arg.SettingsJson,
		arg.SortOrder,
	)
	return err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO collection_items
    (id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID           string `json:"id"`
	CollectionID string `json:"collection_id"`
	SiteID       string `json:"site_id"`
	Slug         string `json:"slug"`
	Title        string `json:"title"`
	DataJson     string `json:"data_json"`
	Locale       string `json:"locale"`
	Status       string `json:"status"`
	PublishedAt  string `json:"published_at"`
	SortOrder    int64  `json:"sort_order"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.CollectionID,
		arg.SiteID,
		arg.Slug,
		arg.Title,
		arg.DataJson,
		arg.Locale,
		arg.Status,
		arg.PublishedAt,
		arg.SortOrder,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM collection_items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, site_id, name, slug, schema_json, settings_json, sort_order, created_at, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollectionByID(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.SchemaJson,
		&i.SettingsJson,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySiteAndSlug = `-- name: GetCollectionBySiteAndSlug :one
SELECT id, site_id, name, slug, schema_json, settings_json, sort_order, created_at, updated_at FROM collections WHERE site_id = ? AND slug = ?
`

type GetCollectionBySiteAndSlugParams struct {
	SiteID string `json:"site_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetCollectionBySiteAndSlug(ctx context.Context, arg GetCollectionBySiteAndSlugParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionBySiteAndSlug, arg.SiteID, arg.Slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.SchemaJson,
		&i.SettingsJson,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByCollectionLocaleSlug = `-- name: GetItemByCollectionLocaleSlug :one
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items
WHERE collection_id = ? AND locale = ? AND slug = ?
`

type GetItemByCollectionLocaleSlugParams struct {
	CollectionID string `json:"collection_id"`
	Locale       string `json:"locale"`
	Slug         string `json:"slug"`
}

func (q *Queries) GetItemByCollectionLocaleSlug(ctx context.Context, arg GetItemByCollectionLocaleSlugParams) (CollectionItem, error) {
	row := q.db.QueryRowContext(ctx, getItemByCollectionLocaleSlug, arg.CollectionID, arg.Locale, arg.Slug)
	var i CollectionItem
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.SiteID,
		&i.Slug,
		&i.Title,
		&i.DataJson,
		&i.Locale,
		&i.Status,
		&i.PublishedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items WHERE id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (CollectionItem, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i CollectionItem
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.SiteID,
		&i.Slug,
		&i.Title,
		&i.DataJson,
		&i.Locale,
		&i.Status,
		&i.PublishedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPublishedItemsBySite = `-- name: ListAllPublishedItemsBySite :many
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items
WHERE site_id = ? AND status = 'published'
ORDER BY collection_id, sort_order, published_at DESC, created_at DESC
`

func (q *Queries) ListAllPublishedItemsBySite(ctx context.Context, siteID string) ([]CollectionItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllPublishedItemsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionItem{}
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.SiteID,
			&i.Slug,
			&i.Title,
			&i.DataJson,
			&i.Locale,
			&i.Status,
			&i.PublishedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsBySite = `-- name: ListCollectionsBySite :many
SELECT id, site_id, name, slug, schema_json, settings_json, sort_order, created_at, updated_at FROM collections WHERE site_id = ? ORDER BY sort_order, name
`

func (q *Queries) ListCollectionsBySite(ctx context.Context, siteID string) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.SchemaJson,
			&i.SettingsJson,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCollection = `-- name: ListItemsByCollection :many
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items
WHERE collection_id = ?
ORDER BY sort_order, published_at DESC, created_at DESC
`

func (q *Queries) ListItemsByCollection(ctx context.Context, collectionID string) ([]CollectionItem, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionItem{}
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.SiteID,
			&i.Slug,
			&i.Title,
			&i.DataJson,
			&i.Locale,
			&i.Status,
			&i.PublishedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalesByCollection = `-- name: ListLocalesByCollection :many
SELECT DISTINCT locale FROM collection_items WHERE collection_id = ? ORDER BY locale
`

func (q *Queries) ListLocalesByCollection(ctx context.Context, collectionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLocalesByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var locale string
		if err := rows.Scan(&locale); err != nil {
			return nil, err
		}
		items = append(items, locale)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedItemsByCollection = `-- name: ListPublishedItemsByCollection :many
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items
WHERE collection_id = ? AND status = 'published'
ORDER BY sort_order, published_at DESC, created_at DESC
`

func (q *Queries) ListPublishedItemsByCollection(ctx context.Context, collectionID string) ([]CollectionItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedItemsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionItem{}
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.SiteID,
			&i.Slug,
			&i.Title,
			&i.DataJson,
			&i.Locale,
			&i.Status,
			&i.PublishedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedItemsByCollectionAndLocale = `-- name: ListPublishedItemsByCollectionAndLocale :many
SELECT id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at FROM collection_items
WHERE collection_id = ? AND status = 'published' AND locale = ?
ORDER BY sort_order, published_at DESC, created_at DESC
`

type ListPublishedItemsByCollectionAndLocaleParams struct {
	CollectionID string `json:"collection_id"`
	Locale       string `json:"locale"`
}

func (q *Queries) ListPublishedItemsByCollectionAndLocale(ctx context.Context, arg ListPublishedItemsByCollectionAndLocaleParams) ([]CollectionItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedItemsByCollectionAndLocale, arg.CollectionID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionItem{}
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.SiteID,
			&i.Slug,
			&i.Title,
			&i.DataJson,
			&i.Locale,
			&i.Status,
			&i.PublishedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections
SET name = ?,
    slug = ?,
    schema_json = ?,
    settings_json = ?,
    sort_order = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateCollectionParams struct {
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	SchemaJson   string `json:"schema_json"`
	SettingsJson string `json:"settings_json"`
	SortOrder    int64  `json:"sort_order"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Slug,
		arg.SchemaJson,
		arg.SettingsJson,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE collection_items
SET slug = ?,
    title = ?,
    data_json = ?,
    locale = ?,
    status = ?,
    published_at = ?,
    sort_order = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateItemParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	DataJson    string `json:"data_json"`
	Locale      string `json:"locale"`
	Status      string `json:"status"`
	PublishedAt string `json:"published_at"`
	SortOrder   int64  `json:"sort_order"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Slug,
		arg.Title,
		arg.DataJson,
		arg.Locale,
		arg.Status,
		arg.PublishedAt,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO collection_items
    (id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(collection_id, locale, slug) DO UPDATE SET
    title        = excluded.title,
    data_json    = excluded.data_json,
    status       = excluded.status,
    published_at = excluded.published_at,
    sort_order   = excluded.sort_order,
    updated_at   = datetime('now')
RETURNING id, collection_id, site_id, slug, title, data_json, locale, status, published_at, sort_order, created_at, updated_at
`

type UpsertItemParams struct {
	ID           string `json:"id"`
	CollectionID string `json:"collection_id"`
	SiteID       string `json:"site_id"`
	Slug         string `json:"slug"`
	Title        string `json:"title"`
	DataJson     string `json:"data_json"`
	Locale       string `json:"locale"`
	Status       string `json:"status"`
	PublishedAt  string `json:"published_at"`
	SortOrder    int64  `json:"sort_order"`
}

// Sprint 4 (2026-05-06): re-import upsert. Conflict on the
// (collection_id, locale, slug) compound natural key.
func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (CollectionItem, error) {
	row := q.db.QueryRowContext(ctx, upsertItem,
		arg.ID,
		arg.CollectionID,
		arg.SiteID,
		arg.Slug,
		arg.Title,
		arg.DataJson,
		arg.Locale,
		arg.Status,
		arg.PublishedAt,
		arg.SortOrder,
	)
	var i CollectionItem
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.SiteID,
		&i.Slug,
		&i.Title,
		&i.DataJson,
		&i.Locale,
		&i.Status,
		&i.PublishedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
