// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: components.sql

package store

import (
	"context"
)

const createComponent = `-- name: CreateComponent :exec
INSERT INTO components (id, site_id, name, category, template, props_schema, css_classes, usage_note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateComponentParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Template    string `json:"template"`
	PropsSchema string `json:"props_schema"`
	CssClasses  string `json:"css_classes"`
	UsageNote   string `json:"usage_note"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) error {
	_, err := q.db.ExecContext(ctx, createComponent,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.Category,
		arg.Template,
		arg.PropsSchema,
		arg.CssClasses,
		arg.UsageNote,
	)
	return err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components WHERE id = ?
`

func (q *Queries) DeleteComponent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComponent, id)
	return err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, site_id, name, category, template, props_schema, css_classes, usage_note, created_at, updated_at FROM components WHERE id = ?
`

func (q *Queries) GetComponentByID(ctx context.Context, id string) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Category,
		&i.Template,
		&i.PropsSchema,
		&i.CssClasses,
		&i.UsageNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComponentByName = `-- name: GetComponentByName :one
SELECT id, site_id, name, category, template, props_schema, css_classes, usage_note, created_at, updated_at FROM components WHERE site_id = ? AND name = ?
`

type GetComponentByNameParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetComponentByName(ctx context.Context, arg GetComponentByNameParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponentByName, arg.SiteID, arg.Name)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Category,
		&i.Template,
		&i.PropsSchema,
		&i.CssClasses,
		&i.UsageNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComponentsBySite = `-- name: ListComponentsBySite :many
SELECT id, site_id, name, category, template, props_schema, css_classes, usage_note, created_at, updated_at FROM components WHERE site_id = ? ORDER BY category, name
`

func (q *Queries) ListComponentsBySite(ctx context.Context, siteID string) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listComponentsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Category,
			&i.Template,
			&i.PropsSchema,
			&i.CssClasses,
			&i.UsageNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComponent = `-- name: UpdateComponent :exec
UPDATE components
SET name = ?, category = ?, template = ?, props_schema = ?, css_classes = ?, usage_note = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateComponentParams struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	Template    string `json:"template"`
	PropsSchema string `json:"props_schema"`
	CssClasses  string `json:"css_classes"`
	UsageNote   string `json:"usage_note"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) error {
	_, err := q.db.ExecContext(ctx, updateComponent,
		arg.Name,
		arg.Category,
		arg.Template,
		arg.PropsSchema,
		arg.CssClasses,
		arg.UsageNote,
		arg.ID,
	)
	return err
}
