// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversions.sql

package store

import (
	"context"
)

const countConversionsByGoal = `-- name: CountConversionsByGoal :one
SELECT COUNT(*) AS count FROM conversion_events
WHERE goal_id = ? AND ts >= ?
`

type CountConversionsByGoalParams struct {
	GoalID string `json:"goal_id"`
	Ts     string `json:"ts"`
}

func (q *Queries) CountConversionsByGoal(ctx context.Context, arg CountConversionsByGoalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversionsByGoal, arg.GoalID, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueConvertersByGoal = `-- name: CountUniqueConvertersByGoal :one
SELECT COUNT(DISTINCT fingerprint) AS count FROM conversion_events
WHERE goal_id = ? AND ts >= ?
`

type CountUniqueConvertersByGoalParams struct {
	GoalID string `json:"goal_id"`
	Ts     string `json:"ts"`
}

func (q *Queries) CountUniqueConvertersByGoal(ctx context.Context, arg CountUniqueConvertersByGoalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUniqueConvertersByGoal, arg.GoalID, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :exec
INSERT INTO conversion_goals (
    id, site_id, slug, name, match_type, match_value,
    value_cents, value_currency, active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGoalParams struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	MatchType     string `json:"match_type"`
	MatchValue    string `json:"match_value"`
	ValueCents    int64  `json:"value_cents"`
	ValueCurrency string `json:"value_currency"`
	Active        int64  `json:"active"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) error {
	_, err := q.db.ExecContext(ctx, createGoal,
		arg.ID,
		arg.SiteID,
		arg.Slug,
		arg.Name,
		arg.MatchType,
		arg.MatchValue,
		arg.ValueCents,
		arg.ValueCurrency,
		arg.Active,
	)
	return err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM conversion_goals WHERE id = ?
`

func (q *Queries) DeleteGoal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, id)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, site_id, slug, name, match_type, match_value, value_cents, value_currency, active, created_at, updated_at FROM conversion_goals
WHERE id = ?
`

func (q *Queries) GetGoalByID(ctx context.Context, id string) (ConversionGoal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByID, id)
	var i ConversionGoal
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Slug,
		&i.Name,
		&i.MatchType,
		&i.MatchValue,
		&i.ValueCents,
		&i.ValueCurrency,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalBySiteSlug = `-- name: GetGoalBySiteSlug :one
SELECT id, site_id, slug, name, match_type, match_value, value_cents, value_currency, active, created_at, updated_at FROM conversion_goals
WHERE site_id = ? AND slug = ?
`

type GetGoalBySiteSlugParams struct {
	SiteID string `json:"site_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetGoalBySiteSlug(ctx context.Context, arg GetGoalBySiteSlugParams) (ConversionGoal, error) {
	row := q.db.QueryRowContext(ctx, getGoalBySiteSlug, arg.SiteID, arg.Slug)
	var i ConversionGoal
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Slug,
		&i.Name,
		&i.MatchType,
		&i.MatchValue,
		&i.ValueCents,
		&i.ValueCurrency,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGoalsBySite = `-- name: ListActiveGoalsBySite :many

SELECT id, site_id, slug, name, match_type, match_value, value_cents, value_currency, active, created_at, updated_at FROM conversion_goals
WHERE site_id = ? AND active = 1
ORDER BY created_at DESC
`

// Conversion goals + events (Phase 31.1, 2026-05-06).
// The CRUD surface for goals plus the ingest + read queries for events.
// Aggregations stay simple here; richer attribution windows live behind
// the analytics handlers which compose these into per-range views.
func (q *Queries) ListActiveGoalsBySite(ctx context.Context, siteID string) ([]ConversionGoal, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGoalsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionGoal{}
	for rows.Next() {
		var i ConversionGoal
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Slug,
			&i.Name,
			&i.MatchType,
			&i.MatchValue,
			&i.ValueCents,
			&i.ValueCurrency,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGoalsBySite = `-- name: ListAllGoalsBySite :many
SELECT id, site_id, slug, name, match_type, match_value, value_cents, value_currency, active, created_at, updated_at FROM conversion_goals
WHERE site_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAllGoalsBySite(ctx context.Context, siteID string) ([]ConversionGoal, error) {
	rows, err := q.db.QueryContext(ctx, listAllGoalsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionGoal{}
	for rows.Next() {
		var i ConversionGoal
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Slug,
			&i.Name,
			&i.MatchType,
			&i.MatchValue,
			&i.ValueCents,
			&i.ValueCurrency,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversionsByGoal = `-- name: ListConversionsByGoal :many
SELECT id, site_id, goal_id, fingerprint, session_id, path, ts, value_cents, value_currency, properties_json FROM conversion_events
WHERE goal_id = ? AND ts >= ?
ORDER BY ts DESC
LIMIT ?
`

type ListConversionsByGoalParams struct {
	GoalID string `json:"goal_id"`
	Ts     string `json:"ts"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListConversionsByGoal(ctx context.Context, arg ListConversionsByGoalParams) ([]ConversionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listConversionsByGoal, arg.GoalID, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionEvent{}
	for rows.Next() {
		var i ConversionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.GoalID,
			&i.Fingerprint,
			&i.SessionID,
			&i.Path,
			&i.Ts,
			&i.ValueCents,
			&i.ValueCurrency,
			&i.PropertiesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversionsBySite = `-- name: ListConversionsBySite :many
SELECT id, site_id, goal_id, fingerprint, session_id, path, ts, value_cents, value_currency, properties_json FROM conversion_events
WHERE site_id = ? AND ts >= ?
ORDER BY ts DESC
LIMIT ?
`

type ListConversionsBySiteParams struct {
	SiteID string `json:"site_id"`
	Ts     string `json:"ts"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListConversionsBySite(ctx context.Context, arg ListConversionsBySiteParams) ([]ConversionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listConversionsBySite, arg.SiteID, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionEvent{}
	for rows.Next() {
		var i ConversionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.GoalID,
			&i.Fingerprint,
			&i.SessionID,
			&i.Path,
			&i.Ts,
			&i.ValueCents,
			&i.ValueCurrency,
			&i.PropertiesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversionsBySiteFingerprint = `-- name: ListConversionsBySiteFingerprint :many
SELECT id, site_id, goal_id, fingerprint, session_id, path, ts, value_cents, value_currency, properties_json FROM conversion_events
WHERE site_id = ? AND fingerprint = ?
ORDER BY ts DESC
LIMIT ?
`

type ListConversionsBySiteFingerprintParams struct {
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListConversionsBySiteFingerprint(ctx context.Context, arg ListConversionsBySiteFingerprintParams) ([]ConversionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listConversionsBySiteFingerprint, arg.SiteID, arg.Fingerprint, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionEvent{}
	for rows.Next() {
		var i ConversionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.GoalID,
			&i.Fingerprint,
			&i.SessionID,
			&i.Path,
			&i.Ts,
			&i.ValueCents,
			&i.ValueCurrency,
			&i.PropertiesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordConversionEvent = `-- name: RecordConversionEvent :exec
INSERT INTO conversion_events (
    id, site_id, goal_id, fingerprint, session_id, path, ts,
    value_cents, value_currency, properties_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordConversionEventParams struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	GoalID         string `json:"goal_id"`
	Fingerprint    string `json:"fingerprint"`
	SessionID      string `json:"session_id"`
	Path           string `json:"path"`
	Ts             string `json:"ts"`
	ValueCents     int64  `json:"value_cents"`
	ValueCurrency  string `json:"value_currency"`
	PropertiesJson string `json:"properties_json"`
}

func (q *Queries) RecordConversionEvent(ctx context.Context, arg RecordConversionEventParams) error {
	_, err := q.db.ExecContext(ctx, recordConversionEvent,
		arg.ID,
		arg.SiteID,
		arg.GoalID,
		arg.Fingerprint,
		arg.SessionID,
		arg.Path,
		arg.Ts,
		arg.ValueCents,
		arg.ValueCurrency,
		arg.PropertiesJson,
	)
	return err
}

const sumValueByGoal = `-- name: SumValueByGoal :one
SELECT COALESCE(SUM(value_cents), 0) AS total_cents FROM conversion_events
WHERE goal_id = ? AND ts >= ?
`

type SumValueByGoalParams struct {
	GoalID string `json:"goal_id"`
	Ts     string `json:"ts"`
}

func (q *Queries) SumValueByGoal(ctx context.Context, arg SumValueByGoalParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumValueByGoal, arg.GoalID, arg.Ts)
	var total_cents interface{}
	err := row.Scan(&total_cents)
	return total_cents, err
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE conversion_goals
SET name = ?,
    match_type = ?,
    match_value = ?,
    value_cents = ?,
    value_currency = ?,
    active = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateGoalParams struct {
	Name          string `json:"name"`
	MatchType     string `json:"match_type"`
	MatchValue    string `json:"match_value"`
	ValueCents    int64  `json:"value_cents"`
	ValueCurrency string `json:"value_currency"`
	Active        int64  `json:"active"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateGoal,
		arg.Name,
		arg.MatchType,
		arg.MatchValue,
		arg.ValueCents,
		arg.ValueCurrency,
		arg.Active,
		arg.ID,
	)
	return err
}
