// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crm_outbox.sql

package store

import (
	"context"
)

const countPendingCRMOutbox = `-- name: CountPendingCRMOutbox :one
SELECT COUNT(*) FROM crm_outbox WHERE status IN ('pending', 'retrying')
`

// For an operator health surface: a growing number here means the CRM has been
// unreachable and identifications are queued, which is exactly the state that
// used to be invisible.
func (q *Queries) CountPendingCRMOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingCRMOutbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCRMOutboxBySiteOlderThan = `-- name: DeleteCRMOutboxBySiteOlderThan :execrows
DELETE FROM crm_outbox
WHERE site_id = ? AND created_at < ? AND status IN ('succeeded', 'dropped')
`

type DeleteCRMOutboxBySiteOlderThanParams struct {
	SiteID    string `json:"site_id"`
	CreatedAt string `json:"created_at"`
}

// Retention sweep. payload_json carries the identified visitor's email, so this
// table holds PII and must not outlive the window.
func (q *Queries) DeleteCRMOutboxBySiteOlderThan(ctx context.Context, arg DeleteCRMOutboxBySiteOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCRMOutboxBySiteOlderThan, arg.SiteID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueCRMOutbox = `-- name: EnqueueCRMOutbox :exec
INSERT INTO crm_outbox (id, site_id, event_type, payload_json)
VALUES (?, ?, ?, ?)
`

type EnqueueCRMOutboxParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	EventType   string `json:"event_type"`
	PayloadJson string `json:"payload_json"`
}

// Records the obligation to tell BrightCRM about an identified visitor. Called
// in the same tx as the visit_sessions write, so the local claim and the
// outbound obligation cannot diverge.
func (q *Queries) EnqueueCRMOutbox(ctx context.Context, arg EnqueueCRMOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueCRMOutbox,
		arg.ID,
		arg.SiteID,
		arg.EventType,
		arg.PayloadJson,
	)
	return err
}

const listDueCRMOutbox = `-- name: ListDueCRMOutbox :many
SELECT id, site_id, event_type, payload_json, status, attempts, next_attempt_at, last_error, created_at, completed_at
FROM crm_outbox
WHERE status IN ('pending', 'retrying') AND next_attempt_at <= datetime('now')
ORDER BY created_at
LIMIT ?
`

// Drain feed: pending or retrying rows whose backoff has elapsed.
func (q *Queries) ListDueCRMOutbox(ctx context.Context, limit int64) ([]CrmOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listDueCRMOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrmOutbox{}
	for rows.Next() {
		var i CrmOutbox
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.EventType,
			&i.PayloadJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCRMOutboxDropped = `-- name: MarkCRMOutboxDropped :exec
UPDATE crm_outbox
SET status = 'dropped', attempts = attempts + 1, completed_at = datetime('now'), last_error = ?
WHERE id = ?
`

type MarkCRMOutboxDroppedParams struct {
	LastError string `json:"last_error"`
	ID        string `json:"id"`
}

// Terminal. Kept rather than deleted so an operator can see WHAT was lost;
// the retention sweep purges it later.
func (q *Queries) MarkCRMOutboxDropped(ctx context.Context, arg MarkCRMOutboxDroppedParams) error {
	_, err := q.db.ExecContext(ctx, markCRMOutboxDropped, arg.LastError, arg.ID)
	return err
}

const markCRMOutboxRetrying = `-- name: MarkCRMOutboxRetrying :exec
UPDATE crm_outbox
SET status = 'retrying', attempts = attempts + 1, next_attempt_at = ?, last_error = ?
WHERE id = ?
`

type MarkCRMOutboxRetryingParams struct {
	NextAttemptAt string `json:"next_attempt_at"`
	LastError     string `json:"last_error"`
	ID            string `json:"id"`
}

// attempts is incremented here rather than by the caller so a crash between
// the send and the bookkeeping cannot lose the count and loop forever.
func (q *Queries) MarkCRMOutboxRetrying(ctx context.Context, arg MarkCRMOutboxRetryingParams) error {
	_, err := q.db.ExecContext(ctx, markCRMOutboxRetrying, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markCRMOutboxSucceeded = `-- name: MarkCRMOutboxSucceeded :exec
UPDATE crm_outbox
SET status = 'succeeded', completed_at = datetime('now'), last_error = ''
WHERE id = ?
`

func (q *Queries) MarkCRMOutboxSucceeded(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markCRMOutboxSucceeded, id)
	return err
}
