// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cwv_events.sql

package store

import (
	"context"
)

const countCWVForSite = `-- name: CountCWVForSite :one
SELECT COUNT(*) FROM cwv_events WHERE site_id = ?
`

func (q *Queries) CountCWVForSite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCWVForSite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCWVBySiteOlderThan = `-- name: DeleteCWVBySiteOlderThan :execrows
DELETE FROM cwv_events
WHERE site_id = ? AND created_at < ?
`

type DeleteCWVBySiteOlderThanParams struct {
	SiteID    string `json:"site_id"`
	CreatedAt string `json:"created_at"`
}

// Per-site retention sweep. The retention manager passes an ISO
// timestamp cutoff and gets back the number of rows deleted so the
// sweep result struct can report per-table totals.
func (q *Queries) DeleteCWVBySiteOlderThan(ctx context.Context, arg DeleteCWVBySiteOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCWVBySiteOlderThan, arg.SiteID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCWVEvent = `-- name: InsertCWVEvent :exec
INSERT INTO cwv_events (id, site_id, page_path, metric, value, rating, device)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertCWVEventParams struct {
	ID       string  `json:"id"`
	SiteID   string  `json:"site_id"`
	PagePath string  `json:"page_path"`
	Metric   string  `json:"metric"`
	Value    float64 `json:"value"`
	Rating   string  `json:"rating"`
	Device   string  `json:"device"`
}

func (q *Queries) InsertCWVEvent(ctx context.Context, arg InsertCWVEventParams) error {
	_, err := q.db.ExecContext(ctx, insertCWVEvent,
		arg.ID,
		arg.SiteID,
		arg.PagePath,
		arg.Metric,
		arg.Value,
		arg.Rating,
		arg.Device,
	)
	return err
}

const listCWVValuesForWindow = `-- name: ListCWVValuesForWindow :many
SELECT value, rating, page_path, created_at
FROM cwv_events
WHERE site_id = ?
  AND metric = ?
  AND (device = ? OR ? = '')
  AND created_at >= datetime('now', ?)
ORDER BY value ASC
`

type ListCWVValuesForWindowParams struct {
	SiteID   string      `json:"site_id"`
	Metric   string      `json:"metric"`
	Device   string      `json:"device"`
	Column4  interface{} `json:"column_4"`
	Datetime interface{} `json:"datetime"`
}

type ListCWVValuesForWindowRow struct {
	Value     float64 `json:"value"`
	Rating    string  `json:"rating"`
	PagePath  string  `json:"page_path"`
	CreatedAt string  `json:"created_at"`
}

// Returns every value for one (site, metric, device) over the last
// N days. The dashboard handler computes p75 in Go (SQLite has no
// native percentile). N is passed via datetime('now', ?); the
// callsite formats e.g. '-7 days'.
func (q *Queries) ListCWVValuesForWindow(ctx context.Context, arg ListCWVValuesForWindowParams) ([]ListCWVValuesForWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listCWVValuesForWindow,
		arg.SiteID,
		arg.Metric,
		arg.Device,
		arg.Column4,
		arg.Datetime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCWVValuesForWindowRow{}
	for rows.Next() {
		var i ListCWVValuesForWindowRow
		if err := rows.Scan(
			&i.Value,
			&i.Rating,
			&i.PagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
