// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package store

import (
	"context"
)

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (id, site_id, status, deploy_target, deploy_config, created_at)
VALUES (?, ?, 'pending', ?, ?, datetime('now'))
`

type CreateDeploymentParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	DeployTarget string `json:"deploy_target"`
	DeployConfig string `json:"deploy_config"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.ID,
		arg.SiteID,
		arg.DeployTarget,
		arg.DeployConfig,
	)
	return err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, site_id, status, build_log, deploy_target, deploy_config, pages_built, duration_ms, error, target_id, deploy_url, deployed_at, created_at, completed_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.BuildLog,
		&i.DeployTarget,
		&i.DeployConfig,
		&i.PagesBuilt,
		&i.DurationMs,
		&i.Error,
		&i.TargetID,
		&i.DeployUrl,
		&i.DeployedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeploymentsBySite = `-- name: ListDeploymentsBySite :many
SELECT id, site_id, status, build_log, deploy_target, deploy_config, pages_built, duration_ms, error, target_id, deploy_url, deployed_at, created_at, completed_at FROM deployments WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsBySite(ctx context.Context, siteID string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.BuildLog,
			&i.DeployTarget,
			&i.DeployConfig,
			&i.PagesBuilt,
			&i.DurationMs,
			&i.Error,
			&i.TargetID,
			&i.DeployUrl,
			&i.DeployedAt,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploymentsBySite = `-- name: ListRecentDeploymentsBySite :many
SELECT id, site_id, status, build_log, deploy_target, deploy_config, pages_built, duration_ms, error, target_id, deploy_url, deployed_at, created_at, completed_at FROM deployments WHERE site_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListRecentDeploymentsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListRecentDeploymentsBySite(ctx context.Context, arg ListRecentDeploymentsBySiteParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeploymentsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.BuildLog,
			&i.DeployTarget,
			&i.DeployConfig,
			&i.PagesBuilt,
			&i.DurationMs,
			&i.Error,
			&i.TargetID,
			&i.DeployUrl,
			&i.DeployedAt,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentDeployed = `-- name: UpdateDeploymentDeployed :exec
UPDATE deployments
SET target_id = ?, deploy_url = ?, deployed_at = datetime('now')
WHERE id = ?
`

type UpdateDeploymentDeployedParams struct {
	TargetID  string `json:"target_id"`
	DeployUrl string `json:"deploy_url"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDeploymentDeployed(ctx context.Context, arg UpdateDeploymentDeployedParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentDeployed, arg.TargetID, arg.DeployUrl, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?, build_log = ?, pages_built = ?, duration_ms = ?, error = ?, completed_at = datetime('now')
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status     string `json:"status"`
	BuildLog   string `json:"build_log"`
	PagesBuilt int64  `json:"pages_built"`
	DurationMs int64  `json:"duration_ms"`
	Error      string `json:"error"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.BuildLog,
		arg.PagesBuilt,
		arg.DurationMs,
		arg.Error,
		arg.ID,
	)
	return err
}
