// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploy_targets.sql

package store

import (
	"context"
)

const clearDefaultDeployTargets = `-- name: ClearDefaultDeployTargets :exec
UPDATE deploy_targets SET is_default = 0, updated_at = datetime('now')
WHERE site_id = ?
`

func (q *Queries) ClearDefaultDeployTargets(ctx context.Context, siteID string) error {
	_, err := q.db.ExecContext(ctx, clearDefaultDeployTargets, siteID)
	return err
}

const createDeployTarget = `-- name: CreateDeployTarget :exec
INSERT INTO deploy_targets (id, site_id, name, kind, config_json, is_default)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDeployTargetParams struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	ConfigJson string `json:"config_json"`
	IsDefault  int64  `json:"is_default"`
}

func (q *Queries) CreateDeployTarget(ctx context.Context, arg CreateDeployTargetParams) error {
	_, err := q.db.ExecContext(ctx, createDeployTarget,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.Kind,
		arg.ConfigJson,
		arg.IsDefault,
	)
	return err
}

const deleteDeployTarget = `-- name: DeleteDeployTarget :exec
DELETE FROM deploy_targets WHERE id = ?
`

func (q *Queries) DeleteDeployTarget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployTarget, id)
	return err
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT id, site_id, name, kind, config_json, is_default, created_at, updated_at FROM deploy_targets WHERE id = ?
`

func (q *Queries) GetDeployTarget(ctx context.Context, id string) (DeployTarget, error) {
	row := q.db.QueryRowContext(ctx, getDeployTarget, id)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Kind,
		&i.ConfigJson,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeployTargetsBySite = `-- name: ListDeployTargetsBySite :many
SELECT id, site_id, name, kind, config_json, is_default, created_at, updated_at FROM deploy_targets WHERE site_id = ? ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListDeployTargetsBySite(ctx context.Context, siteID string) ([]DeployTarget, error) {
	rows, err := q.db.QueryContext(ctx, listDeployTargetsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTarget{}
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Kind,
			&i.ConfigJson,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeployTargetDefault = `-- name: SetDeployTargetDefault :exec
UPDATE deploy_targets SET is_default = 1, updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) SetDeployTargetDefault(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setDeployTargetDefault, id)
	return err
}

const updateDeployTarget = `-- name: UpdateDeployTarget :exec
UPDATE deploy_targets SET
    name = ?,
    kind = ?,
    config_json = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateDeployTargetParams struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	ConfigJson string `json:"config_json"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployTarget,
		arg.Name,
		arg.Kind,
		arg.ConfigJson,
		arg.ID,
	)
	return err
}
