// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: design_references.sql

package store

import (
	"context"
)

const createDesignReference = `-- name: CreateDesignReference :exec
INSERT INTO design_references (id, site_id, url, label, ref_type, fetched_json, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDesignReferenceParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Url         string `json:"url"`
	Label       string `json:"label"`
	RefType     string `json:"ref_type"`
	FetchedJson string `json:"fetched_json"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) CreateDesignReference(ctx context.Context, arg CreateDesignReferenceParams) error {
	_, err := q.db.ExecContext(ctx, createDesignReference,
		arg.ID,
		arg.SiteID,
		arg.Url,
		arg.Label,
		arg.RefType,
		arg.FetchedJson,
		arg.FetchedAt,
	)
	return err
}

const deleteDesignReference = `-- name: DeleteDesignReference :exec
DELETE FROM design_references WHERE id = ? AND site_id = ?
`

type DeleteDesignReferenceParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) DeleteDesignReference(ctx context.Context, arg DeleteDesignReferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDesignReference, arg.ID, arg.SiteID)
	return err
}

const getDesignReference = `-- name: GetDesignReference :one
SELECT id, site_id, url, label, ref_type, fetched_json, fetched_at, created_at FROM design_references
WHERE id = ? AND site_id = ?
`

type GetDesignReferenceParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) GetDesignReference(ctx context.Context, arg GetDesignReferenceParams) (DesignReference, error) {
	row := q.db.QueryRowContext(ctx, getDesignReference, arg.ID, arg.SiteID)
	var i DesignReference
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Url,
		&i.Label,
		&i.RefType,
		&i.FetchedJson,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDesignReferences = `-- name: ListDesignReferences :many
SELECT id, site_id, url, label, ref_type, fetched_json, fetched_at, created_at FROM design_references
WHERE site_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDesignReferences(ctx context.Context, siteID string) ([]DesignReference, error) {
	rows, err := q.db.QueryContext(ctx, listDesignReferences, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DesignReference{}
	for rows.Next() {
		var i DesignReference
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Url,
			&i.Label,
			&i.RefType,
			&i.FetchedJson,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesignReferenceFetched = `-- name: UpdateDesignReferenceFetched :exec
UPDATE design_references SET
    fetched_json = ?,
    fetched_at = ?
WHERE id = ? AND site_id = ?
`

type UpdateDesignReferenceFetchedParams struct {
	FetchedJson string `json:"fetched_json"`
	FetchedAt   string `json:"fetched_at"`
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
}

func (q *Queries) UpdateDesignReferenceFetched(ctx context.Context, arg UpdateDesignReferenceFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateDesignReferenceFetched,
		arg.FetchedJson,
		arg.FetchedAt,
		arg.ID,
		arg.SiteID,
	)
	return err
}
