// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount_codes.sql

package store

import (
	"context"
)

const createDiscountCode = `-- name: CreateDiscountCode :exec
INSERT INTO discount_codes (id, site_id, code, kind, value, min_subtotal_cents, max_uses, starts_at, ends_at, applies_to, applies_to_ids_json, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDiscountCodeParams struct {
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
	Code             string `json:"code"`
	Kind             string `json:"kind"`
	Value            int64  `json:"value"`
	MinSubtotalCents int64  `json:"min_subtotal_cents"`
	MaxUses          int64  `json:"max_uses"`
	StartsAt         string `json:"starts_at"`
	EndsAt           string `json:"ends_at"`
	AppliesTo        string `json:"applies_to"`
	AppliesToIdsJson string `json:"applies_to_ids_json"`
	IsActive         int64  `json:"is_active"`
}

func (q *Queries) CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) error {
	_, err := q.db.ExecContext(ctx, createDiscountCode,
		arg.ID,
		arg.SiteID,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.MinSubtotalCents,
		arg.MaxUses,
		arg.StartsAt,
		arg.EndsAt,
		arg.AppliesTo,
		arg.AppliesToIdsJson,
		arg.IsActive,
	)
	return err
}

const deleteDiscountCode = `-- name: DeleteDiscountCode :exec
DELETE FROM discount_codes WHERE id = ? AND site_id = ?
`

type DeleteDiscountCodeParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) DeleteDiscountCode(ctx context.Context, arg DeleteDiscountCodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteDiscountCode, arg.ID, arg.SiteID)
	return err
}

const getDiscountCodeByCode = `-- name: GetDiscountCodeByCode :one
SELECT id, site_id, code, kind, value, min_subtotal_cents, max_uses, used_count, starts_at, ends_at, applies_to, applies_to_ids_json, is_active, created_at, updated_at FROM discount_codes WHERE site_id = ? AND code = ?
`

type GetDiscountCodeByCodeParams struct {
	SiteID string `json:"site_id"`
	Code   string `json:"code"`
}

func (q *Queries) GetDiscountCodeByCode(ctx context.Context, arg GetDiscountCodeByCodeParams) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByCode, arg.SiteID, arg.Code)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.MinSubtotalCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.AppliesTo,
		&i.AppliesToIdsJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscountCodeByID = `-- name: GetDiscountCodeByID :one
SELECT id, site_id, code, kind, value, min_subtotal_cents, max_uses, used_count, starts_at, ends_at, applies_to, applies_to_ids_json, is_active, created_at, updated_at FROM discount_codes WHERE id = ? AND site_id = ?
`

type GetDiscountCodeByIDParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) GetDiscountCodeByID(ctx context.Context, arg GetDiscountCodeByIDParams) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByID, arg.ID, arg.SiteID)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.MinSubtotalCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.AppliesTo,
		&i.AppliesToIdsJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDiscountCodeUsedCount = `-- name: IncrementDiscountCodeUsedCount :exec
UPDATE discount_codes
SET used_count = used_count + 1,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type IncrementDiscountCodeUsedCountParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) IncrementDiscountCodeUsedCount(ctx context.Context, arg IncrementDiscountCodeUsedCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementDiscountCodeUsedCount, arg.ID, arg.SiteID)
	return err
}

const listDiscountCodesBySite = `-- name: ListDiscountCodesBySite :many
SELECT id, site_id, code, kind, value, min_subtotal_cents, max_uses, used_count, starts_at, ends_at, applies_to, applies_to_ids_json, is_active, created_at, updated_at FROM discount_codes
WHERE site_id = ?
ORDER BY is_active DESC, created_at DESC
LIMIT ?
`

type ListDiscountCodesBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListDiscountCodesBySite(ctx context.Context, arg ListDiscountCodesBySiteParams) ([]DiscountCode, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountCodesBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscountCode{}
	for rows.Next() {
		var i DiscountCode
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Code,
			&i.Kind,
			&i.Value,
			&i.MinSubtotalCents,
			&i.MaxUses,
			&i.UsedCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.AppliesTo,
			&i.AppliesToIdsJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscountCode = `-- name: UpdateDiscountCode :exec
UPDATE discount_codes
SET code = ?,
    kind = ?,
    value = ?,
    min_subtotal_cents = ?,
    max_uses = ?,
    starts_at = ?,
    ends_at = ?,
    applies_to = ?,
    applies_to_ids_json = ?,
    is_active = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateDiscountCodeParams struct {
	Code             string `json:"code"`
	Kind             string `json:"kind"`
	Value            int64  `json:"value"`
	MinSubtotalCents int64  `json:"min_subtotal_cents"`
	MaxUses          int64  `json:"max_uses"`
	StartsAt         string `json:"starts_at"`
	EndsAt           string `json:"ends_at"`
	AppliesTo        string `json:"applies_to"`
	AppliesToIdsJson string `json:"applies_to_ids_json"`
	IsActive         int64  `json:"is_active"`
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
}

func (q *Queries) UpdateDiscountCode(ctx context.Context, arg UpdateDiscountCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateDiscountCode,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.MinSubtotalCents,
		arg.MaxUses,
		arg.StartsAt,
		arg.EndsAt,
		arg.AppliesTo,
		arg.AppliesToIdsJson,
		arg.IsActive,
		arg.ID,
		arg.SiteID,
	)
	return err
}
