// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_revisions.sql

package store

import (
	"context"
)

const countEntityRevisions = `-- name: CountEntityRevisions :one
SELECT CAST(COUNT(*) AS INTEGER) FROM entity_revisions
WHERE site_id = ? AND entity_type = ? AND entity_id = ?
`

type CountEntityRevisionsParams struct {
	SiteID     string `json:"site_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) CountEntityRevisions(ctx context.Context, arg CountEntityRevisionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntityRevisions, arg.SiteID, arg.EntityType, arg.EntityID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEntityRevision = `-- name: CreateEntityRevision :one
INSERT INTO entity_revisions (id, site_id, entity_type, entity_id, version_number, snapshot_json, change_summary, created_by, created_at)
VALUES (
    ?1, ?2, ?3, ?4,
    (SELECT COALESCE(MAX(version_number), 0) + 1
       FROM entity_revisions
      WHERE site_id = ?2 AND entity_type = ?3 AND entity_id = ?4),
    ?5, ?6, ?7, datetime('now')
)
RETURNING version_number
`

type CreateEntityRevisionParams struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	EntityType    string `json:"entity_type"`
	EntityID      string `json:"entity_id"`
	SnapshotJson  string `json:"snapshot_json"`
	ChangeSummary string `json:"change_summary"`
	CreatedBy     string `json:"created_by"`
}

// version_number is computed inside the INSERT so read and write are one
// atomic statement under SQLite's writer lock: two concurrent Record
// calls can no longer race SELECT MAX+1 into duplicate versions (which
// broke GetEntityRevisionByVersion :one and therefore restore). The
// unique index idx_entity_revisions_version is the schema backstop.
func (q *Queries) CreateEntityRevision(ctx context.Context, arg CreateEntityRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEntityRevision,
		arg.ID,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.SnapshotJson,
		arg.ChangeSummary,
		arg.CreatedBy,
	)
	var version_number int64
	err := row.Scan(&version_number)
	return version_number, err
}

const getEntityRevisionByVersion = `-- name: GetEntityRevisionByVersion :one
SELECT id, site_id, entity_type, entity_id, version_number, snapshot_json, change_summary, created_by, created_at FROM entity_revisions
WHERE site_id = ? AND entity_type = ? AND entity_id = ? AND version_number = ?
`

type GetEntityRevisionByVersionParams struct {
	SiteID        string `json:"site_id"`
	EntityType    string `json:"entity_type"`
	EntityID      string `json:"entity_id"`
	VersionNumber int64  `json:"version_number"`
}

func (q *Queries) GetEntityRevisionByVersion(ctx context.Context, arg GetEntityRevisionByVersionParams) (EntityRevision, error) {
	row := q.db.QueryRowContext(ctx, getEntityRevisionByVersion,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.VersionNumber,
	)
	var i EntityRevision
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNumber,
		&i.SnapshotJson,
		&i.ChangeSummary,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEntityRevisions = `-- name: ListEntityRevisions :many
SELECT id, site_id, entity_type, entity_id, version_number, snapshot_json, change_summary, created_by, created_at FROM entity_revisions
WHERE site_id = ? AND entity_type = ? AND entity_id = ?
ORDER BY version_number DESC
LIMIT ?
`

type ListEntityRevisionsParams struct {
	SiteID     string `json:"site_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListEntityRevisions(ctx context.Context, arg ListEntityRevisionsParams) ([]EntityRevision, error) {
	rows, err := q.db.QueryContext(ctx, listEntityRevisions,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityRevision{}
	for rows.Next() {
		var i EntityRevision
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.EntityType,
			&i.EntityID,
			&i.VersionNumber,
			&i.SnapshotJson,
			&i.ChangeSummary,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEntityRevisionsOverLimit = `-- name: PruneEntityRevisionsOverLimit :exec
DELETE FROM entity_revisions AS outer_r
WHERE outer_r.site_id = ?1
  AND outer_r.entity_type = ?2
  AND outer_r.entity_id = ?3
  AND outer_r.id NOT IN (
    SELECT inner_r.id FROM entity_revisions AS inner_r
    WHERE inner_r.site_id = ?1
      AND inner_r.entity_type = ?2
      AND inner_r.entity_id = ?3
    ORDER BY inner_r.version_number DESC
    LIMIT ?4
)
`

type PruneEntityRevisionsOverLimitParams struct {
	SiteID     string `json:"site_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) PruneEntityRevisionsOverLimit(ctx context.Context, arg PruneEntityRevisionsOverLimitParams) error {
	_, err := q.db.ExecContext(ctx, pruneEntityRevisionsOverLimit,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
	)
	return err
}
