// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package store

import (
	"context"
)

const deleteFormSubmissionsBySiteOlderThan = `-- name: DeleteFormSubmissionsBySiteOlderThan :execrows
DELETE FROM form_submissions
WHERE site_id = ? AND created_at < ?
`

type DeleteFormSubmissionsBySiteOlderThanParams struct {
	SiteID    string `json:"site_id"`
	CreatedAt string `json:"created_at"`
}

// Per-site retention sweep. form_submissions.data_json is the raw submitted
// payload (name, email, phone, free text) and the only delete that existed was
// single-row by id, so a contact form accumulated PII forever while the
// tenant's analytics window suggested otherwise.
func (q *Queries) DeleteFormSubmissionsBySiteOlderThan(ctx context.Context, arg DeleteFormSubmissionsBySiteOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFormSubmissionsBySiteOlderThan, arg.SiteID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
