// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guardrails.sql

package store

import (
	"context"
)

const createGuardrail = `-- name: CreateGuardrail :exec
INSERT INTO guardrail_rules (id, site_id, rule_type, target, value, severity, is_active, created_at)
VALUES (?, ?, ?, ?, ?, ?, 1, datetime('now'))
`

type CreateGuardrailParams struct {
	ID       string `json:"id"`
	SiteID   string `json:"site_id"`
	RuleType string `json:"rule_type"`
	Target   string `json:"target"`
	Value    string `json:"value"`
	Severity string `json:"severity"`
}

func (q *Queries) CreateGuardrail(ctx context.Context, arg CreateGuardrailParams) error {
	_, err := q.db.ExecContext(ctx, createGuardrail,
		arg.ID,
		arg.SiteID,
		arg.RuleType,
		arg.Target,
		arg.Value,
		arg.Severity,
	)
	return err
}

const deleteGuardrail = `-- name: DeleteGuardrail :exec
DELETE FROM guardrail_rules WHERE id = ?
`

func (q *Queries) DeleteGuardrail(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuardrail, id)
	return err
}

const getGuardrailByID = `-- name: GetGuardrailByID :one
SELECT id, site_id, rule_type, target, value, severity, is_active, created_at FROM guardrail_rules WHERE id = ?
`

func (q *Queries) GetGuardrailByID(ctx context.Context, id string) (GuardrailRule, error) {
	row := q.db.QueryRowContext(ctx, getGuardrailByID, id)
	var i GuardrailRule
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.RuleType,
		&i.Target,
		&i.Value,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGuardrailsBySite = `-- name: ListActiveGuardrailsBySite :many
SELECT id, site_id, rule_type, target, value, severity, is_active, created_at FROM guardrail_rules WHERE site_id = ? AND is_active = 1 ORDER BY rule_type, target
`

func (q *Queries) ListActiveGuardrailsBySite(ctx context.Context, siteID string) ([]GuardrailRule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGuardrailsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailRule{}
	for rows.Next() {
		var i GuardrailRule
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.RuleType,
			&i.Target,
			&i.Value,
			&i.Severity,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardrailsBySite = `-- name: ListGuardrailsBySite :many
SELECT id, site_id, rule_type, target, value, severity, is_active, created_at FROM guardrail_rules WHERE site_id = ? ORDER BY rule_type, target
`

func (q *Queries) ListGuardrailsBySite(ctx context.Context, siteID string) ([]GuardrailRule, error) {
	rows, err := q.db.QueryContext(ctx, listGuardrailsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailRule{}
	for rows.Next() {
		var i GuardrailRule
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.RuleType,
			&i.Target,
			&i.Value,
			&i.Severity,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuardrail = `-- name: UpdateGuardrail :exec
UPDATE guardrail_rules
SET rule_type = ?, target = ?, value = ?, severity = ?, is_active = ?
WHERE id = ?
`

type UpdateGuardrailParams struct {
	RuleType string `json:"rule_type"`
	Target   string `json:"target"`
	Value    string `json:"value"`
	Severity string `json:"severity"`
	IsActive int64  `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateGuardrail(ctx context.Context, arg UpdateGuardrailParams) error {
	_, err := q.db.ExecContext(ctx, updateGuardrail,
		arg.RuleType,
		arg.Target,
		arg.Value,
		arg.Severity,
		arg.IsActive,
		arg.ID,
	)
	return err
}
