// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_adjustments.sql

package store

import (
	"context"
)

const createInventoryAdjustment = `-- name: CreateInventoryAdjustment :exec
INSERT INTO inventory_adjustments (id, variant_id, site_id, delta, new_count, reason, note, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInventoryAdjustmentParams struct {
	ID        string `json:"id"`
	VariantID string `json:"variant_id"`
	SiteID    string `json:"site_id"`
	Delta     int64  `json:"delta"`
	NewCount  int64  `json:"new_count"`
	Reason    string `json:"reason"`
	Note      string `json:"note"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateInventoryAdjustment(ctx context.Context, arg CreateInventoryAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, createInventoryAdjustment,
		arg.ID,
		arg.VariantID,
		arg.SiteID,
		arg.Delta,
		arg.NewCount,
		arg.Reason,
		arg.Note,
		arg.CreatedBy,
	)
	return err
}

const listInventoryAdjustmentsBySite = `-- name: ListInventoryAdjustmentsBySite :many
SELECT id, variant_id, site_id, delta, new_count, reason, note, created_by, created_at FROM inventory_adjustments
WHERE site_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListInventoryAdjustmentsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListInventoryAdjustmentsBySite(ctx context.Context, arg ListInventoryAdjustmentsBySiteParams) ([]InventoryAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryAdjustmentsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryAdjustment{}
	for rows.Next() {
		var i InventoryAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.SiteID,
			&i.Delta,
			&i.NewCount,
			&i.Reason,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryAdjustmentsByVariant = `-- name: ListInventoryAdjustmentsByVariant :many
SELECT id, variant_id, site_id, delta, new_count, reason, note, created_by, created_at FROM inventory_adjustments
WHERE variant_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListInventoryAdjustmentsByVariantParams struct {
	VariantID string `json:"variant_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListInventoryAdjustmentsByVariant(ctx context.Context, arg ListInventoryAdjustmentsByVariantParams) ([]InventoryAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryAdjustmentsByVariant, arg.VariantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryAdjustment{}
	for rows.Next() {
		var i InventoryAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.SiteID,
			&i.Delta,
			&i.NewCount,
			&i.Reason,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
