// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package store

import (
	"context"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, email, role, token, created_by, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	Token     string `json:"token"`
	CreatedBy string `json:"created_by"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, email, role, token, created_by, created_at, expires_at, used_at FROM invites WHERE token = ?
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, email, role, token, created_by, created_at, expires_at, used_at FROM invites
WHERE used_at = '' AND expires_at > datetime('now')
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites SET used_at = datetime('now') WHERE id = ?
`

func (q *Queries) MarkInviteUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, id)
	return err
}
