// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledgebase.sql

package store

import (
	"context"
)

const createKnowledgebaseEntry = `-- name: CreateKnowledgebaseEntry :exec
INSERT INTO knowledgebase_entries (id, site_id, category, title, content, is_active, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?, datetime('now'), datetime('now'))
`

type CreateKnowledgebaseEntryParams struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateKnowledgebaseEntry(ctx context.Context, arg CreateKnowledgebaseEntryParams) error {
	_, err := q.db.ExecContext(ctx, createKnowledgebaseEntry,
		arg.ID,
		arg.SiteID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	return err
}

const deleteKnowledgebaseEntry = `-- name: DeleteKnowledgebaseEntry :exec
DELETE FROM knowledgebase_entries WHERE id = ?
`

func (q *Queries) DeleteKnowledgebaseEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteKnowledgebaseEntry, id)
	return err
}

const getKnowledgebaseByID = `-- name: GetKnowledgebaseByID :one
SELECT id, site_id, category, title, content, is_active, sort_order, created_at, updated_at FROM knowledgebase_entries WHERE id = ?
`

func (q *Queries) GetKnowledgebaseByID(ctx context.Context, id string) (KnowledgebaseEntry, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgebaseByID, id)
	var i KnowledgebaseEntry
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveKnowledgebaseBySite = `-- name: ListActiveKnowledgebaseBySite :many
SELECT id, site_id, category, title, content, is_active, sort_order, created_at, updated_at FROM knowledgebase_entries
WHERE site_id = ? AND is_active = 1 ORDER BY category, sort_order
`

func (q *Queries) ListActiveKnowledgebaseBySite(ctx context.Context, siteID string) ([]KnowledgebaseEntry, error) {
	rows, err := q.db.QueryContext(ctx, listActiveKnowledgebaseBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgebaseEntry{}
	for rows.Next() {
		var i KnowledgebaseEntry
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgebaseBySite = `-- name: ListKnowledgebaseBySite :many
SELECT id, site_id, category, title, content, is_active, sort_order, created_at, updated_at FROM knowledgebase_entries
WHERE site_id = ? ORDER BY category, sort_order
`

func (q *Queries) ListKnowledgebaseBySite(ctx context.Context, siteID string) ([]KnowledgebaseEntry, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgebaseBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgebaseEntry{}
	for rows.Next() {
		var i KnowledgebaseEntry
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgebaseEntry = `-- name: UpdateKnowledgebaseEntry :exec
UPDATE knowledgebase_entries
SET category = ?, title = ?, content = ?, is_active = ?, sort_order = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateKnowledgebaseEntryParams struct {
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	IsActive  int64  `json:"is_active"`
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateKnowledgebaseEntry(ctx context.Context, arg UpdateKnowledgebaseEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateKnowledgebaseEntry,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
