// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_folders.sql

package store

import (
	"context"
)

const createMediaFolder = `-- name: CreateMediaFolder :exec
INSERT INTO media_folders (site_id, name, is_system)
VALUES (?, ?, ?)
`

type CreateMediaFolderParams struct {
	SiteID   string `json:"site_id"`
	Name     string `json:"name"`
	IsSystem int64  `json:"is_system"`
}

func (q *Queries) CreateMediaFolder(ctx context.Context, arg CreateMediaFolderParams) error {
	_, err := q.db.ExecContext(ctx, createMediaFolder, arg.SiteID, arg.Name, arg.IsSystem)
	return err
}

const deleteMediaFolder = `-- name: DeleteMediaFolder :exec
DELETE FROM media_folders WHERE site_id = ? AND name = ? AND is_system = 0
`

type DeleteMediaFolderParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteMediaFolder(ctx context.Context, arg DeleteMediaFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFolder, arg.SiteID, arg.Name)
	return err
}

const ensureMediaFolder = `-- name: EnsureMediaFolder :exec
INSERT OR IGNORE INTO media_folders (site_id, name, is_system)
VALUES (?, ?, ?)
`

type EnsureMediaFolderParams struct {
	SiteID   string `json:"site_id"`
	Name     string `json:"name"`
	IsSystem int64  `json:"is_system"`
}

func (q *Queries) EnsureMediaFolder(ctx context.Context, arg EnsureMediaFolderParams) error {
	_, err := q.db.ExecContext(ctx, ensureMediaFolder, arg.SiteID, arg.Name, arg.IsSystem)
	return err
}

const getMediaFolder = `-- name: GetMediaFolder :one
SELECT site_id, name, is_system, created_at
FROM media_folders
WHERE site_id = ? AND name = ?
`

type GetMediaFolderParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetMediaFolder(ctx context.Context, arg GetMediaFolderParams) (MediaFolder, error) {
	row := q.db.QueryRowContext(ctx, getMediaFolder, arg.SiteID, arg.Name)
	var i MediaFolder
	err := row.Scan(
		&i.SiteID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaFoldersBySite = `-- name: ListMediaFoldersBySite :many
SELECT site_id, name, is_system, created_at
FROM media_folders
WHERE site_id = ?
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListMediaFoldersBySite(ctx context.Context, siteID string) ([]MediaFolder, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFoldersBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFolder{}
	for rows.Next() {
		var i MediaFolder
		if err := rows.Scan(
			&i.SiteID,
			&i.Name,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
