// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package store

import (
	"context"
	"strings"
)

const clearMediaFolder = `-- name: ClearMediaFolder :exec
UPDATE media SET
    folder = '',
    updated_at = datetime('now')
WHERE site_id = ? AND folder = ?
`

type ClearMediaFolderParams struct {
	SiteID string `json:"site_id"`
	Folder string `json:"folder"`
}

func (q *Queries) ClearMediaFolder(ctx context.Context, arg ClearMediaFolderParams) error {
	_, err := q.db.ExecContext(ctx, clearMediaFolder, arg.SiteID, arg.Folder)
	return err
}

const countMediaBySite = `-- name: CountMediaBySite :one
SELECT COUNT(*) FROM media WHERE site_id = ?
`

func (q *Queries) CountMediaBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaInFolder = `-- name: CountMediaInFolder :one
SELECT COUNT(*) FROM media WHERE site_id = ? AND folder = ?
`

type CountMediaInFolderParams struct {
	SiteID string `json:"site_id"`
	Folder string `json:"folder"`
}

func (q *Queries) CountMediaInFolder(ctx context.Context, arg CountMediaInFolderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaInFolder, arg.SiteID, arg.Folder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfiledMedia = `-- name: CountUnfiledMedia :one
SELECT COUNT(*) FROM media WHERE site_id = ? AND folder = ''
`

func (q *Queries) CountUnfiledMedia(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfiledMedia, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :exec
INSERT INTO media (id, site_id, filename, alt_text, mime_type, file_size, width, height, original_path, folder)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMediaParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Filename     string `json:"filename"`
	AltText      string `json:"alt_text"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	OriginalPath string `json:"original_path"`
	Folder       string `json:"folder"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.ExecContext(ctx, createMedia,
		arg.ID,
		arg.SiteID,
		arg.Filename,
		arg.AltText,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.OriginalPath,
		arg.Folder,
	)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE id = ?
`

func (q *Queries) GetMediaByID(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Filename,
		&i.AltText,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.VariantsJson,
		&i.OriginalPath,
		&i.Folder,
		&i.FocalX,
		&i.FocalY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaByIDs = `-- name: ListMediaByIDs :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListMediaByIDs(ctx context.Context, ids []string) ([]Medium, error) {
	query := listMediaByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.Folder,
			&i.FocalX,
			&i.FocalY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaBySite = `-- name: ListMediaBySite :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMediaBySite(ctx context.Context, siteID string) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.Folder,
			&i.FocalX,
			&i.FocalY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaBySitePaginated = `-- name: ListMediaBySitePaginated :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE site_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMediaBySitePaginatedParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMediaBySitePaginated(ctx context.Context, arg ListMediaBySitePaginatedParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaBySitePaginated, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.Folder,
			&i.FocalX,
			&i.FocalY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaInFolderPaginated = `-- name: ListMediaInFolderPaginated :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE site_id = ? AND folder = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMediaInFolderPaginatedParams struct {
	SiteID string `json:"site_id"`
	Folder string `json:"folder"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMediaInFolderPaginated(ctx context.Context, arg ListMediaInFolderPaginatedParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaInFolderPaginated,
		arg.SiteID,
		arg.Folder,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.Folder,
			&i.FocalX,
			&i.FocalY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfiledMediaPaginated = `-- name: ListUnfiledMediaPaginated :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, folder, focal_x, focal_y, created_at, updated_at FROM media WHERE site_id = ? AND folder = '' ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListUnfiledMediaPaginatedParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListUnfiledMediaPaginated(ctx context.Context, arg ListUnfiledMediaPaginatedParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listUnfiledMediaPaginated, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.Folder,
			&i.FocalX,
			&i.FocalY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE media SET
    alt_text = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateMediaParams struct {
	AltText string `json:"alt_text"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateMedia, arg.AltText, arg.ID)
	return err
}

const updateMediaFocalPoint = `-- name: UpdateMediaFocalPoint :exec
UPDATE media SET
    focal_x = ?,
    focal_y = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateMediaFocalPointParams struct {
	FocalX int64  `json:"focal_x"`
	FocalY int64  `json:"focal_y"`
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) UpdateMediaFocalPoint(ctx context.Context, arg UpdateMediaFocalPointParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFocalPoint,
		arg.FocalX,
		arg.FocalY,
		arg.ID,
		arg.SiteID,
	)
	return err
}

const updateMediaFolder = `-- name: UpdateMediaFolder :exec
UPDATE media SET
    folder = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateMediaFolderParams struct {
	Folder string `json:"folder"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMediaFolder(ctx context.Context, arg UpdateMediaFolderParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFolder, arg.Folder, arg.ID)
	return err
}

const updateMediaVariants = `-- name: UpdateMediaVariants :exec
UPDATE media SET
    width = ?,
    height = ?,
    blurhash = ?,
    variants_json = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateMediaVariantsParams struct {
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	Blurhash     string `json:"blurhash"`
	VariantsJson string `json:"variants_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaVariants,
		arg.Width,
		arg.Height,
		arg.Blurhash,
		arg.VariantsJson,
		arg.ID,
	)
	return err
}
