// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package store

import (
	"context"
	"strings"
)

const createMedia = `-- name: CreateMedia :exec
INSERT INTO media (id, site_id, filename, alt_text, mime_type, file_size, width, height, original_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMediaParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Filename     string `json:"filename"`
	AltText      string `json:"alt_text"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	OriginalPath string `json:"original_path"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.ExecContext(ctx, createMedia,
		arg.ID,
		arg.SiteID,
		arg.Filename,
		arg.AltText,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.OriginalPath,
	)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, created_at, updated_at FROM media WHERE id = ?
`

func (q *Queries) GetMediaByID(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Filename,
		&i.AltText,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.VariantsJson,
		&i.OriginalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaByIDs = `-- name: ListMediaByIDs :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, created_at, updated_at FROM media WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListMediaByIDs(ctx context.Context, ids []string) ([]Medium, error) {
	query := listMediaByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaBySite = `-- name: ListMediaBySite :many
SELECT id, site_id, filename, alt_text, mime_type, file_size, width, height, blurhash, variants_json, original_path, created_at, updated_at FROM media WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMediaBySite(ctx context.Context, siteID string) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Filename,
			&i.AltText,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.VariantsJson,
			&i.OriginalPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE media SET
    alt_text = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateMediaParams struct {
	AltText string `json:"alt_text"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateMedia, arg.AltText, arg.ID)
	return err
}

const updateMediaVariants = `-- name: UpdateMediaVariants :exec
UPDATE media SET
    width = ?,
    height = ?,
    blurhash = ?,
    variants_json = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateMediaVariantsParams struct {
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	Blurhash     string `json:"blurhash"`
	VariantsJson string `json:"variants_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaVariants,
		arg.Width,
		arg.Height,
		arg.Blurhash,
		arg.VariantsJson,
		arg.ID,
	)
	return err
}
