// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missing_urls.sql

package store

import (
	"context"
)

const countMissingURLsBySite = `-- name: CountMissingURLsBySite :one
SELECT COUNT(*) FROM missing_urls WHERE site_id = ?
`

func (q *Queries) CountMissingURLsBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMissingURLsBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMissingURL = `-- name: DeleteMissingURL :exec
DELETE FROM missing_urls WHERE id = ?
`

func (q *Queries) DeleteMissingURL(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMissingURL, id)
	return err
}

const deleteMissingURLByPath = `-- name: DeleteMissingURLByPath :exec
DELETE FROM missing_urls WHERE site_id = ? AND path = ?
`

type DeleteMissingURLByPathParams struct {
	SiteID string `json:"site_id"`
	Path   string `json:"path"`
}

func (q *Queries) DeleteMissingURLByPath(ctx context.Context, arg DeleteMissingURLByPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteMissingURLByPath, arg.SiteID, arg.Path)
	return err
}

const getMissingURLByID = `-- name: GetMissingURLByID :one
SELECT id, site_id, path, referer, hit_count, first_seen, last_seen FROM missing_urls WHERE id = ?
`

func (q *Queries) GetMissingURLByID(ctx context.Context, id string) (MissingUrl, error) {
	row := q.db.QueryRowContext(ctx, getMissingURLByID, id)
	var i MissingUrl
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Path,
		&i.Referer,
		&i.HitCount,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getMissingURLByPath = `-- name: GetMissingURLByPath :one
SELECT id, site_id, path, referer, hit_count, first_seen, last_seen FROM missing_urls WHERE site_id = ? AND path = ?
`

type GetMissingURLByPathParams struct {
	SiteID string `json:"site_id"`
	Path   string `json:"path"`
}

func (q *Queries) GetMissingURLByPath(ctx context.Context, arg GetMissingURLByPathParams) (MissingUrl, error) {
	row := q.db.QueryRowContext(ctx, getMissingURLByPath, arg.SiteID, arg.Path)
	var i MissingUrl
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Path,
		&i.Referer,
		&i.HitCount,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listMissingURLsBySite = `-- name: ListMissingURLsBySite :many
SELECT id, site_id, path, referer, hit_count, first_seen, last_seen FROM missing_urls
WHERE site_id = ?
ORDER BY hit_count DESC, last_seen DESC
LIMIT ?
`

type ListMissingURLsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListMissingURLsBySite(ctx context.Context, arg ListMissingURLsBySiteParams) ([]MissingUrl, error) {
	rows, err := q.db.QueryContext(ctx, listMissingURLsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MissingUrl{}
	for rows.Next() {
		var i MissingUrl
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Path,
			&i.Referer,
			&i.HitCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMissingURL = `-- name: UpsertMissingURL :exec
INSERT INTO missing_urls (id, site_id, path, referer, hit_count, first_seen, last_seen)
VALUES (?, ?, ?, ?, 1, datetime('now'), datetime('now'))
ON CONFLICT(site_id, path) DO UPDATE
  SET hit_count = hit_count + 1,
      last_seen = datetime('now'),
      referer = CASE WHEN excluded.referer != '' THEN excluded.referer ELSE missing_urls.referer END
`

type UpsertMissingURLParams struct {
	ID      string `json:"id"`
	SiteID  string `json:"site_id"`
	Path    string `json:"path"`
	Referer string `json:"referer"`
}

func (q *Queries) UpsertMissingURL(ctx context.Context, arg UpsertMissingURLParams) error {
	_, err := q.db.ExecContext(ctx, upsertMissingURL,
		arg.ID,
		arg.SiteID,
		arg.Path,
		arg.Referer,
	)
	return err
}
