// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Block struct {
	ID              string `json:"id"`
	PageID          string `json:"page_id"`
	BlockType       string `json:"block_type"`
	SortOrder       int64  `json:"sort_order"`
	DataJson        string `json:"data_json"`
	StyleJson       string `json:"style_json"`
	IsVisible       int64  `json:"is_visible"`
	TemplateVersion int64  `json:"template_version"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Deployment struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Status       string `json:"status"`
	BuildLog     string `json:"build_log"`
	DeployTarget string `json:"deploy_target"`
	DeployConfig string `json:"deploy_config"`
	PagesBuilt   int64  `json:"pages_built"`
	DurationMs   int64  `json:"duration_ms"`
	Error        string `json:"error"`
	CreatedAt    string `json:"created_at"`
	CompletedAt  string `json:"completed_at"`
}

type GlobalBlock struct {
	ID              string `json:"id"`
	SiteID          string `json:"site_id"`
	Name            string `json:"name"`
	Slot            string `json:"slot"`
	BlockType       string `json:"block_type"`
	DataJson        string `json:"data_json"`
	StyleJson       string `json:"style_json"`
	IsActive        int64  `json:"is_active"`
	SortOrder       int64  `json:"sort_order"`
	TemplateVersion int64  `json:"template_version"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Medium struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Filename     string `json:"filename"`
	AltText      string `json:"alt_text"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	Blurhash     string `json:"blurhash"`
	VariantsJson string `json:"variants_json"`
	OriginalPath string `json:"original_path"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Page struct {
	ID              string `json:"id"`
	SiteID          string `json:"site_id"`
	Title           string `json:"title"`
	Slug            string `json:"slug"`
	Status          string `json:"status"`
	MetaTitle       string `json:"meta_title"`
	MetaDescription string `json:"meta_description"`
	OgImageID       string `json:"og_image_id"`
	Layout          string `json:"layout"`
	SortOrder       int64  `json:"sort_order"`
	ShowInNav       int64  `json:"show_in_nav"`
	NavLabel        string `json:"nav_label"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Site struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Slug            string `json:"slug"`
	Domain          string `json:"domain"`
	Status          string `json:"status"`
	PrimaryColor    string `json:"primary_color"`
	SecondaryColor  string `json:"secondary_color"`
	BgColor         string `json:"bg_color"`
	TextColor       string `json:"text_color"`
	FontHeading     string `json:"font_heading"`
	FontBody        string `json:"font_body"`
	MetaTitle       string `json:"meta_title"`
	MetaDescription string `json:"meta_description"`
	OgImageID       string `json:"og_image_id"`
	FaviconID       string `json:"favicon_id"`
	Ga4ID           string `json:"ga4_id"`
	UmamiID         string `json:"umami_id"`
	UmamiUrl        string `json:"umami_url"`
	CookiebitDomain string `json:"cookiebit_domain"`
	Lang            string `json:"lang"`
	LastBuildAt     string `json:"last_build_at"`
	LastBuildStatus string `json:"last_build_status"`
	LastBuildError  string `json:"last_build_error"`
	LastDeployAt    string `json:"last_deploy_at"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	TokenVersion int64  `json:"token_version"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
