// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type AgentKey struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	KeyHash      string `json:"key_hash"`
	Capabilities string `json:"capabilities"`
	IsActive     int64  `json:"is_active"`
	LastUsedAt   string `json:"last_used_at"`
	CreatedAt    string `json:"created_at"`
}

type AllowedScript struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Domain    string `json:"domain"`
	Purpose   string `json:"purpose"`
	Kind      string `json:"kind"`
	IsActive  int64  `json:"is_active"`
	CreatedAt string `json:"created_at"`
}

type AuditLog struct {
	ID           string `json:"id"`
	ActorUserID  string `json:"actor_user_id"`
	ActorRole    string `json:"actor_role"`
	ActorIp      string `json:"actor_ip"`
	SiteID       string `json:"site_id"`
	Action       string `json:"action"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	ChangesJson  string `json:"changes_json"`
	CreatedAt    string `json:"created_at"`
}

type BillingEvent struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
	EventType       string `json:"event_type"`
	PayloadJson     string `json:"payload_json"`
	ProcessedAt     string `json:"processed_at"`
	Error           string `json:"error"`
	CreatedAt       string `json:"created_at"`
}

type Block struct {
	ID              string `json:"id"`
	PageID          string `json:"page_id"`
	BlockType       string `json:"block_type"`
	Name            string `json:"name"`
	SortOrder       int64  `json:"sort_order"`
	DataJson        string `json:"data_json"`
	StyleJson       string `json:"style_json"`
	IsVisible       int64  `json:"is_visible"`
	TemplateVersion int64  `json:"template_version"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Collection struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	SchemaJson   string `json:"schema_json"`
	SettingsJson string `json:"settings_json"`
	SortOrder    int64  `json:"sort_order"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type CollectionItem struct {
	ID           string `json:"id"`
	CollectionID string `json:"collection_id"`
	SiteID       string `json:"site_id"`
	Slug         string `json:"slug"`
	Title        string `json:"title"`
	DataJson     string `json:"data_json"`
	Locale       string `json:"locale"`
	Status       string `json:"status"`
	PublishedAt  string `json:"published_at"`
	SortOrder    int64  `json:"sort_order"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Component struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Template    string `json:"template"`
	PropsSchema string `json:"props_schema"`
	CssClasses  string `json:"css_classes"`
	UsageNote   string `json:"usage_note"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type ConsentRecord struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	SessionID      string `json:"session_id"`
	Fingerprint    string `json:"fingerprint"`
	Domain         string `json:"domain"`
	PageUrl        string `json:"page_url"`
	Referrer       string `json:"referrer"`
	UserAgent      string `json:"user_agent"`
	IpHash         string `json:"ip_hash"`
	ConsentMethod  string `json:"consent_method"`
	ConsentVersion int64  `json:"consent_version"`
	CategoriesJson string `json:"categories_json"`
	GpcActive      int64  `json:"gpc_active"`
	CreatedAt      int64  `json:"created_at"`
	CreatedAtIso   string `json:"created_at_iso"`
}

type ConsentSalt struct {
	DayUtc    string `json:"day_utc"`
	Salt      string `json:"salt"`
	CreatedAt string `json:"created_at"`
}

type ConversionEvent struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	GoalID         string `json:"goal_id"`
	Fingerprint    string `json:"fingerprint"`
	SessionID      string `json:"session_id"`
	Path           string `json:"path"`
	Ts             string `json:"ts"`
	ValueCents     int64  `json:"value_cents"`
	ValueCurrency  string `json:"value_currency"`
	PropertiesJson string `json:"properties_json"`
}

type ConversionGoal struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	MatchType     string `json:"match_type"`
	MatchValue    string `json:"match_value"`
	ValueCents    int64  `json:"value_cents"`
	ValueCurrency string `json:"value_currency"`
	Active        int64  `json:"active"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type CssClass struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	Css       string `json:"css"`
	UsageNote string `json:"usage_note"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type DeployTarget struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	ConfigJson string `json:"config_json"`
	IsDefault  int64  `json:"is_default"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type Deployment struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Status       string `json:"status"`
	BuildLog     string `json:"build_log"`
	DeployTarget string `json:"deploy_target"`
	DeployConfig string `json:"deploy_config"`
	PagesBuilt   int64  `json:"pages_built"`
	DurationMs   int64  `json:"duration_ms"`
	Error        string `json:"error"`
	TargetID     string `json:"target_id"`
	DeployUrl    string `json:"deploy_url"`
	DeployedAt   string `json:"deployed_at"`
	CreatedAt    string `json:"created_at"`
	CompletedAt  string `json:"completed_at"`
}

type DesignReference struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Url         string `json:"url"`
	Label       string `json:"label"`
	RefType     string `json:"ref_type"`
	FetchedJson string `json:"fetched_json"`
	FetchedAt   string `json:"fetched_at"`
	CreatedAt   string `json:"created_at"`
}

type Evaluation struct {
	ID         string `json:"id"`
	BuildID    string `json:"build_id"`
	SiteID     string `json:"site_id"`
	Category   string `json:"category"`
	Score      int64  `json:"score"`
	MaxScore   int64  `json:"max_score"`
	Grade      string `json:"grade"`
	ChecksJson string `json:"checks_json"`
	CreatedAt  string `json:"created_at"`
}

type Form struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	FieldsJson   string `json:"fields_json"`
	Action       string `json:"action"`
	ActionConfig string `json:"action_config"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type FormSubmission struct {
	ID        string `json:"id"`
	FormID    string `json:"form_id"`
	SiteID    string `json:"site_id"`
	DataJson  string `json:"data_json"`
	IpHash    string `json:"ip_hash"`
	CreatedAt string `json:"created_at"`
}

type GlobalBlock struct {
	ID              string `json:"id"`
	SiteID          string `json:"site_id"`
	Name            string `json:"name"`
	Slot            string `json:"slot"`
	BlockType       string `json:"block_type"`
	DataJson        string `json:"data_json"`
	StyleJson       string `json:"style_json"`
	IsActive        int64  `json:"is_active"`
	SortOrder       int64  `json:"sort_order"`
	TemplateVersion int64  `json:"template_version"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type GuardrailRule struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	RuleType  string `json:"rule_type"`
	Target    string `json:"target"`
	Value     string `json:"value"`
	Severity  string `json:"severity"`
	IsActive  int64  `json:"is_active"`
	CreatedAt string `json:"created_at"`
}

type Invite struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	Token     string `json:"token"`
	CreatedBy string `json:"created_by"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
	UsedAt    string `json:"used_at"`
}

type KnowledgebaseEntry struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	IsActive  int64  `json:"is_active"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type MediaFolder struct {
	SiteID    string `json:"site_id"`
	Name      string `json:"name"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
}

type Medium struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Filename     string `json:"filename"`
	AltText      string `json:"alt_text"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	Blurhash     string `json:"blurhash"`
	VariantsJson string `json:"variants_json"`
	OriginalPath string `json:"original_path"`
	Folder       string `json:"folder"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Migration struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	SourceUrl    string `json:"source_url"`
	SourceType   string `json:"source_type"`
	ManifestJson string `json:"manifest_json"`
	Status       string `json:"status"`
	Error        string `json:"error"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type MigrationVerification struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	MigrationID string `json:"migration_id"`
	SourceUrl   string `json:"source_url"`
	StatusCode  int64  `json:"status_code"`
	FinalUrl    string `json:"final_url"`
	Hops        int64  `json:"hops"`
	Ok          int64  `json:"ok"`
	Error       string `json:"error"`
	CheckedAt   string `json:"checked_at"`
}

type MissingUrl struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Path      string `json:"path"`
	Referer   string `json:"referer"`
	HitCount  int64  `json:"hit_count"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
}

type Page struct {
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
	Title            string `json:"title"`
	Slug             string `json:"slug"`
	Status           string `json:"status"`
	MetaTitle        string `json:"meta_title"`
	MetaDescription  string `json:"meta_description"`
	OgImageID        string `json:"og_image_id"`
	Layout           string `json:"layout"`
	SortOrder        int64  `json:"sort_order"`
	ShowInNav        int64  `json:"show_in_nav"`
	NavLabel         string `json:"nav_label"`
	NoIndex          int64  `json:"no_index"`
	CanonicalUrl     string `json:"canonical_url"`
	HideGlobalBlocks int64  `json:"hide_global_blocks"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type PasswordReset struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	TokenHash   string `json:"token_hash"`
	ExpiresAt   string `json:"expires_at"`
	UsedAt      string `json:"used_at"`
	RequesterIp string `json:"requester_ip"`
	CreatedAt   string `json:"created_at"`
}

type Redirect struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	FromPath   string `json:"from_path"`
	ToPath     string `json:"to_path"`
	StatusCode int64  `json:"status_code"`
	IsAuto     int64  `json:"is_auto"`
	CreatedAt  string `json:"created_at"`
}

type SchemaVersion struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
	Note      string `json:"note"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Site struct {
	ID                  string `json:"id"`
	WorkspaceID         string `json:"workspace_id"`
	Name                string `json:"name"`
	Slug                string `json:"slug"`
	Domain              string `json:"domain"`
	Status              string `json:"status"`
	PrimaryColor        string `json:"primary_color"`
	SecondaryColor      string `json:"secondary_color"`
	SurfaceColor        string `json:"surface_color"`
	BorderColor         string `json:"border_color"`
	MutedColor          string `json:"muted_color"`
	AccentColor         string `json:"accent_color"`
	OnPrimaryColor      string `json:"on_primary_color"`
	BgColor             string `json:"bg_color"`
	TextColor           string `json:"text_color"`
	FontHeading         string `json:"font_heading"`
	FontBody            string `json:"font_body"`
	MetaTitle           string `json:"meta_title"`
	MetaDescription     string `json:"meta_description"`
	OgImageID           string `json:"og_image_id"`
	FaviconID           string `json:"favicon_id"`
	Ga4ID               string `json:"ga4_id"`
	UmamiID             string `json:"umami_id"`
	UmamiUrl            string `json:"umami_url"`
	CookieproofDomain   string `json:"cookieproof_domain"`
	Lang                string `json:"lang"`
	LastBuildAt         string `json:"last_build_at"`
	LastBuildStatus     string `json:"last_build_status"`
	LastBuildError      string `json:"last_build_error"`
	LastDeployAt        string `json:"last_deploy_at"`
	StorageQuotaBytes   int64  `json:"storage_quota_bytes"`
	BuildMinutesQuota   int64  `json:"build_minutes_quota"`
	QuotaOverageBlocked int64  `json:"quota_overage_blocked"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type SiteArchitecture struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	StructureType string `json:"structure_type"`
	MaxDepth      int64  `json:"max_depth"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type SiteDomain struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Hostname    string `json:"hostname"`
	Status      string `json:"status"`
	VerifyToken string `json:"verify_token"`
	CertPath    string `json:"cert_path"`
	LastCheckAt string `json:"last_check_at"`
	LastError   string `json:"last_error"`
	IsCanonical int64  `json:"is_canonical"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type SiteFont struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	FamilyName   string `json:"family_name"`
	Weight       int64  `json:"weight"`
	Style        string `json:"style"`
	FilePath     string `json:"file_path"`
	FileSize     int64  `json:"file_size"`
	OriginalName string `json:"original_name"`
	CreatedAt    string `json:"created_at"`
}

type SiteMember struct {
	SiteID    string `json:"site_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

type SiteProfile struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	BusinessName   string `json:"business_name"`
	RegistrationNr string `json:"registration_nr"`
	Country        string `json:"country"`
	ContactEmail   string `json:"contact_email"`
	ContactPhone   string `json:"contact_phone"`
	PrivacyEmail   string `json:"privacy_email"`
	SecurityEmail  string `json:"security_email"`
	AddressLine1   string `json:"address_line1"`
	AddressLine2   string `json:"address_line2"`
	City           string `json:"city"`
	PostalCode     string `json:"postal_code"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type SiteSetting struct {
	ID        string `json:"id"`
	SiteID    string `json:"site_id"`
	Category  string `json:"category"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type SiteSilo struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	Name       string `json:"name"`
	SlugPrefix string `json:"slug_prefix"`
	SiloType   string `json:"silo_type"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  string `json:"created_at"`
}

type Subscription struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	Provider           string `json:"provider"`
	ExternalID         string `json:"external_id"`
	ExternalCustomerID string `json:"external_customer_id"`
	Plan               string `json:"plan"`
	Status             string `json:"status"`
	AmountCents        int64  `json:"amount_cents"`
	Currency           string `json:"currency"`
	IntervalUnit       string `json:"interval_unit"`
	IntervalCount      int64  `json:"interval_count"`
	CurrentPeriodEnd   string `json:"current_period_end"`
	CancelAt           string `json:"cancel_at"`
	MetadataJson       string `json:"metadata_json"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

type User struct {
	ID               string `json:"id"`
	Email            string `json:"email"`
	PasswordHash     string `json:"password_hash"`
	Name             string `json:"name"`
	Role             string `json:"role"`
	TokenVersion     int64  `json:"token_version"`
	TotpSecret       string `json:"totp_secret"`
	TotpEnrolledAt   string `json:"totp_enrolled_at"`
	TotpRecoveryJson string `json:"totp_recovery_json"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type VerifyJob struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	MigrationID    string `json:"migration_id"`
	Status         string `json:"status"`
	TotalUrls      int64  `json:"total_urls"`
	ProcessedUrls  int64  `json:"processed_urls"`
	OkCount        int64  `json:"ok_count"`
	FailCount      int64  `json:"fail_count"`
	DeployedDomain string `json:"deployed_domain"`
	Error          string `json:"error"`
	CreatedAt      string `json:"created_at"`
	StartedAt      string `json:"started_at"`
	CompletedAt    string `json:"completed_at"`
}

type VisitEngagement struct {
	ID                   string `json:"id"`
	SiteID               string `json:"site_id"`
	Fingerprint          string `json:"fingerprint"`
	Path                 string `json:"path"`
	Ts                   string `json:"ts"`
	ScreenW              int64  `json:"screen_w"`
	ScreenH              int64  `json:"screen_h"`
	ViewportW            int64  `json:"viewport_w"`
	ViewportH            int64  `json:"viewport_h"`
	PrefersDark          int64  `json:"prefers_dark"`
	PrefersReducedMotion int64  `json:"prefers_reduced_motion"`
	TimeOnPageMs         int64  `json:"time_on_page_ms"`
	MaxScrollPct         int64  `json:"max_scroll_pct"`
}

type VisitEvent struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
	SessionID   string `json:"session_id"`
	Path        string `json:"path"`
	Referer     string `json:"referer"`
	Status      int64  `json:"status"`
	Ms          int64  `json:"ms"`
	Ts          string `json:"ts"`
	Browser     string `json:"browser"`
	Os          string `json:"os"`
	Device      string `json:"device"`
	Country     string `json:"country"`
	Lang        string `json:"lang"`
	UtmSource   string `json:"utm_source"`
	UtmMedium   string `json:"utm_medium"`
	UtmCampaign string `json:"utm_campaign"`
}

type VisitSession struct {
	ID                    string `json:"id"`
	SiteID                string `json:"site_id"`
	Fingerprint           string `json:"fingerprint"`
	VisitorID             string `json:"visitor_id"`
	Email                 string `json:"email"`
	ConsentMethod         string `json:"consent_method"`
	ConsentCategoriesJson string `json:"consent_categories_json"`
	StartedAt             string `json:"started_at"`
	LastSeenAt            string `json:"last_seen_at"`
	PageCount             int64  `json:"page_count"`
	IdentifiedAt          string `json:"identified_at"`
	MetadataJson          string `json:"metadata_json"`
	MetadataExpiresAt     string `json:"metadata_expires_at"`
	IdentityConfirmedAt   string `json:"identity_confirmed_at"`
}

type Waitlist struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Name        string `json:"name"`
	UseCase     string `json:"use_case"`
	Region      string `json:"region"`
	SourceIp    string `json:"source_ip"`
	UserAgent   string `json:"user_agent"`
	InvitedAt   string `json:"invited_at"`
	InviteToken string `json:"invite_token"`
	Notes       string `json:"notes"`
	CreatedAt   string `json:"created_at"`
}

type Workspace struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	Slug                 string `json:"slug"`
	Plan                 string `json:"plan"`
	Region               string `json:"region"`
	BillingEmail         string `json:"billing_email"`
	StripeCustomerID     string `json:"stripe_customer_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	Status               string `json:"status"`
	TrialEndsAt          string `json:"trial_ends_at"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type WorkspaceInvite struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Email       string `json:"email"`
	Role        string `json:"role"`
	Token       string `json:"token"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
	ExpiresAt   string `json:"expires_at"`
	UsedAt      string `json:"used_at"`
}

type WorkspaceMember struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
	CreatedAt   string `json:"created_at"`
}
