// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package store

import (
	"context"
)

const countOrdersBySite = `-- name: CountOrdersBySite :one
SELECT CAST(COUNT(*) AS INTEGER) FROM orders WHERE site_id = ?
`

func (q *Queries) CountOrdersBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersBySite, siteID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    id, site_id, order_number, status,
    customer_name, customer_email, customer_phone,
    shipping_address_json, billing_address_json,
    subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents,
    currency, discount_code_id,
    payment_provider, payment_id, payment_status, payment_checkout_url,
    notes, metadata_json
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID                  string `json:"id"`
	SiteID              string `json:"site_id"`
	OrderNumber         string `json:"order_number"`
	Status              string `json:"status"`
	CustomerName        string `json:"customer_name"`
	CustomerEmail       string `json:"customer_email"`
	CustomerPhone       string `json:"customer_phone"`
	ShippingAddressJson string `json:"shipping_address_json"`
	BillingAddressJson  string `json:"billing_address_json"`
	SubtotalCents       int64  `json:"subtotal_cents"`
	DiscountCents       int64  `json:"discount_cents"`
	ShippingCents       int64  `json:"shipping_cents"`
	TaxCents            int64  `json:"tax_cents"`
	TotalCents          int64  `json:"total_cents"`
	Currency            string `json:"currency"`
	DiscountCodeID      string `json:"discount_code_id"`
	PaymentProvider     string `json:"payment_provider"`
	PaymentID           string `json:"payment_id"`
	PaymentStatus       string `json:"payment_status"`
	PaymentCheckoutUrl  string `json:"payment_checkout_url"`
	Notes               string `json:"notes"`
	MetadataJson        string `json:"metadata_json"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.SiteID,
		arg.OrderNumber,
		arg.Status,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.ShippingAddressJson,
		arg.BillingAddressJson,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.ShippingCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.Currency,
		arg.DiscountCodeID,
		arg.PaymentProvider,
		arg.PaymentID,
		arg.PaymentStatus,
		arg.PaymentCheckoutUrl,
		arg.Notes,
		arg.MetadataJson,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, site_id, order_number, status, customer_name, customer_email, customer_phone, shipping_address_json, billing_address_json, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, discount_code_id, payment_provider, payment_id, payment_status, payment_checkout_url, refund_id, notes, metadata_json, created_at, updated_at, paid_at, fulfilled_at, cancelled_at, refunded_at FROM orders WHERE id = ? AND site_id = ?
`

type GetOrderByIDParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.SiteID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.OrderNumber,
		&i.Status,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.ShippingAddressJson,
		&i.BillingAddressJson,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.DiscountCodeID,
		&i.PaymentProvider,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.PaymentCheckoutUrl,
		&i.RefundID,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.FulfilledAt,
		&i.CancelledAt,
		&i.RefundedAt,
	)
	return i, err
}

const getOrderByOrderNumber = `-- name: GetOrderByOrderNumber :one
SELECT id, site_id, order_number, status, customer_name, customer_email, customer_phone, shipping_address_json, billing_address_json, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, discount_code_id, payment_provider, payment_id, payment_status, payment_checkout_url, refund_id, notes, metadata_json, created_at, updated_at, paid_at, fulfilled_at, cancelled_at, refunded_at FROM orders WHERE site_id = ? AND order_number = ?
`

type GetOrderByOrderNumberParams struct {
	SiteID      string `json:"site_id"`
	OrderNumber string `json:"order_number"`
}

func (q *Queries) GetOrderByOrderNumber(ctx context.Context, arg GetOrderByOrderNumberParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByOrderNumber, arg.SiteID, arg.OrderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.OrderNumber,
		&i.Status,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.ShippingAddressJson,
		&i.BillingAddressJson,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.DiscountCodeID,
		&i.PaymentProvider,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.PaymentCheckoutUrl,
		&i.RefundID,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.FulfilledAt,
		&i.CancelledAt,
		&i.RefundedAt,
	)
	return i, err
}

const getOrderByPaymentID = `-- name: GetOrderByPaymentID :one
SELECT id, site_id, order_number, status, customer_name, customer_email, customer_phone, shipping_address_json, billing_address_json, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, discount_code_id, payment_provider, payment_id, payment_status, payment_checkout_url, refund_id, notes, metadata_json, created_at, updated_at, paid_at, fulfilled_at, cancelled_at, refunded_at FROM orders WHERE payment_id = ? LIMIT 1
`

func (q *Queries) GetOrderByPaymentID(ctx context.Context, paymentID string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByPaymentID, paymentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.OrderNumber,
		&i.Status,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.ShippingAddressJson,
		&i.BillingAddressJson,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.DiscountCodeID,
		&i.PaymentProvider,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.PaymentCheckoutUrl,
		&i.RefundID,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.FulfilledAt,
		&i.CancelledAt,
		&i.RefundedAt,
	)
	return i, err
}

const listOrdersBySite = `-- name: ListOrdersBySite :many
SELECT id, site_id, order_number, status, customer_name, customer_email, customer_phone, shipping_address_json, billing_address_json, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, discount_code_id, payment_provider, payment_id, payment_status, payment_checkout_url, refund_id, notes, metadata_json, created_at, updated_at, paid_at, fulfilled_at, cancelled_at, refunded_at FROM orders
WHERE site_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListOrdersBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListOrdersBySite(ctx context.Context, arg ListOrdersBySiteParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.OrderNumber,
			&i.Status,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.ShippingAddressJson,
			&i.BillingAddressJson,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.DiscountCodeID,
			&i.PaymentProvider,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentCheckoutUrl,
			&i.RefundID,
			&i.Notes,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.FulfilledAt,
			&i.CancelledAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersBySiteStatus = `-- name: ListOrdersBySiteStatus :many
SELECT id, site_id, order_number, status, customer_name, customer_email, customer_phone, shipping_address_json, billing_address_json, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, discount_code_id, payment_provider, payment_id, payment_status, payment_checkout_url, refund_id, notes, metadata_json, created_at, updated_at, paid_at, fulfilled_at, cancelled_at, refunded_at FROM orders
WHERE site_id = ? AND status = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListOrdersBySiteStatusParams struct {
	SiteID string `json:"site_id"`
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListOrdersBySiteStatus(ctx context.Context, arg ListOrdersBySiteStatusParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersBySiteStatus, arg.SiteID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.OrderNumber,
			&i.Status,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.ShippingAddressJson,
			&i.BillingAddressJson,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.DiscountCodeID,
			&i.PaymentProvider,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentCheckoutUrl,
			&i.RefundID,
			&i.Notes,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.FulfilledAt,
			&i.CancelledAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUnpaidOrders = `-- name: ListStaleUnpaidOrders :many
SELECT id, site_id, status, payment_status, payment_id, discount_code_id, total_cents, currency, created_at
FROM orders
WHERE status = 'pending'
  AND payment_id = ''
  AND created_at < ?
ORDER BY created_at
LIMIT ?
`

type ListStaleUnpaidOrdersParams struct {
	CreatedAt string `json:"created_at"`
	Limit     int64  `json:"limit"`
}

type ListStaleUnpaidOrdersRow struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	Status         string `json:"status"`
	PaymentStatus  string `json:"payment_status"`
	PaymentID      string `json:"payment_id"`
	DiscountCodeID string `json:"discount_code_id"`
	TotalCents     int64  `json:"total_cents"`
	Currency       string `json:"currency"`
	CreatedAt      string `json:"created_at"`
}

// Reaper feed: orders that committed their inventory + discount
// reservations and then never acquired a payment. Checkout commits the
// reservation tx BEFORE calling Mollie, so a Mollie outage, a missing API
// key or an unresolvable public URL all leave the row at 'pending' with an
// empty payment_id. No webhook will ever arrive for those, so the release
// path was unreachable and the stock stayed consumed forever.
//
// payment_id = ” is the load-bearing predicate: an order that DID reach
// Mollie has one, and its reservation is legitimately held while the
// customer sits on the payment page. Only the never-got-that-far rows are
// safe to reap, so a slow customer is never false-reaped.
func (q *Queries) ListStaleUnpaidOrders(ctx context.Context, arg ListStaleUnpaidOrdersParams) ([]ListStaleUnpaidOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleUnpaidOrders, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleUnpaidOrdersRow{}
	for rows.Next() {
		var i ListStaleUnpaidOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentID,
			&i.DiscountCodeID,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderNotes = `-- name: UpdateOrderNotes :exec
UPDATE orders
SET notes = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateOrderNotesParams struct {
	Notes  string `json:"notes"`
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) UpdateOrderNotes(ctx context.Context, arg UpdateOrderNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderNotes, arg.Notes, arg.ID, arg.SiteID)
	return err
}

const updateOrderPayment = `-- name: UpdateOrderPayment :exec
UPDATE orders
SET payment_id = ?,
    payment_checkout_url = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateOrderPaymentParams struct {
	PaymentID          string `json:"payment_id"`
	PaymentCheckoutUrl string `json:"payment_checkout_url"`
	ID                 string `json:"id"`
	SiteID             string `json:"site_id"`
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPayment,
		arg.PaymentID,
		arg.PaymentCheckoutUrl,
		arg.ID,
		arg.SiteID,
	)
	return err
}

const updateOrderRefundID = `-- name: UpdateOrderRefundID :exec
UPDATE orders
SET refund_id = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateOrderRefundIDParams struct {
	RefundID string `json:"refund_id"`
	ID       string `json:"id"`
	SiteID   string `json:"site_id"`
}

func (q *Queries) UpdateOrderRefundID(ctx context.Context, arg UpdateOrderRefundIDParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderRefundID, arg.RefundID, arg.ID, arg.SiteID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?,
    payment_status = ?,
    paid_at = CASE WHEN ? = 'paid' AND paid_at = '' THEN datetime('now') ELSE paid_at END,
    fulfilled_at = CASE WHEN ? = 'fulfilled' AND fulfilled_at = '' THEN datetime('now') ELSE fulfilled_at END,
    cancelled_at = CASE WHEN ? = 'cancelled' AND cancelled_at = '' THEN datetime('now') ELSE cancelled_at END,
    refunded_at = CASE WHEN ? = 'refunded' AND refunded_at = '' THEN datetime('now') ELSE refunded_at END,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateOrderStatusParams struct {
	Status        string      `json:"status"`
	PaymentStatus string      `json:"payment_status"`
	Column3       interface{} `json:"column_3"`
	Column4       interface{} `json:"column_4"`
	Column5       interface{} `json:"column_5"`
	Column6       interface{} `json:"column_6"`
	ID            string      `json:"id"`
	SiteID        string      `json:"site_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus,
		arg.Status,
		arg.PaymentStatus,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.ID,
		arg.SiteID,
	)
	return err
}
