// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_locales.sql

package store

import (
	"context"
)

const deletePageLocale = `-- name: DeletePageLocale :exec
DELETE FROM page_locales WHERE page_id = ? AND locale = ?
`

type DeletePageLocaleParams struct {
	PageID string `json:"page_id"`
	Locale string `json:"locale"`
}

func (q *Queries) DeletePageLocale(ctx context.Context, arg DeletePageLocaleParams) error {
	_, err := q.db.ExecContext(ctx, deletePageLocale, arg.PageID, arg.Locale)
	return err
}

const deletePageLocalesByLocale = `-- name: DeletePageLocalesByLocale :exec
DELETE FROM page_locales WHERE page_id IN (
    SELECT id FROM pages WHERE site_id = ?
) AND locale = ?
`

type DeletePageLocalesByLocaleParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) DeletePageLocalesByLocale(ctx context.Context, arg DeletePageLocalesByLocaleParams) error {
	_, err := q.db.ExecContext(ctx, deletePageLocalesByLocale, arg.SiteID, arg.Locale)
	return err
}

const getPageLocale = `-- name: GetPageLocale :one
SELECT page_id, locale, slug_override, title, meta_title, meta_description, status, created_at, updated_at FROM page_locales WHERE page_id = ? AND locale = ?
`

type GetPageLocaleParams struct {
	PageID string `json:"page_id"`
	Locale string `json:"locale"`
}

func (q *Queries) GetPageLocale(ctx context.Context, arg GetPageLocaleParams) (PageLocale, error) {
	row := q.db.QueryRowContext(ctx, getPageLocale, arg.PageID, arg.Locale)
	var i PageLocale
	err := row.Scan(
		&i.PageID,
		&i.Locale,
		&i.SlugOverride,
		&i.Title,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPageLocalesByPage = `-- name: ListPageLocalesByPage :many
SELECT page_id, locale, slug_override, title, meta_title, meta_description, status, created_at, updated_at FROM page_locales WHERE page_id = ? ORDER BY locale ASC
`

func (q *Queries) ListPageLocalesByPage(ctx context.Context, pageID string) ([]PageLocale, error) {
	rows, err := q.db.QueryContext(ctx, listPageLocalesByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageLocale{}
	for rows.Next() {
		var i PageLocale
		if err := rows.Scan(
			&i.PageID,
			&i.Locale,
			&i.SlugOverride,
			&i.Title,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageLocalesBySite = `-- name: ListPageLocalesBySite :many
SELECT pl.page_id, pl.locale, pl.slug_override, pl.title, pl.meta_title, pl.meta_description, pl.status, pl.created_at, pl.updated_at FROM page_locales pl
JOIN pages p ON p.id = pl.page_id
WHERE p.site_id = ?
ORDER BY p.slug ASC, pl.locale ASC
`

func (q *Queries) ListPageLocalesBySite(ctx context.Context, siteID string) ([]PageLocale, error) {
	rows, err := q.db.QueryContext(ctx, listPageLocalesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageLocale{}
	for rows.Next() {
		var i PageLocale
		if err := rows.Scan(
			&i.PageID,
			&i.Locale,
			&i.SlugOverride,
			&i.Title,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPageLocale = `-- name: UpsertPageLocale :exec
INSERT INTO page_locales (page_id, locale, slug_override, title, meta_title, meta_description, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(page_id, locale) DO UPDATE SET
    slug_override = excluded.slug_override,
    title = excluded.title,
    meta_title = excluded.meta_title,
    meta_description = excluded.meta_description,
    status = excluded.status,
    updated_at = datetime('now')
`

type UpsertPageLocaleParams struct {
	PageID          string `json:"page_id"`
	Locale          string `json:"locale"`
	SlugOverride    string `json:"slug_override"`
	Title           string `json:"title"`
	MetaTitle       string `json:"meta_title"`
	MetaDescription string `json:"meta_description"`
	Status          string `json:"status"`
}

func (q *Queries) UpsertPageLocale(ctx context.Context, arg UpsertPageLocaleParams) error {
	_, err := q.db.ExecContext(ctx, upsertPageLocale,
		arg.PageID,
		arg.Locale,
		arg.SlugOverride,
		arg.Title,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Status,
	)
	return err
}
