// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"
)

const countProductsBySite = `-- name: CountProductsBySite :one
SELECT CAST(COUNT(*) AS INTEGER) FROM products WHERE site_id = ?
`

func (q *Queries) CountProductsBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsBySite, siteID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, site_id, name, slug, description, category, status, images_json, base_price_cents, currency, requires_shipping, tax_class, weight_grams, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
	Name             string `json:"name"`
	Slug             string `json:"slug"`
	Description      string `json:"description"`
	Category         string `json:"category"`
	Status           string `json:"status"`
	ImagesJson       string `json:"images_json"`
	BasePriceCents   int64  `json:"base_price_cents"`
	Currency         string `json:"currency"`
	RequiresShipping int64  `json:"requires_shipping"`
	TaxClass         string `json:"tax_class"`
	WeightGrams      int64  `json:"weight_grams"`
	SortOrder        int64  `json:"sort_order"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.ImagesJson,
		arg.BasePriceCents,
		arg.Currency,
		arg.RequiresShipping,
		arg.TaxClass,
		arg.WeightGrams,
		arg.SortOrder,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ? AND site_id = ?
`

type DeleteProductParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.SiteID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, site_id, name, slug, description, category, status, images_json, base_price_cents, currency, requires_shipping, tax_class, weight_grams, sort_order, created_at, updated_at FROM products WHERE id = ? AND site_id = ?
`

type GetProductByIDParams struct {
	ID     string `json:"id"`
	SiteID string `json:"site_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, arg.ID, arg.SiteID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.ImagesJson,
		&i.BasePriceCents,
		&i.Currency,
		&i.RequiresShipping,
		&i.TaxClass,
		&i.WeightGrams,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, site_id, name, slug, description, category, status, images_json, base_price_cents, currency, requires_shipping, tax_class, weight_grams, sort_order, created_at, updated_at FROM products WHERE site_id = ? AND slug = ?
`

type GetProductBySlugParams struct {
	SiteID string `json:"site_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, arg.SiteID, arg.Slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.ImagesJson,
		&i.BasePriceCents,
		&i.Currency,
		&i.RequiresShipping,
		&i.TaxClass,
		&i.WeightGrams,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProductsBySite = `-- name: ListActiveProductsBySite :many
SELECT id, site_id, name, slug, description, category, status, images_json, base_price_cents, currency, requires_shipping, tax_class, weight_grams, sort_order, created_at, updated_at FROM products
WHERE site_id = ? AND status = 'active'
ORDER BY sort_order ASC, created_at DESC
LIMIT ?
`

type ListActiveProductsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListActiveProductsBySite(ctx context.Context, arg ListActiveProductsBySiteParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProductsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.ImagesJson,
			&i.BasePriceCents,
			&i.Currency,
			&i.RequiresShipping,
			&i.TaxClass,
			&i.WeightGrams,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySite = `-- name: ListProductsBySite :many
SELECT id, site_id, name, slug, description, category, status, images_json, base_price_cents, currency, requires_shipping, tax_class, weight_grams, sort_order, created_at, updated_at FROM products
WHERE site_id = ?
ORDER BY sort_order ASC, created_at DESC
LIMIT ?
`

type ListProductsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListProductsBySite(ctx context.Context, arg ListProductsBySiteParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.ImagesJson,
			&i.BasePriceCents,
			&i.Currency,
			&i.RequiresShipping,
			&i.TaxClass,
			&i.WeightGrams,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = ?,
    slug = ?,
    description = ?,
    category = ?,
    status = ?,
    images_json = ?,
    base_price_cents = ?,
    currency = ?,
    requires_shipping = ?,
    tax_class = ?,
    weight_grams = ?,
    sort_order = ?,
    updated_at = datetime('now')
WHERE id = ? AND site_id = ?
`

type UpdateProductParams struct {
	Name             string `json:"name"`
	Slug             string `json:"slug"`
	Description      string `json:"description"`
	Category         string `json:"category"`
	Status           string `json:"status"`
	ImagesJson       string `json:"images_json"`
	BasePriceCents   int64  `json:"base_price_cents"`
	Currency         string `json:"currency"`
	RequiresShipping int64  `json:"requires_shipping"`
	TaxClass         string `json:"tax_class"`
	WeightGrams      int64  `json:"weight_grams"`
	SortOrder        int64  `json:"sort_order"`
	ID               string `json:"id"`
	SiteID           string `json:"site_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.ImagesJson,
		arg.BasePriceCents,
		arg.Currency,
		arg.RequiresShipping,
		arg.TaxClass,
		arg.WeightGrams,
		arg.SortOrder,
		arg.ID,
		arg.SiteID,
	)
	return err
}
