// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	// Per-path engagement so the dashboard can show "users spend 2m12s on
	// /pricing but bounce at /blog/x in 8s". Capped at the busiest 10 paths.
	AvgEngagementByPath(ctx context.Context, arg AvgEngagementByPathParams) ([]AvgEngagementByPathRow, error)
	// Aggregate metrics across all engagement beacons in a window. NULL-safe
	// via COALESCE so an empty window returns zeros instead of NaN.
	AvgEngagementSince(ctx context.Context, arg AvgEngagementSinceParams) (AvgEngagementSinceRow, error)
	ClearDefaultDeployTargets(ctx context.Context, siteID string) error
	ClearMediaFolder(ctx context.Context, arg ClearMediaFolderParams) error
	// For every identified session, return its full path history ordered by ts.
	// The handler groups by session_id / fingerprint to assemble the journey.
	ConversionPathsForIdentified(ctx context.Context, arg ConversionPathsForIdentifiedParams) ([]ConversionPathsForIdentifiedRow, error)
	// Distinct fingerprints in the last N minutes (caller passes the cutoff
	// timestamp). Used for the "live now" widget.
	CountLiveVisitorsSince(ctx context.Context, arg CountLiveVisitorsSinceParams) (int64, error)
	CountMediaBySite(ctx context.Context, siteID string) (int64, error)
	CountMediaInFolder(ctx context.Context, arg CountMediaInFolderParams) (int64, error)
	CountPagesBySite(ctx context.Context, siteID string) (int64, error)
	CountUnfiledMedia(ctx context.Context, siteID string) (int64, error)
	CountUniqueVisitorsSince(ctx context.Context, arg CountUniqueVisitorsSinceParams) (int64, error)
	CountVisitsByPath(ctx context.Context, arg CountVisitsByPathParams) ([]CountVisitsByPathRow, error)
	CountVisitsBySite(ctx context.Context, arg CountVisitsBySiteParams) (int64, error)
	CreateAgentKey(ctx context.Context, arg CreateAgentKeyParams) error
	CreateAllowedScript(ctx context.Context, arg CreateAllowedScriptParams) error
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateCSSClass(ctx context.Context, arg CreateCSSClassParams) error
	CreateComponent(ctx context.Context, arg CreateComponentParams) error
	CreateDeployTarget(ctx context.Context, arg CreateDeployTargetParams) error
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error
	CreateDesignReference(ctx context.Context, arg CreateDesignReferenceParams) error
	CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) error
	CreateForm(ctx context.Context, arg CreateFormParams) error
	CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) error
	CreateGlobalBlock(ctx context.Context, arg CreateGlobalBlockParams) error
	CreateGuardrail(ctx context.Context, arg CreateGuardrailParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateKnowledgebaseEntry(ctx context.Context, arg CreateKnowledgebaseEntryParams) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) error
	CreateMediaFolder(ctx context.Context, arg CreateMediaFolderParams) error
	CreatePage(ctx context.Context, arg CreatePageParams) error
	CreateRedirect(ctx context.Context, arg CreateRedirectParams) error
	CreateSilo(ctx context.Context, arg CreateSiloParams) error
	CreateSite(ctx context.Context, arg CreateSiteParams) error
	CreateSiteFont(ctx context.Context, arg CreateSiteFontParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeactivateAgentKey(ctx context.Context, id string) error
	DeleteAgentKey(ctx context.Context, id string) error
	DeleteAllowedScript(ctx context.Context, id string) error
	DeleteBlock(ctx context.Context, id string) error
	DeleteBlocksByPage(ctx context.Context, pageID string) error
	DeleteCSSClass(ctx context.Context, id string) error
	DeleteComponent(ctx context.Context, id string) error
	DeleteDeployTarget(ctx context.Context, id string) error
	DeleteDeployment(ctx context.Context, id string) error
	DeleteDesignReference(ctx context.Context, arg DeleteDesignReferenceParams) error
	DeleteEvaluationsByBuild(ctx context.Context, buildID string) error
	DeleteForm(ctx context.Context, id string) error
	DeleteFormSubmission(ctx context.Context, id string) error
	DeleteGlobalBlock(ctx context.Context, id string) error
	DeleteGuardrail(ctx context.Context, id string) error
	DeleteInvite(ctx context.Context, id string) error
	DeleteKnowledgebaseEntry(ctx context.Context, id string) error
	DeleteMedia(ctx context.Context, id string) error
	DeleteMediaFolder(ctx context.Context, arg DeleteMediaFolderParams) error
	DeletePage(ctx context.Context, id string) error
	DeleteRedirect(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, id string) error
	DeleteSettingsByCategory(ctx context.Context, arg DeleteSettingsByCategoryParams) error
	DeleteSilo(ctx context.Context, id string) error
	DeleteSite(ctx context.Context, id string) error
	DeleteSiteFont(ctx context.Context, arg DeleteSiteFontParams) error
	DeleteUser(ctx context.Context, id string) error
	EnsureMediaFolder(ctx context.Context, arg EnsureMediaFolderParams) error
	GetAgentKeyByHash(ctx context.Context, keyHash string) (AgentKey, error)
	GetAgentKeyByID(ctx context.Context, id string) (AgentKey, error)
	GetBlockByID(ctx context.Context, id string) (Block, error)
	GetCSSClassByID(ctx context.Context, id string) (CssClass, error)
	GetCSSClassByName(ctx context.Context, arg GetCSSClassByNameParams) (CssClass, error)
	GetComponentByID(ctx context.Context, id string) (Component, error)
	GetComponentByName(ctx context.Context, arg GetComponentByNameParams) (Component, error)
	GetDeployTarget(ctx context.Context, id string) (DeployTarget, error)
	GetDeploymentByID(ctx context.Context, id string) (Deployment, error)
	GetDesignReference(ctx context.Context, arg GetDesignReferenceParams) (DesignReference, error)
	GetFormByID(ctx context.Context, id string) (Form, error)
	GetGlobalBlockByID(ctx context.Context, id string) (GlobalBlock, error)
	GetGuardrailByID(ctx context.Context, id string) (GuardrailRule, error)
	GetInviteByToken(ctx context.Context, token string) (Invite, error)
	GetKnowledgebaseByID(ctx context.Context, id string) (KnowledgebaseEntry, error)
	GetMediaByID(ctx context.Context, id string) (Medium, error)
	GetMediaFolder(ctx context.Context, arg GetMediaFolderParams) (MediaFolder, error)
	GetPageByID(ctx context.Context, id string) (Page, error)
	GetPageBySiteAndSlug(ctx context.Context, arg GetPageBySiteAndSlugParams) (Page, error)
	GetRedirectByPath(ctx context.Context, arg GetRedirectByPathParams) (Redirect, error)
	GetSessionByFingerprint(ctx context.Context, arg GetSessionByFingerprintParams) (VisitSession, error)
	GetSetting(ctx context.Context, arg GetSettingParams) (SiteSetting, error)
	GetSiloByID(ctx context.Context, id string) (SiteSilo, error)
	// Site architecture
	GetSiteArchitecture(ctx context.Context, siteID string) (SiteArchitecture, error)
	GetSiteByID(ctx context.Context, id string) (Site, error)
	GetSiteBySlug(ctx context.Context, slug string) (Site, error)
	GetSiteFont(ctx context.Context, arg GetSiteFontParams) (SiteFont, error)
	// Site profiles
	GetSiteProfile(ctx context.Context, siteID string) (SiteProfile, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetVisitorMetadataByFingerprint(ctx context.Context, arg GetVisitorMetadataByFingerprintParams) (VisitSession, error)
	IdentifyVisitSession(ctx context.Context, arg IdentifyVisitSessionParams) error
	IncrementTokenVersion(ctx context.Context, id string) error
	ListActiveGlobalBlocksBySite(ctx context.Context, siteID string) ([]GlobalBlock, error)
	ListActiveGuardrailsBySite(ctx context.Context, siteID string) ([]GuardrailRule, error)
	ListActiveKnowledgebaseBySite(ctx context.Context, siteID string) ([]KnowledgebaseEntry, error)
	ListAgentKeysBySite(ctx context.Context, siteID string) ([]ListAgentKeysBySiteRow, error)
	// Allowed scripts
	ListAllowedScriptsBySite(ctx context.Context, siteID string) ([]AllowedScript, error)
	ListBlocksByPage(ctx context.Context, pageID string) ([]Block, error)
	ListCSSClassesBySite(ctx context.Context, siteID string) ([]CssClass, error)
	ListComponentsBySite(ctx context.Context, siteID string) ([]Component, error)
	ListDeployTargetsBySite(ctx context.Context, siteID string) ([]DeployTarget, error)
	ListDeploymentsBySite(ctx context.Context, siteID string) ([]Deployment, error)
	ListDesignReferences(ctx context.Context, siteID string) ([]DesignReference, error)
	ListDistinctFontFamilies(ctx context.Context, siteID string) ([]string, error)
	// Evaluations
	ListEvaluationsByBuild(ctx context.Context, buildID string) ([]Evaluation, error)
	ListEvaluationsBySite(ctx context.Context, arg ListEvaluationsBySiteParams) ([]Evaluation, error)
	// Form submissions
	ListFormSubmissions(ctx context.Context, formID string) ([]FormSubmission, error)
	ListFormSubmissionsBySite(ctx context.Context, arg ListFormSubmissionsBySiteParams) ([]FormSubmission, error)
	// Forms
	ListFormsBySite(ctx context.Context, siteID string) ([]Form, error)
	ListGlobalBlocksBySite(ctx context.Context, siteID string) ([]GlobalBlock, error)
	ListGuardrailsBySite(ctx context.Context, siteID string) ([]GuardrailRule, error)
	ListIdentifiedSessions(ctx context.Context, arg ListIdentifiedSessionsParams) ([]VisitSession, error)
	ListKnowledgebaseBySite(ctx context.Context, siteID string) ([]KnowledgebaseEntry, error)
	ListMediaByIDs(ctx context.Context, ids []string) ([]Medium, error)
	ListMediaBySite(ctx context.Context, siteID string) ([]Medium, error)
	ListMediaBySitePaginated(ctx context.Context, arg ListMediaBySitePaginatedParams) ([]Medium, error)
	ListMediaFoldersBySite(ctx context.Context, siteID string) ([]MediaFolder, error)
	ListMediaInFolderPaginated(ctx context.Context, arg ListMediaInFolderPaginatedParams) ([]Medium, error)
	ListPagesBySite(ctx context.Context, siteID string) ([]Page, error)
	ListPendingInvites(ctx context.Context) ([]Invite, error)
	ListPublishedPagesBySite(ctx context.Context, siteID string) ([]Page, error)
	ListRecentDeploymentsBySite(ctx context.Context, arg ListRecentDeploymentsBySiteParams) ([]Deployment, error)
	ListRedirectsBySite(ctx context.Context, siteID string) ([]Redirect, error)
	ListSettingsByCategory(ctx context.Context, arg ListSettingsByCategoryParams) ([]SiteSetting, error)
	ListSettingsBySite(ctx context.Context, siteID string) ([]SiteSetting, error)
	// Silos
	ListSilosBySite(ctx context.Context, siteID string) ([]SiteSilo, error)
	ListSiteFonts(ctx context.Context, siteID string) ([]SiteFont, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListUnfiledMediaPaginated(ctx context.Context, arg ListUnfiledMediaPaginatedParams) ([]Medium, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVisitsBySite(ctx context.Context, arg ListVisitsBySiteParams) ([]VisitEvent, error)
	MarkInviteUsed(ctx context.Context, id string) error
	// Pageviews per UTC day for the requested window. Returned as ISO-date
	// buckets so the frontend can render a sparkline / bar chart directly.
	PageviewsTimeSeriesDaily(ctx context.Context, arg PageviewsTimeSeriesDailyParams) ([]PageviewsTimeSeriesDailyRow, error)
	// Pageviews per UTC hour for the last day window. Used when range = 1d.
	PageviewsTimeSeriesHourly(ctx context.Context, arg PageviewsTimeSeriesHourlyParams) ([]PageviewsTimeSeriesHourlyRow, error)
	RecordVisitEngagement(ctx context.Context, arg RecordVisitEngagementParams) error
	RecordVisitEvent(ctx context.Context, arg RecordVisitEventParams) error
	SetDeployTargetDefault(ctx context.Context, id string) error
	TopBrowsers(ctx context.Context, arg TopBrowsersParams) ([]TopBrowsersRow, error)
	TopCountries(ctx context.Context, arg TopCountriesParams) ([]TopCountriesRow, error)
	TopDevices(ctx context.Context, arg TopDevicesParams) ([]TopDevicesRow, error)
	TopLanguages(ctx context.Context, arg TopLanguagesParams) ([]TopLanguagesRow, error)
	TopOS(ctx context.Context, arg TopOSParams) ([]TopOSRow, error)
	TopReferers(ctx context.Context, arg TopReferersParams) ([]TopReferersRow, error)
	TopStatuses(ctx context.Context, arg TopStatusesParams) ([]TopStatusesRow, error)
	TopUTMCampaigns(ctx context.Context, arg TopUTMCampaignsParams) ([]TopUTMCampaignsRow, error)
	TopUTMSources(ctx context.Context, arg TopUTMSourcesParams) ([]TopUTMSourcesRow, error)
	// Group by 100px-bucketed viewport width so we don't get a long tail of
	// one-off sizes. ~16 buckets cover the realistic phone-to-4k range.
	TopViewports(ctx context.Context, arg TopViewportsParams) ([]TopViewportsRow, error)
	UpdateAgentKeyLastUsed(ctx context.Context, id string) error
	UpdateAllowedScript(ctx context.Context, arg UpdateAllowedScriptParams) error
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) error
	UpdateBlockOrder(ctx context.Context, arg UpdateBlockOrderParams) error
	UpdateCSSClass(ctx context.Context, arg UpdateCSSClassParams) error
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) error
	UpdateDeploymentDeployed(ctx context.Context, arg UpdateDeploymentDeployedParams) error
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
	UpdateDesignReferenceFetched(ctx context.Context, arg UpdateDesignReferenceFetchedParams) error
	UpdateForm(ctx context.Context, arg UpdateFormParams) error
	UpdateGlobalBlock(ctx context.Context, arg UpdateGlobalBlockParams) error
	UpdateGuardrail(ctx context.Context, arg UpdateGuardrailParams) error
	UpdateKnowledgebaseEntry(ctx context.Context, arg UpdateKnowledgebaseEntryParams) error
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) error
	UpdateMediaFolder(ctx context.Context, arg UpdateMediaFolderParams) error
	UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdatePageOrder(ctx context.Context, arg UpdatePageOrderParams) error
	UpdateRedirect(ctx context.Context, arg UpdateRedirectParams) error
	UpdateSilo(ctx context.Context, arg UpdateSiloParams) error
	UpdateSite(ctx context.Context, arg UpdateSiteParams) error
	UpdateSiteBuildStatus(ctx context.Context, arg UpdateSiteBuildStatusParams) error
	UpdateSiteDeployAt(ctx context.Context, arg UpdateSiteDeployAtParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertSiteArchitecture(ctx context.Context, arg UpsertSiteArchitectureParams) error
	UpsertSiteProfile(ctx context.Context, arg UpsertSiteProfileParams) error
	UpsertVisitSession(ctx context.Context, arg UpsertVisitSessionParams) error
	UpsertVisitorMetadataByFingerprint(ctx context.Context, arg UpsertVisitorMetadataByFingerprintParams) (int64, error)
	UpsertVisitorMetadataByVisitorID(ctx context.Context, arg UpsertVisitorMetadataByVisitorIDParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
