// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CountPagesBySite(ctx context.Context, siteID string) (int64, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateGlobalBlock(ctx context.Context, arg CreateGlobalBlockParams) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) error
	CreatePage(ctx context.Context, arg CreatePageParams) error
	CreateSite(ctx context.Context, arg CreateSiteParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteBlock(ctx context.Context, id string) error
	DeleteBlocksByPage(ctx context.Context, pageID string) error
	DeleteGlobalBlock(ctx context.Context, id string) error
	DeleteMedia(ctx context.Context, id string) error
	DeletePage(ctx context.Context, id string) error
	DeleteSite(ctx context.Context, id string) error
	GetBlockByID(ctx context.Context, id string) (Block, error)
	GetGlobalBlockByID(ctx context.Context, id string) (GlobalBlock, error)
	GetMediaByID(ctx context.Context, id string) (Medium, error)
	GetPageByID(ctx context.Context, id string) (Page, error)
	GetSiteByID(ctx context.Context, id string) (Site, error)
	GetSiteBySlug(ctx context.Context, slug string) (Site, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	IncrementTokenVersion(ctx context.Context, id string) error
	ListActiveGlobalBlocksBySite(ctx context.Context, siteID string) ([]GlobalBlock, error)
	ListBlocksByPage(ctx context.Context, pageID string) ([]Block, error)
	ListGlobalBlocksBySite(ctx context.Context, siteID string) ([]GlobalBlock, error)
	ListMediaByIDs(ctx context.Context, ids []string) ([]Medium, error)
	ListMediaBySite(ctx context.Context, siteID string) ([]Medium, error)
	ListPagesBySite(ctx context.Context, siteID string) ([]Page, error)
	ListPublishedPagesBySite(ctx context.Context, siteID string) ([]Page, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) error
	UpdateBlockOrder(ctx context.Context, arg UpdateBlockOrderParams) error
	UpdateGlobalBlock(ctx context.Context, arg UpdateGlobalBlockParams) error
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) error
	UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdatePageOrder(ctx context.Context, arg UpdatePageOrderParams) error
	UpdateSite(ctx context.Context, arg UpdateSiteParams) error
	UpdateSiteBuildStatus(ctx context.Context, arg UpdateSiteBuildStatusParams) error
	UpdateSiteDeployAt(ctx context.Context, arg UpdateSiteDeployAtParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
