package store

// Raw exposes the underlying DBTX for ad-hoc queries that sqlc cannot
// model statically (e.g. SQLite JSON1 virtual columns from json_each /
// json_tree). Callers should prefer named queries in queries/*.sql when
// possible; this is the escape hatch for cases sqlc rejects.
//
// Hand-written, NOT generated by sqlc. Lives outside *.sql.go so sqlc
// won't overwrite it on the next `sqlc generate`.
func (q *Queries) Raw() DBTX {
	return q.db
}
