// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redirects.sql

package store

import (
	"context"
)

const countRedirectsBySite = `-- name: CountRedirectsBySite :one
SELECT COUNT(*) FROM redirects WHERE site_id = ?
`

func (q *Queries) CountRedirectsBySite(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRedirectsBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvaluation = `-- name: CreateEvaluation :exec
INSERT INTO evaluations (id, build_id, site_id, category, score, max_score, grade, checks_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateEvaluationParams struct {
	ID         string `json:"id"`
	BuildID    string `json:"build_id"`
	SiteID     string `json:"site_id"`
	Category   string `json:"category"`
	Score      int64  `json:"score"`
	MaxScore   int64  `json:"max_score"`
	Grade      string `json:"grade"`
	ChecksJson string `json:"checks_json"`
}

func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) error {
	_, err := q.db.ExecContext(ctx, createEvaluation,
		arg.ID,
		arg.BuildID,
		arg.SiteID,
		arg.Category,
		arg.Score,
		arg.MaxScore,
		arg.Grade,
		arg.ChecksJson,
	)
	return err
}

const createForm = `-- name: CreateForm :exec
INSERT INTO forms (id, site_id, name, fields_json, action, action_config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateFormParams struct {
	ID           string `json:"id"`
	SiteID       string `json:"site_id"`
	Name         string `json:"name"`
	FieldsJson   string `json:"fields_json"`
	Action       string `json:"action"`
	ActionConfig string `json:"action_config"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) error {
	_, err := q.db.ExecContext(ctx, createForm,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.FieldsJson,
		arg.Action,
		arg.ActionConfig,
	)
	return err
}

const createFormSubmission = `-- name: CreateFormSubmission :exec
INSERT INTO form_submissions (id, form_id, site_id, data_json, ip_hash, created_at)
VALUES (?, ?, ?, ?, ?, datetime('now'))
`

type CreateFormSubmissionParams struct {
	ID       string `json:"id"`
	FormID   string `json:"form_id"`
	SiteID   string `json:"site_id"`
	DataJson string `json:"data_json"`
	IpHash   string `json:"ip_hash"`
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createFormSubmission,
		arg.ID,
		arg.FormID,
		arg.SiteID,
		arg.DataJson,
		arg.IpHash,
	)
	return err
}

const createRedirect = `-- name: CreateRedirect :exec
INSERT INTO redirects (id, site_id, from_path, to_path, status_code, is_auto, created_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateRedirectParams struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	FromPath   string `json:"from_path"`
	ToPath     string `json:"to_path"`
	StatusCode int64  `json:"status_code"`
	IsAuto     int64  `json:"is_auto"`
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) error {
	_, err := q.db.ExecContext(ctx, createRedirect,
		arg.ID,
		arg.SiteID,
		arg.FromPath,
		arg.ToPath,
		arg.StatusCode,
		arg.IsAuto,
	)
	return err
}

const deleteEvaluationsByBuild = `-- name: DeleteEvaluationsByBuild :exec
DELETE FROM evaluations WHERE build_id = ?
`

func (q *Queries) DeleteEvaluationsByBuild(ctx context.Context, buildID string) error {
	_, err := q.db.ExecContext(ctx, deleteEvaluationsByBuild, buildID)
	return err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = ?
`

func (q *Queries) DeleteForm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteForm, id)
	return err
}

const deleteFormSubmission = `-- name: DeleteFormSubmission :exec
DELETE FROM form_submissions WHERE id = ?
`

func (q *Queries) DeleteFormSubmission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFormSubmission, id)
	return err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM redirects WHERE id = ?
`

func (q *Queries) DeleteRedirect(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRedirect, id)
	return err
}

const getFormByID = `-- name: GetFormByID :one
SELECT id, site_id, name, fields_json, "action", action_config, created_at, updated_at FROM forms WHERE id = ?
`

func (q *Queries) GetFormByID(ctx context.Context, id string) (Form, error) {
	row := q.db.QueryRowContext(ctx, getFormByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.FieldsJson,
		&i.Action,
		&i.ActionConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedirectByID = `-- name: GetRedirectByID :one
SELECT id, site_id, from_path, to_path, status_code, is_auto, created_at FROM redirects WHERE id = ?
`

func (q *Queries) GetRedirectByID(ctx context.Context, id string) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, getRedirectByID, id)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.FromPath,
		&i.ToPath,
		&i.StatusCode,
		&i.IsAuto,
		&i.CreatedAt,
	)
	return i, err
}

const getRedirectByPath = `-- name: GetRedirectByPath :one
SELECT id, site_id, from_path, to_path, status_code, is_auto, created_at FROM redirects WHERE site_id = ? AND from_path = ?
`

type GetRedirectByPathParams struct {
	SiteID   string `json:"site_id"`
	FromPath string `json:"from_path"`
}

func (q *Queries) GetRedirectByPath(ctx context.Context, arg GetRedirectByPathParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, getRedirectByPath, arg.SiteID, arg.FromPath)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.FromPath,
		&i.ToPath,
		&i.StatusCode,
		&i.IsAuto,
		&i.CreatedAt,
	)
	return i, err
}

const listEvaluationsByBuild = `-- name: ListEvaluationsByBuild :many
SELECT id, build_id, site_id, category, score, max_score, grade, checks_json, created_at FROM evaluations WHERE build_id = ? ORDER BY category
`

// Evaluations
func (q *Queries) ListEvaluationsByBuild(ctx context.Context, buildID string) ([]Evaluation, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evaluation{}
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.SiteID,
			&i.Category,
			&i.Score,
			&i.MaxScore,
			&i.Grade,
			&i.ChecksJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationsBySite = `-- name: ListEvaluationsBySite :many
SELECT id, build_id, site_id, category, score, max_score, grade, checks_json, created_at FROM evaluations WHERE site_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListEvaluationsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListEvaluationsBySite(ctx context.Context, arg ListEvaluationsBySiteParams) ([]Evaluation, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evaluation{}
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.SiteID,
			&i.Category,
			&i.Score,
			&i.MaxScore,
			&i.Grade,
			&i.ChecksJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingRedirectFromPathsBySite = `-- name: ListExistingRedirectFromPathsBySite :many
SELECT from_path FROM redirects WHERE site_id = ?
`

// Sprint 4 (2026-05-06): mirror of ListExistingPageSlugsBySite.
func (q *Queries) ListExistingRedirectFromPathsBySite(ctx context.Context, siteID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExistingRedirectFromPathsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var from_path string
		if err := rows.Scan(&from_path); err != nil {
			return nil, err
		}
		items = append(items, from_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSubmissions = `-- name: ListFormSubmissions :many
SELECT id, form_id, site_id, data_json, ip_hash, created_at FROM form_submissions WHERE form_id = ? ORDER BY created_at DESC
`

// Form submissions
func (q *Queries) ListFormSubmissions(ctx context.Context, formID string) ([]FormSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listFormSubmissions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormSubmission{}
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SiteID,
			&i.DataJson,
			&i.IpHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSubmissionsBySite = `-- name: ListFormSubmissionsBySite :many
SELECT id, form_id, site_id, data_json, ip_hash, created_at FROM form_submissions WHERE site_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListFormSubmissionsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListFormSubmissionsBySite(ctx context.Context, arg ListFormSubmissionsBySiteParams) ([]FormSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listFormSubmissionsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormSubmission{}
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SiteID,
			&i.DataJson,
			&i.IpHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsBySite = `-- name: ListFormsBySite :many
SELECT id, site_id, name, fields_json, "action", action_config, created_at, updated_at FROM forms WHERE site_id = ? ORDER BY name
`

// Forms
func (q *Queries) ListFormsBySite(ctx context.Context, siteID string) ([]Form, error) {
	rows, err := q.db.QueryContext(ctx, listFormsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Form{}
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.FieldsJson,
			&i.Action,
			&i.ActionConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedirectsBySite = `-- name: ListRedirectsBySite :many
SELECT id, site_id, from_path, to_path, status_code, is_auto, created_at FROM redirects WHERE site_id = ? ORDER BY from_path
`

func (q *Queries) ListRedirectsBySite(ctx context.Context, siteID string) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, listRedirectsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Redirect{}
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.FromPath,
			&i.ToPath,
			&i.StatusCode,
			&i.IsAuto,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :exec
UPDATE forms
SET name = ?, fields_json = ?, action = ?, action_config = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateFormParams struct {
	Name         string `json:"name"`
	FieldsJson   string `json:"fields_json"`
	Action       string `json:"action"`
	ActionConfig string `json:"action_config"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) error {
	_, err := q.db.ExecContext(ctx, updateForm,
		arg.Name,
		arg.FieldsJson,
		arg.Action,
		arg.ActionConfig,
		arg.ID,
	)
	return err
}

const updateRedirect = `-- name: UpdateRedirect :exec
UPDATE redirects SET from_path = ?, to_path = ?, status_code = ? WHERE id = ?
`

type UpdateRedirectParams struct {
	FromPath   string `json:"from_path"`
	ToPath     string `json:"to_path"`
	StatusCode int64  `json:"status_code"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateRedirect(ctx context.Context, arg UpdateRedirectParams) error {
	_, err := q.db.ExecContext(ctx, updateRedirect,
		arg.FromPath,
		arg.ToPath,
		arg.StatusCode,
		arg.ID,
	)
	return err
}

const upsertRedirect = `-- name: UpsertRedirect :one
INSERT INTO redirects (id, site_id, from_path, to_path, status_code, is_auto, created_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(site_id, from_path) DO UPDATE SET
    to_path     = excluded.to_path,
    status_code = excluded.status_code,
    is_auto     = excluded.is_auto
RETURNING id, site_id, from_path, to_path, status_code, is_auto, created_at
`

type UpsertRedirectParams struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	FromPath   string `json:"from_path"`
	ToPath     string `json:"to_path"`
	StatusCode int64  `json:"status_code"`
	IsAuto     int64  `json:"is_auto"`
}

// Sprint 4 (2026-05-06): re-import upsert. ON CONFLICT(site_id, from_path)
// DO UPDATE leaves created_at alone and returns the existing row's id, so
// the porter detects insert-vs-update by comparing returned ID.
func (q *Queries) UpsertRedirect(ctx context.Context, arg UpsertRedirectParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, upsertRedirect,
		arg.ID,
		arg.SiteID,
		arg.FromPath,
		arg.ToPath,
		arg.StatusCode,
		arg.IsAuto,
	)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.FromPath,
		&i.ToPath,
		&i.StatusCode,
		&i.IsAuto,
		&i.CreatedAt,
	)
	return i, err
}
