// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_versions.sql

package store

import (
	"context"
)

const getMaxSchemaVersion = `-- name: GetMaxSchemaVersion :one
SELECT COALESCE(MAX(version), 0) FROM schema_versions
`

func (q *Queries) GetMaxSchemaVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSchemaVersion)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listSchemaVersions = `-- name: ListSchemaVersions :many
SELECT version, applied_at, note
FROM schema_versions
ORDER BY version ASC
`

func (q *Queries) ListSchemaVersions(ctx context.Context) ([]SchemaVersion, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaVersion{}
	for rows.Next() {
		var i SchemaVersion
		if err := rows.Scan(&i.Version, &i.AppliedAt, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSchemaVersion = `-- name: RecordSchemaVersion :exec
INSERT OR IGNORE INTO schema_versions (version, note) VALUES (?, ?)
`

type RecordSchemaVersionParams struct {
	Version int64  `json:"version"`
	Note    string `json:"note"`
}

func (q *Queries) RecordSchemaVersion(ctx context.Context, arg RecordSchemaVersionParams) error {
	_, err := q.db.ExecContext(ctx, recordSchemaVersion, arg.Version, arg.Note)
	return err
}
