// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shield.sql

package store

import (
	"context"
)

const countShieldTokensBySession = `-- name: CountShieldTokensBySession :one
SELECT COUNT(*) FROM shield_tokens WHERE session_id = ?
`

func (q *Queries) CountShieldTokensBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShieldTokensBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShieldSession = `-- name: CreateShieldSession :exec
INSERT INTO shield_sessions (id, expires_at)
VALUES (?, ?)
`

type CreateShieldSessionParams struct {
	ID        string `json:"id"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateShieldSession(ctx context.Context, arg CreateShieldSessionParams) error {
	_, err := q.db.ExecContext(ctx, createShieldSession, arg.ID, arg.ExpiresAt)
	return err
}

const createShieldToken = `-- name: CreateShieldToken :exec
INSERT INTO shield_tokens (token, session_id, kind, hint, ciphertext)
VALUES (?, ?, ?, ?, ?)
`

type CreateShieldTokenParams struct {
	Token      string `json:"token"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Hint       string `json:"hint"`
	Ciphertext string `json:"ciphertext"`
}

func (q *Queries) CreateShieldToken(ctx context.Context, arg CreateShieldTokenParams) error {
	_, err := q.db.ExecContext(ctx, createShieldToken,
		arg.Token,
		arg.SessionID,
		arg.Kind,
		arg.Hint,
		arg.Ciphertext,
	)
	return err
}

const deleteShieldSession = `-- name: DeleteShieldSession :exec
DELETE FROM shield_sessions WHERE id = ?
`

func (q *Queries) DeleteShieldSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShieldSession, id)
	return err
}

const getShieldSession = `-- name: GetShieldSession :one
SELECT id, created_at, last_seen, expires_at
FROM shield_sessions
WHERE id = ?
`

func (q *Queries) GetShieldSession(ctx context.Context, id string) (ShieldSession, error) {
	row := q.db.QueryRowContext(ctx, getShieldSession, id)
	var i ShieldSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSeen,
		&i.ExpiresAt,
	)
	return i, err
}

const getShieldToken = `-- name: GetShieldToken :one
SELECT token, session_id, kind, hint, ciphertext, created_at
FROM shield_tokens
WHERE token = ? AND session_id = ?
`

type GetShieldTokenParams struct {
	Token     string `json:"token"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetShieldToken(ctx context.Context, arg GetShieldTokenParams) (ShieldToken, error) {
	row := q.db.QueryRowContext(ctx, getShieldToken, arg.Token, arg.SessionID)
	var i ShieldToken
	err := row.Scan(
		&i.Token,
		&i.SessionID,
		&i.Kind,
		&i.Hint,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const listShieldTokensBySession = `-- name: ListShieldTokensBySession :many
SELECT token, kind, hint, created_at
FROM shield_tokens
WHERE session_id = ?
ORDER BY created_at
`

type ListShieldTokensBySessionRow struct {
	Token     string `json:"token"`
	Kind      string `json:"kind"`
	Hint      string `json:"hint"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListShieldTokensBySession(ctx context.Context, sessionID string) ([]ListShieldTokensBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listShieldTokensBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShieldTokensBySessionRow{}
	for rows.Next() {
		var i ListShieldTokensBySessionRow
		if err := rows.Scan(
			&i.Token,
			&i.Kind,
			&i.Hint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepExpiredShieldSessions = `-- name: SweepExpiredShieldSessions :exec
DELETE FROM shield_sessions WHERE expires_at < datetime('now')
`

func (q *Queries) SweepExpiredShieldSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, sweepExpiredShieldSessions)
	return err
}

const touchShieldSession = `-- name: TouchShieldSession :exec
UPDATE shield_sessions
SET last_seen = datetime('now'), expires_at = ?
WHERE id = ?
`

type TouchShieldSessionParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchShieldSession(ctx context.Context, arg TouchShieldSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchShieldSession, arg.ExpiresAt, arg.ID)
	return err
}
