// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package store

import (
	"context"
)

const createSite = `-- name: CreateSite :exec
INSERT INTO sites (id, name, slug, domain, primary_color, secondary_color, bg_color, text_color, font_heading, font_body, lang)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSiteParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
	Domain         string `json:"domain"`
	PrimaryColor   string `json:"primary_color"`
	SecondaryColor string `json:"secondary_color"`
	BgColor        string `json:"bg_color"`
	TextColor      string `json:"text_color"`
	FontHeading    string `json:"font_heading"`
	FontBody       string `json:"font_body"`
	Lang           string `json:"lang"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) error {
	_, err := q.db.ExecContext(ctx, createSite,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.BgColor,
		arg.TextColor,
		arg.FontHeading,
		arg.FontBody,
		arg.Lang,
	)
	return err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = ?
`

func (q *Queries) DeleteSite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, slug, domain, status, primary_color, secondary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, created_at, updated_at FROM sites WHERE id = ?
`

func (q *Queries) GetSiteByID(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Status,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.BgColor,
		&i.TextColor,
		&i.FontHeading,
		&i.FontBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageID,
		&i.FaviconID,
		&i.Ga4ID,
		&i.UmamiID,
		&i.UmamiUrl,
		&i.CookieproofDomain,
		&i.Lang,
		&i.LastBuildAt,
		&i.LastBuildStatus,
		&i.LastBuildError,
		&i.LastDeployAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, name, slug, domain, status, primary_color, secondary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, created_at, updated_at FROM sites WHERE slug = ?
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Status,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.BgColor,
		&i.TextColor,
		&i.FontHeading,
		&i.FontBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageID,
		&i.FaviconID,
		&i.Ga4ID,
		&i.UmamiID,
		&i.UmamiUrl,
		&i.CookieproofDomain,
		&i.Lang,
		&i.LastBuildAt,
		&i.LastBuildStatus,
		&i.LastBuildError,
		&i.LastDeployAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, name, slug, domain, status, primary_color, secondary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, created_at, updated_at FROM sites ORDER BY updated_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Domain,
			&i.Status,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.BgColor,
			&i.TextColor,
			&i.FontHeading,
			&i.FontBody,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.OgImageID,
			&i.FaviconID,
			&i.Ga4ID,
			&i.UmamiID,
			&i.UmamiUrl,
			&i.CookieproofDomain,
			&i.Lang,
			&i.LastBuildAt,
			&i.LastBuildStatus,
			&i.LastBuildError,
			&i.LastDeployAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    name = ?,
    slug = ?,
    domain = ?,
    status = ?,
    primary_color = ?,
    secondary_color = ?,
    bg_color = ?,
    text_color = ?,
    font_heading = ?,
    font_body = ?,
    meta_title = ?,
    meta_description = ?,
    og_image_id = ?,
    favicon_id = ?,
    ga4_id = ?,
    umami_id = ?,
    umami_url = ?,
    cookieproof_domain = ?,
    lang = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteParams struct {
	Name              string `json:"name"`
	Slug              string `json:"slug"`
	Domain            string `json:"domain"`
	Status            string `json:"status"`
	PrimaryColor      string `json:"primary_color"`
	SecondaryColor    string `json:"secondary_color"`
	BgColor           string `json:"bg_color"`
	TextColor         string `json:"text_color"`
	FontHeading       string `json:"font_heading"`
	FontBody          string `json:"font_body"`
	MetaTitle         string `json:"meta_title"`
	MetaDescription   string `json:"meta_description"`
	OgImageID         string `json:"og_image_id"`
	FaviconID         string `json:"favicon_id"`
	Ga4ID             string `json:"ga4_id"`
	UmamiID           string `json:"umami_id"`
	UmamiUrl          string `json:"umami_url"`
	CookieproofDomain string `json:"cookieproof_domain"`
	Lang              string `json:"lang"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.ExecContext(ctx, updateSite,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Status,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.BgColor,
		arg.TextColor,
		arg.FontHeading,
		arg.FontBody,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgImageID,
		arg.FaviconID,
		arg.Ga4ID,
		arg.UmamiID,
		arg.UmamiUrl,
		arg.CookieproofDomain,
		arg.Lang,
		arg.ID,
	)
	return err
}

const updateSiteBuildStatus = `-- name: UpdateSiteBuildStatus :exec
UPDATE sites SET
    last_build_at = ?,
    last_build_status = ?,
    last_build_error = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteBuildStatusParams struct {
	LastBuildAt     string `json:"last_build_at"`
	LastBuildStatus string `json:"last_build_status"`
	LastBuildError  string `json:"last_build_error"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSiteBuildStatus(ctx context.Context, arg UpdateSiteBuildStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteBuildStatus,
		arg.LastBuildAt,
		arg.LastBuildStatus,
		arg.LastBuildError,
		arg.ID,
	)
	return err
}

const updateSiteDeployAt = `-- name: UpdateSiteDeployAt :exec
UPDATE sites SET last_deploy_at = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteDeployAtParams struct {
	LastDeployAt string `json:"last_deploy_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSiteDeployAt(ctx context.Context, arg UpdateSiteDeployAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteDeployAt, arg.LastDeployAt, arg.ID)
	return err
}
