// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_locales.sql

package store

import (
	"context"
)

const clearDefaultSiteLocales = `-- name: ClearDefaultSiteLocales :exec
UPDATE site_locales SET is_default = 0, updated_at = datetime('now')
WHERE site_id = ? AND locale != ?
`

type ClearDefaultSiteLocalesParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) ClearDefaultSiteLocales(ctx context.Context, arg ClearDefaultSiteLocalesParams) error {
	_, err := q.db.ExecContext(ctx, clearDefaultSiteLocales, arg.SiteID, arg.Locale)
	return err
}

const countSiteLocales = `-- name: CountSiteLocales :one
SELECT COUNT(*) FROM site_locales WHERE site_id = ?
`

func (q *Queries) CountSiteLocales(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSiteLocales, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSiteLocale = `-- name: DeleteSiteLocale :exec
DELETE FROM site_locales WHERE site_id = ? AND locale = ?
`

type DeleteSiteLocaleParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) DeleteSiteLocale(ctx context.Context, arg DeleteSiteLocaleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSiteLocale, arg.SiteID, arg.Locale)
	return err
}

const getDefaultSiteLocale = `-- name: GetDefaultSiteLocale :one
SELECT site_id, locale, is_default, sort_order, created_at, updated_at FROM site_locales WHERE site_id = ? AND is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultSiteLocale(ctx context.Context, siteID string) (SiteLocale, error) {
	row := q.db.QueryRowContext(ctx, getDefaultSiteLocale, siteID)
	var i SiteLocale
	err := row.Scan(
		&i.SiteID,
		&i.Locale,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteLocale = `-- name: GetSiteLocale :one
SELECT site_id, locale, is_default, sort_order, created_at, updated_at FROM site_locales WHERE site_id = ? AND locale = ?
`

type GetSiteLocaleParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) GetSiteLocale(ctx context.Context, arg GetSiteLocaleParams) (SiteLocale, error) {
	row := q.db.QueryRowContext(ctx, getSiteLocale, arg.SiteID, arg.Locale)
	var i SiteLocale
	err := row.Scan(
		&i.SiteID,
		&i.Locale,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteLocales = `-- name: ListSiteLocales :many
SELECT site_id, locale, is_default, sort_order, created_at, updated_at FROM site_locales WHERE site_id = ? ORDER BY is_default DESC, sort_order ASC, locale ASC
`

func (q *Queries) ListSiteLocales(ctx context.Context, siteID string) ([]SiteLocale, error) {
	rows, err := q.db.QueryContext(ctx, listSiteLocales, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteLocale{}
	for rows.Next() {
		var i SiteLocale
		if err := rows.Scan(
			&i.SiteID,
			&i.Locale,
			&i.IsDefault,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultSiteLocale = `-- name: SetDefaultSiteLocale :exec
UPDATE site_locales SET is_default = 1, updated_at = datetime('now')
WHERE site_id = ? AND locale = ?
`

type SetDefaultSiteLocaleParams struct {
	SiteID string `json:"site_id"`
	Locale string `json:"locale"`
}

func (q *Queries) SetDefaultSiteLocale(ctx context.Context, arg SetDefaultSiteLocaleParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultSiteLocale, arg.SiteID, arg.Locale)
	return err
}

const upsertSiteLocale = `-- name: UpsertSiteLocale :exec
INSERT INTO site_locales (site_id, locale, is_default, sort_order)
VALUES (?, ?, ?, ?)
ON CONFLICT(site_id, locale) DO UPDATE SET
    is_default = excluded.is_default,
    sort_order = excluded.sort_order,
    updated_at = datetime('now')
`

type UpsertSiteLocaleParams struct {
	SiteID    string `json:"site_id"`
	Locale    string `json:"locale"`
	IsDefault int64  `json:"is_default"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpsertSiteLocale(ctx context.Context, arg UpsertSiteLocaleParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteLocale,
		arg.SiteID,
		arg.Locale,
		arg.IsDefault,
		arg.SortOrder,
	)
	return err
}
