// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_settings.sql

package store

import (
	"context"
)

const createAllowedScript = `-- name: CreateAllowedScript :exec
INSERT INTO allowed_scripts (id, site_id, domain, purpose, is_active, created_at)
VALUES (?, ?, ?, ?, 1, datetime('now'))
`

type CreateAllowedScriptParams struct {
	ID      string `json:"id"`
	SiteID  string `json:"site_id"`
	Domain  string `json:"domain"`
	Purpose string `json:"purpose"`
}

func (q *Queries) CreateAllowedScript(ctx context.Context, arg CreateAllowedScriptParams) error {
	_, err := q.db.ExecContext(ctx, createAllowedScript,
		arg.ID,
		arg.SiteID,
		arg.Domain,
		arg.Purpose,
	)
	return err
}

const createSilo = `-- name: CreateSilo :exec
INSERT INTO site_silos (id, site_id, name, slug_prefix, silo_type, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateSiloParams struct {
	ID         string `json:"id"`
	SiteID     string `json:"site_id"`
	Name       string `json:"name"`
	SlugPrefix string `json:"slug_prefix"`
	SiloType   string `json:"silo_type"`
	SortOrder  int64  `json:"sort_order"`
}

func (q *Queries) CreateSilo(ctx context.Context, arg CreateSiloParams) error {
	_, err := q.db.ExecContext(ctx, createSilo,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.SlugPrefix,
		arg.SiloType,
		arg.SortOrder,
	)
	return err
}

const deleteAllowedScript = `-- name: DeleteAllowedScript :exec
DELETE FROM allowed_scripts WHERE id = ?
`

func (q *Queries) DeleteAllowedScript(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAllowedScript, id)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM site_settings WHERE id = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, id)
	return err
}

const deleteSettingsByCategory = `-- name: DeleteSettingsByCategory :exec
DELETE FROM site_settings WHERE site_id = ? AND category = ?
`

type DeleteSettingsByCategoryParams struct {
	SiteID   string `json:"site_id"`
	Category string `json:"category"`
}

func (q *Queries) DeleteSettingsByCategory(ctx context.Context, arg DeleteSettingsByCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteSettingsByCategory, arg.SiteID, arg.Category)
	return err
}

const deleteSilo = `-- name: DeleteSilo :exec
DELETE FROM site_silos WHERE id = ?
`

func (q *Queries) DeleteSilo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSilo, id)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT id, site_id, category, "key", value, updated_at FROM site_settings WHERE site_id = ? AND category = ? AND key = ?
`

type GetSettingParams struct {
	SiteID   string `json:"site_id"`
	Category string `json:"category"`
	Key      string `json:"key"`
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.SiteID, arg.Category, arg.Key)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiloByID = `-- name: GetSiloByID :one
SELECT id, site_id, name, slug_prefix, silo_type, sort_order, created_at FROM site_silos WHERE id = ?
`

func (q *Queries) GetSiloByID(ctx context.Context, id string) (SiteSilo, error) {
	row := q.db.QueryRowContext(ctx, getSiloByID, id)
	var i SiteSilo
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.SlugPrefix,
		&i.SiloType,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteArchitecture = `-- name: GetSiteArchitecture :one
SELECT id, site_id, structure_type, max_depth, created_at, updated_at FROM site_architecture WHERE site_id = ?
`

// Site architecture
func (q *Queries) GetSiteArchitecture(ctx context.Context, siteID string) (SiteArchitecture, error) {
	row := q.db.QueryRowContext(ctx, getSiteArchitecture, siteID)
	var i SiteArchitecture
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.StructureType,
		&i.MaxDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteProfile = `-- name: GetSiteProfile :one
SELECT id, site_id, business_name, registration_nr, country, contact_email, contact_phone, privacy_email, security_email, address_line1, address_line2, city, postal_code, created_at, updated_at FROM site_profiles WHERE site_id = ?
`

// Site profiles
func (q *Queries) GetSiteProfile(ctx context.Context, siteID string) (SiteProfile, error) {
	row := q.db.QueryRowContext(ctx, getSiteProfile, siteID)
	var i SiteProfile
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BusinessName,
		&i.RegistrationNr,
		&i.Country,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.PrivacyEmail,
		&i.SecurityEmail,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.PostalCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllowedScriptsBySite = `-- name: ListAllowedScriptsBySite :many
SELECT id, site_id, domain, purpose, is_active, created_at FROM allowed_scripts WHERE site_id = ? ORDER BY domain
`

// Allowed scripts
func (q *Queries) ListAllowedScriptsBySite(ctx context.Context, siteID string) ([]AllowedScript, error) {
	rows, err := q.db.QueryContext(ctx, listAllowedScriptsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllowedScript{}
	for rows.Next() {
		var i AllowedScript
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Domain,
			&i.Purpose,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsByCategory = `-- name: ListSettingsByCategory :many
SELECT id, site_id, category, "key", value, updated_at FROM site_settings WHERE site_id = ? AND category = ? ORDER BY key
`

type ListSettingsByCategoryParams struct {
	SiteID   string `json:"site_id"`
	Category string `json:"category"`
}

func (q *Queries) ListSettingsByCategory(ctx context.Context, arg ListSettingsByCategoryParams) ([]SiteSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsByCategory, arg.SiteID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsBySite = `-- name: ListSettingsBySite :many
SELECT id, site_id, category, "key", value, updated_at FROM site_settings WHERE site_id = ? ORDER BY category, key
`

func (q *Queries) ListSettingsBySite(ctx context.Context, siteID string) ([]SiteSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSilosBySite = `-- name: ListSilosBySite :many
SELECT id, site_id, name, slug_prefix, silo_type, sort_order, created_at FROM site_silos WHERE site_id = ? ORDER BY sort_order
`

// Silos
func (q *Queries) ListSilosBySite(ctx context.Context, siteID string) ([]SiteSilo, error) {
	rows, err := q.db.QueryContext(ctx, listSilosBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSilo{}
	for rows.Next() {
		var i SiteSilo
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.SlugPrefix,
			&i.SiloType,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAllowedScript = `-- name: UpdateAllowedScript :exec
UPDATE allowed_scripts SET domain = ?, purpose = ?, is_active = ? WHERE id = ?
`

type UpdateAllowedScriptParams struct {
	Domain   string `json:"domain"`
	Purpose  string `json:"purpose"`
	IsActive int64  `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateAllowedScript(ctx context.Context, arg UpdateAllowedScriptParams) error {
	_, err := q.db.ExecContext(ctx, updateAllowedScript,
		arg.Domain,
		arg.Purpose,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateSilo = `-- name: UpdateSilo :exec
UPDATE site_silos SET name = ?, slug_prefix = ?, silo_type = ?, sort_order = ? WHERE id = ?
`

type UpdateSiloParams struct {
	Name       string `json:"name"`
	SlugPrefix string `json:"slug_prefix"`
	SiloType   string `json:"silo_type"`
	SortOrder  int64  `json:"sort_order"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSilo(ctx context.Context, arg UpdateSiloParams) error {
	_, err := q.db.ExecContext(ctx, updateSilo,
		arg.Name,
		arg.SlugPrefix,
		arg.SiloType,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO site_settings (id, site_id, category, key, value, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(site_id, category, key) DO UPDATE SET value = excluded.value, updated_at = datetime('now')
`

type UpsertSettingParams struct {
	ID       string `json:"id"`
	SiteID   string `json:"site_id"`
	Category string `json:"category"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.ID,
		arg.SiteID,
		arg.Category,
		arg.Key,
		arg.Value,
	)
	return err
}

const upsertSiteArchitecture = `-- name: UpsertSiteArchitecture :exec
INSERT INTO site_architecture (id, site_id, structure_type, max_depth, created_at, updated_at)
VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT(site_id) DO UPDATE SET
    structure_type = excluded.structure_type,
    max_depth = excluded.max_depth,
    updated_at = datetime('now')
`

type UpsertSiteArchitectureParams struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	StructureType string `json:"structure_type"`
	MaxDepth      int64  `json:"max_depth"`
}

func (q *Queries) UpsertSiteArchitecture(ctx context.Context, arg UpsertSiteArchitectureParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteArchitecture,
		arg.ID,
		arg.SiteID,
		arg.StructureType,
		arg.MaxDepth,
	)
	return err
}

const upsertSiteProfile = `-- name: UpsertSiteProfile :exec
INSERT INTO site_profiles (id, site_id, business_name, registration_nr, country, contact_email, contact_phone, privacy_email, security_email, address_line1, address_line2, city, postal_code, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT(site_id) DO UPDATE SET
    business_name = excluded.business_name,
    registration_nr = excluded.registration_nr,
    country = excluded.country,
    contact_email = excluded.contact_email,
    contact_phone = excluded.contact_phone,
    privacy_email = excluded.privacy_email,
    security_email = excluded.security_email,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    postal_code = excluded.postal_code,
    updated_at = datetime('now')
`

type UpsertSiteProfileParams struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	BusinessName   string `json:"business_name"`
	RegistrationNr string `json:"registration_nr"`
	Country        string `json:"country"`
	ContactEmail   string `json:"contact_email"`
	ContactPhone   string `json:"contact_phone"`
	PrivacyEmail   string `json:"privacy_email"`
	SecurityEmail  string `json:"security_email"`
	AddressLine1   string `json:"address_line1"`
	AddressLine2   string `json:"address_line2"`
	City           string `json:"city"`
	PostalCode     string `json:"postal_code"`
}

func (q *Queries) UpsertSiteProfile(ctx context.Context, arg UpsertSiteProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertSiteProfile,
		arg.ID,
		arg.SiteID,
		arg.BusinessName,
		arg.RegistrationNr,
		arg.Country,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.PrivacyEmail,
		arg.SecurityEmail,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.PostalCode,
	)
	return err
}
