// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package store

import (
	"context"
)

const createSite = `-- name: CreateSite :exec
INSERT INTO sites (id, workspace_id, name, slug, domain, primary_color, secondary_color, bg_color, text_color, font_heading, font_body, lang)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSiteParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
	Domain         string `json:"domain"`
	PrimaryColor   string `json:"primary_color"`
	SecondaryColor string `json:"secondary_color"`
	BgColor        string `json:"bg_color"`
	TextColor      string `json:"text_color"`
	FontHeading    string `json:"font_heading"`
	FontBody       string `json:"font_body"`
	Lang           string `json:"lang"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) error {
	_, err := q.db.ExecContext(ctx, createSite,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.BgColor,
		arg.TextColor,
		arg.FontHeading,
		arg.FontBody,
		arg.Lang,
	)
	return err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = ?
`

func (q *Queries) DeleteSite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, workspace_id, name, slug, domain, status, primary_color, secondary_color, surface_color, border_color, muted_color, accent_color, on_primary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, storage_quota_bytes, build_minutes_quota, quota_overage_blocked, created_at, updated_at FROM sites WHERE id = ?
`

func (q *Queries) GetSiteByID(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Status,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.SurfaceColor,
		&i.BorderColor,
		&i.MutedColor,
		&i.AccentColor,
		&i.OnPrimaryColor,
		&i.BgColor,
		&i.TextColor,
		&i.FontHeading,
		&i.FontBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageID,
		&i.FaviconID,
		&i.Ga4ID,
		&i.UmamiID,
		&i.UmamiUrl,
		&i.CookieproofDomain,
		&i.Lang,
		&i.LastBuildAt,
		&i.LastBuildStatus,
		&i.LastBuildError,
		&i.LastDeployAt,
		&i.StorageQuotaBytes,
		&i.BuildMinutesQuota,
		&i.QuotaOverageBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, workspace_id, name, slug, domain, status, primary_color, secondary_color, surface_color, border_color, muted_color, accent_color, on_primary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, storage_quota_bytes, build_minutes_quota, quota_overage_blocked, created_at, updated_at FROM sites WHERE slug = ?
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Status,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.SurfaceColor,
		&i.BorderColor,
		&i.MutedColor,
		&i.AccentColor,
		&i.OnPrimaryColor,
		&i.BgColor,
		&i.TextColor,
		&i.FontHeading,
		&i.FontBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageID,
		&i.FaviconID,
		&i.Ga4ID,
		&i.UmamiID,
		&i.UmamiUrl,
		&i.CookieproofDomain,
		&i.Lang,
		&i.LastBuildAt,
		&i.LastBuildStatus,
		&i.LastBuildError,
		&i.LastDeployAt,
		&i.StorageQuotaBytes,
		&i.BuildMinutesQuota,
		&i.QuotaOverageBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteQuota = `-- name: GetSiteQuota :one
SELECT storage_quota_bytes, build_minutes_quota, quota_overage_blocked FROM sites WHERE id = ?
`

type GetSiteQuotaRow struct {
	StorageQuotaBytes   int64 `json:"storage_quota_bytes"`
	BuildMinutesQuota   int64 `json:"build_minutes_quota"`
	QuotaOverageBlocked int64 `json:"quota_overage_blocked"`
}

func (q *Queries) GetSiteQuota(ctx context.Context, id string) (GetSiteQuotaRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteQuota, id)
	var i GetSiteQuotaRow
	err := row.Scan(&i.StorageQuotaBytes, &i.BuildMinutesQuota, &i.QuotaOverageBlocked)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, workspace_id, name, slug, domain, status, primary_color, secondary_color, surface_color, border_color, muted_color, accent_color, on_primary_color, bg_color, text_color, font_heading, font_body, meta_title, meta_description, og_image_id, favicon_id, ga4_id, umami_id, umami_url, cookieproof_domain, lang, last_build_at, last_build_status, last_build_error, last_deploy_at, storage_quota_bytes, build_minutes_quota, quota_overage_blocked, created_at, updated_at FROM sites ORDER BY updated_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Domain,
			&i.Status,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.SurfaceColor,
			&i.BorderColor,
			&i.MutedColor,
			&i.AccentColor,
			&i.OnPrimaryColor,
			&i.BgColor,
			&i.TextColor,
			&i.FontHeading,
			&i.FontBody,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.OgImageID,
			&i.FaviconID,
			&i.Ga4ID,
			&i.UmamiID,
			&i.UmamiUrl,
			&i.CookieproofDomain,
			&i.Lang,
			&i.LastBuildAt,
			&i.LastBuildStatus,
			&i.LastBuildError,
			&i.LastDeployAt,
			&i.StorageQuotaBytes,
			&i.BuildMinutesQuota,
			&i.QuotaOverageBlocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesForQuotaAudit = `-- name: ListSitesForQuotaAudit :many
SELECT id, name, slug, storage_quota_bytes, build_minutes_quota, quota_overage_blocked
FROM sites
ORDER BY updated_at DESC
`

type ListSitesForQuotaAuditRow struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Slug                string `json:"slug"`
	StorageQuotaBytes   int64  `json:"storage_quota_bytes"`
	BuildMinutesQuota   int64  `json:"build_minutes_quota"`
	QuotaOverageBlocked int64  `json:"quota_overage_blocked"`
}

func (q *Queries) ListSitesForQuotaAudit(ctx context.Context) ([]ListSitesForQuotaAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listSitesForQuotaAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesForQuotaAuditRow{}
	for rows.Next() {
		var i ListSitesForQuotaAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.StorageQuotaBytes,
			&i.BuildMinutesQuota,
			&i.QuotaOverageBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumBuildMinutesBySiteSinceCutoff = `-- name: SumBuildMinutesBySiteSinceCutoff :one
SELECT COALESCE(SUM(duration_ms), 0) AS duration_ms_total
FROM deployments
WHERE site_id = ? AND created_at >= ?
`

type SumBuildMinutesBySiteSinceCutoffParams struct {
	SiteID    string `json:"site_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) SumBuildMinutesBySiteSinceCutoff(ctx context.Context, arg SumBuildMinutesBySiteSinceCutoffParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumBuildMinutesBySiteSinceCutoff, arg.SiteID, arg.CreatedAt)
	var duration_ms_total interface{}
	err := row.Scan(&duration_ms_total)
	return duration_ms_total, err
}

const sumStorageBytesBySite = `-- name: SumStorageBytesBySite :one
SELECT COALESCE(SUM(file_size), 0) AS bytes FROM media WHERE site_id = ?
`

func (q *Queries) SumStorageBytesBySite(ctx context.Context, siteID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumStorageBytesBySite, siteID)
	var bytes interface{}
	err := row.Scan(&bytes)
	return bytes, err
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    name = ?,
    slug = ?,
    domain = ?,
    status = ?,
    primary_color = ?,
    secondary_color = ?,
    bg_color = ?,
    text_color = ?,
    surface_color = ?,
    border_color = ?,
    muted_color = ?,
    accent_color = ?,
    on_primary_color = ?,
    font_heading = ?,
    font_body = ?,
    meta_title = ?,
    meta_description = ?,
    og_image_id = ?,
    favicon_id = ?,
    ga4_id = ?,
    umami_id = ?,
    umami_url = ?,
    cookieproof_domain = ?,
    lang = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteParams struct {
	Name              string `json:"name"`
	Slug              string `json:"slug"`
	Domain            string `json:"domain"`
	Status            string `json:"status"`
	PrimaryColor      string `json:"primary_color"`
	SecondaryColor    string `json:"secondary_color"`
	BgColor           string `json:"bg_color"`
	TextColor         string `json:"text_color"`
	SurfaceColor      string `json:"surface_color"`
	BorderColor       string `json:"border_color"`
	MutedColor        string `json:"muted_color"`
	AccentColor       string `json:"accent_color"`
	OnPrimaryColor    string `json:"on_primary_color"`
	FontHeading       string `json:"font_heading"`
	FontBody          string `json:"font_body"`
	MetaTitle         string `json:"meta_title"`
	MetaDescription   string `json:"meta_description"`
	OgImageID         string `json:"og_image_id"`
	FaviconID         string `json:"favicon_id"`
	Ga4ID             string `json:"ga4_id"`
	UmamiID           string `json:"umami_id"`
	UmamiUrl          string `json:"umami_url"`
	CookieproofDomain string `json:"cookieproof_domain"`
	Lang              string `json:"lang"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.ExecContext(ctx, updateSite,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Status,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.BgColor,
		arg.TextColor,
		arg.SurfaceColor,
		arg.BorderColor,
		arg.MutedColor,
		arg.AccentColor,
		arg.OnPrimaryColor,
		arg.FontHeading,
		arg.FontBody,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgImageID,
		arg.FaviconID,
		arg.Ga4ID,
		arg.UmamiID,
		arg.UmamiUrl,
		arg.CookieproofDomain,
		arg.Lang,
		arg.ID,
	)
	return err
}

const updateSiteBuildStatus = `-- name: UpdateSiteBuildStatus :exec
UPDATE sites SET
    last_build_at = ?,
    last_build_status = ?,
    last_build_error = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteBuildStatusParams struct {
	LastBuildAt     string `json:"last_build_at"`
	LastBuildStatus string `json:"last_build_status"`
	LastBuildError  string `json:"last_build_error"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSiteBuildStatus(ctx context.Context, arg UpdateSiteBuildStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteBuildStatus,
		arg.LastBuildAt,
		arg.LastBuildStatus,
		arg.LastBuildError,
		arg.ID,
	)
	return err
}

const updateSiteDeployAt = `-- name: UpdateSiteDeployAt :exec
UPDATE sites SET last_deploy_at = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteDeployAtParams struct {
	LastDeployAt string `json:"last_deploy_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSiteDeployAt(ctx context.Context, arg UpdateSiteDeployAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteDeployAt, arg.LastDeployAt, arg.ID)
	return err
}

const updateSiteQuota = `-- name: UpdateSiteQuota :exec
UPDATE sites
SET storage_quota_bytes = ?, build_minutes_quota = ?, quota_overage_blocked = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateSiteQuotaParams struct {
	StorageQuotaBytes   int64  `json:"storage_quota_bytes"`
	BuildMinutesQuota   int64  `json:"build_minutes_quota"`
	QuotaOverageBlocked int64  `json:"quota_overage_blocked"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateSiteQuota(ctx context.Context, arg UpdateSiteQuotaParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteQuota,
		arg.StorageQuotaBytes,
		arg.BuildMinutesQuota,
		arg.QuotaOverageBlocked,
		arg.ID,
	)
	return err
}
