// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package store

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (id, workspace_id, provider, external_id, external_customer_id,
                           plan, status, amount_cents, currency, interval_unit, interval_count,
                           current_period_end, cancel_at, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSubscriptionParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	Provider           string `json:"provider"`
	ExternalID         string `json:"external_id"`
	ExternalCustomerID string `json:"external_customer_id"`
	Plan               string `json:"plan"`
	Status             string `json:"status"`
	AmountCents        int64  `json:"amount_cents"`
	Currency           string `json:"currency"`
	IntervalUnit       string `json:"interval_unit"`
	IntervalCount      int64  `json:"interval_count"`
	CurrentPeriodEnd   string `json:"current_period_end"`
	CancelAt           string `json:"cancel_at"`
	MetadataJson       string `json:"metadata_json"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.ExternalID,
		arg.ExternalCustomerID,
		arg.Plan,
		arg.Status,
		arg.AmountCents,
		arg.Currency,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.CurrentPeriodEnd,
		arg.CancelAt,
		arg.MetadataJson,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByExternalID = `-- name: GetSubscriptionByExternalID :one
SELECT id, workspace_id, provider, external_id, external_customer_id,
       plan, status, amount_cents, currency, interval_unit, interval_count,
       current_period_end, cancel_at, metadata_json, created_at, updated_at
FROM subscriptions WHERE external_id = ?
`

func (q *Queries) GetSubscriptionByExternalID(ctx context.Context, externalID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByExternalID, externalID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.ExternalCustomerID,
		&i.Plan,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.CurrentPeriodEnd,
		&i.CancelAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, workspace_id, provider, external_id, external_customer_id,
       plan, status, amount_cents, currency, interval_unit, interval_count,
       current_period_end, cancel_at, metadata_json, created_at, updated_at
FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.ExternalCustomerID,
		&i.Plan,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.CurrentPeriodEnd,
		&i.CancelAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByWorkspace = `-- name: GetSubscriptionByWorkspace :one
SELECT id, workspace_id, provider, external_id, external_customer_id,
       plan, status, amount_cents, currency, interval_unit, interval_count,
       current_period_end, cancel_at, metadata_json, created_at, updated_at
FROM subscriptions
WHERE workspace_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSubscriptionByWorkspace(ctx context.Context, workspaceID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByWorkspace, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.ExternalCustomerID,
		&i.Plan,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.CurrentPeriodEnd,
		&i.CancelAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsBySite = `-- name: ListSubscriptionsBySite :many
SELECT id, workspace_id, provider, external_id, external_customer_id,
       plan, status, amount_cents, currency, interval_unit, interval_count,
       current_period_end, cancel_at, metadata_json, created_at, updated_at
FROM subscriptions
ORDER BY created_at DESC
LIMIT 1000
`

func (q *Queries) ListSubscriptionsBySite(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsBySite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ExternalID,
			&i.ExternalCustomerID,
			&i.Plan,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.CurrentPeriodEnd,
			&i.CancelAt,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionExternal = `-- name: UpdateSubscriptionExternal :exec
UPDATE subscriptions
SET external_id = ?, external_customer_id = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateSubscriptionExternalParams struct {
	ExternalID         string `json:"external_id"`
	ExternalCustomerID string `json:"external_customer_id"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateSubscriptionExternal(ctx context.Context, arg UpdateSubscriptionExternalParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionExternal, arg.ExternalID, arg.ExternalCustomerID, arg.ID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = ?, current_period_end = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateSubscriptionStatusParams struct {
	Status           string `json:"status"`
	CurrentPeriodEnd string `json:"current_period_end"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.Status, arg.CurrentPeriodEnd, arg.ID)
	return err
}
