// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visit_events.sql

package store

import (
	"context"
)

const countVisitsByPath = `-- name: CountVisitsByPath :many
SELECT path, COUNT(*) AS count FROM visit_events
WHERE site_id = ? AND ts >= ?
GROUP BY path
ORDER BY count DESC
`

type CountVisitsByPathParams struct {
	SiteID string `json:"site_id"`
	Ts     string `json:"ts"`
}

type CountVisitsByPathRow struct {
	Path  string `json:"path"`
	Count int64  `json:"count"`
}

func (q *Queries) CountVisitsByPath(ctx context.Context, arg CountVisitsByPathParams) ([]CountVisitsByPathRow, error) {
	rows, err := q.db.QueryContext(ctx, countVisitsByPath, arg.SiteID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountVisitsByPathRow{}
	for rows.Next() {
		var i CountVisitsByPathRow
		if err := rows.Scan(&i.Path, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countVisitsBySite = `-- name: CountVisitsBySite :one
SELECT COUNT(*) FROM visit_events
WHERE site_id = ? AND ts >= ?
`

type CountVisitsBySiteParams struct {
	SiteID string `json:"site_id"`
	Ts     string `json:"ts"`
}

func (q *Queries) CountVisitsBySite(ctx context.Context, arg CountVisitsBySiteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisitsBySite, arg.SiteID, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listVisitsBySite = `-- name: ListVisitsBySite :many
SELECT id, site_id, fingerprint, session_id, path, referer, status, ms, ts FROM visit_events
WHERE site_id = ?
ORDER BY ts DESC
LIMIT ? OFFSET ?
`

type ListVisitsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListVisitsBySite(ctx context.Context, arg ListVisitsBySiteParams) ([]VisitEvent, error) {
	rows, err := q.db.QueryContext(ctx, listVisitsBySite, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisitEvent{}
	for rows.Next() {
		var i VisitEvent
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Fingerprint,
			&i.SessionID,
			&i.Path,
			&i.Referer,
			&i.Status,
			&i.Ms,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVisitEvent = `-- name: RecordVisitEvent :exec
INSERT INTO visit_events (id, site_id, fingerprint, session_id, path, referer, status, ms, ts)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordVisitEventParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
	SessionID   string `json:"session_id"`
	Path        string `json:"path"`
	Referer     string `json:"referer"`
	Status      int64  `json:"status"`
	Ms          int64  `json:"ms"`
	Ts          string `json:"ts"`
}

func (q *Queries) RecordVisitEvent(ctx context.Context, arg RecordVisitEventParams) error {
	_, err := q.db.ExecContext(ctx, recordVisitEvent,
		arg.ID,
		arg.SiteID,
		arg.Fingerprint,
		arg.SessionID,
		arg.Path,
		arg.Referer,
		arg.Status,
		arg.Ms,
		arg.Ts,
	)
	return err
}

const topReferers = `-- name: TopReferers :many
SELECT referer, COUNT(*) AS count FROM visit_events
WHERE site_id = ? AND ts >= ? AND referer != ''
GROUP BY referer
ORDER BY count DESC
LIMIT ?
`

type TopReferersParams struct {
	SiteID string `json:"site_id"`
	Ts     string `json:"ts"`
	Limit  int64  `json:"limit"`
}

type TopReferersRow struct {
	Referer string `json:"referer"`
	Count   int64  `json:"count"`
}

func (q *Queries) TopReferers(ctx context.Context, arg TopReferersParams) ([]TopReferersRow, error) {
	rows, err := q.db.QueryContext(ctx, topReferers, arg.SiteID, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopReferersRow{}
	for rows.Next() {
		var i TopReferersRow
		if err := rows.Scan(&i.Referer, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
