// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visit_sessions.sql

package store

import (
	"context"
)

const getSessionByFingerprint = `-- name: GetSessionByFingerprint :one
SELECT id, site_id, fingerprint, visitor_id, email, consent_method, consent_categories_json, started_at, last_seen_at, page_count, identified_at, metadata_json, metadata_expires_at, identity_confirmed_at FROM visit_sessions
WHERE site_id = ? AND fingerprint = ?
`

type GetSessionByFingerprintParams struct {
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) GetSessionByFingerprint(ctx context.Context, arg GetSessionByFingerprintParams) (VisitSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByFingerprint, arg.SiteID, arg.Fingerprint)
	var i VisitSession
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Fingerprint,
		&i.VisitorID,
		&i.Email,
		&i.ConsentMethod,
		&i.ConsentCategoriesJson,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.PageCount,
		&i.IdentifiedAt,
		&i.MetadataJson,
		&i.MetadataExpiresAt,
		&i.IdentityConfirmedAt,
	)
	return i, err
}

const getVisitorMetadataByFingerprint = `-- name: GetVisitorMetadataByFingerprint :one
SELECT id, site_id, fingerprint, visitor_id, email, consent_method,
       consent_categories_json, started_at, last_seen_at, page_count,
       identified_at, metadata_json, metadata_expires_at, identity_confirmed_at
FROM visit_sessions
WHERE site_id = ? AND fingerprint = ?
`

type GetVisitorMetadataByFingerprintParams struct {
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) GetVisitorMetadataByFingerprint(ctx context.Context, arg GetVisitorMetadataByFingerprintParams) (VisitSession, error) {
	row := q.db.QueryRowContext(ctx, getVisitorMetadataByFingerprint, arg.SiteID, arg.Fingerprint)
	var i VisitSession
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Fingerprint,
		&i.VisitorID,
		&i.Email,
		&i.ConsentMethod,
		&i.ConsentCategoriesJson,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.PageCount,
		&i.IdentifiedAt,
		&i.MetadataJson,
		&i.MetadataExpiresAt,
		&i.IdentityConfirmedAt,
	)
	return i, err
}

const identifyVisitSession = `-- name: IdentifyVisitSession :exec
UPDATE visit_sessions SET
    visitor_id = ?,
    email = ?,
    consent_method = ?,
    consent_categories_json = ?,
    identified_at = ?,
    last_seen_at = ?
WHERE site_id = ? AND fingerprint = ?
`

type IdentifyVisitSessionParams struct {
	VisitorID             string `json:"visitor_id"`
	Email                 string `json:"email"`
	ConsentMethod         string `json:"consent_method"`
	ConsentCategoriesJson string `json:"consent_categories_json"`
	IdentifiedAt          string `json:"identified_at"`
	LastSeenAt            string `json:"last_seen_at"`
	SiteID                string `json:"site_id"`
	Fingerprint           string `json:"fingerprint"`
}

func (q *Queries) IdentifyVisitSession(ctx context.Context, arg IdentifyVisitSessionParams) error {
	_, err := q.db.ExecContext(ctx, identifyVisitSession,
		arg.VisitorID,
		arg.Email,
		arg.ConsentMethod,
		arg.ConsentCategoriesJson,
		arg.IdentifiedAt,
		arg.LastSeenAt,
		arg.SiteID,
		arg.Fingerprint,
	)
	return err
}

const listIdentifiedSessions = `-- name: ListIdentifiedSessions :many
SELECT id, site_id, fingerprint, visitor_id, email, consent_method, consent_categories_json, started_at, last_seen_at, page_count, identified_at, metadata_json, metadata_expires_at, identity_confirmed_at FROM visit_sessions
WHERE site_id = ? AND identified_at != ''
ORDER BY identified_at DESC
LIMIT ? OFFSET ?
`

type ListIdentifiedSessionsParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListIdentifiedSessions(ctx context.Context, arg ListIdentifiedSessionsParams) ([]VisitSession, error) {
	rows, err := q.db.QueryContext(ctx, listIdentifiedSessions, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisitSession{}
	for rows.Next() {
		var i VisitSession
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Fingerprint,
			&i.VisitorID,
			&i.Email,
			&i.ConsentMethod,
			&i.ConsentCategoriesJson,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.PageCount,
			&i.IdentifiedAt,
			&i.MetadataJson,
			&i.MetadataExpiresAt,
			&i.IdentityConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVisitSession = `-- name: UpsertVisitSession :exec
INSERT INTO visit_sessions (id, site_id, fingerprint, started_at, last_seen_at, page_count)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT(site_id, fingerprint) DO UPDATE SET
    last_seen_at = excluded.last_seen_at,
    page_count = visit_sessions.page_count + 1
`

type UpsertVisitSessionParams struct {
	ID          string `json:"id"`
	SiteID      string `json:"site_id"`
	Fingerprint string `json:"fingerprint"`
	StartedAt   string `json:"started_at"`
	LastSeenAt  string `json:"last_seen_at"`
}

func (q *Queries) UpsertVisitSession(ctx context.Context, arg UpsertVisitSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertVisitSession,
		arg.ID,
		arg.SiteID,
		arg.Fingerprint,
		arg.StartedAt,
		arg.LastSeenAt,
	)
	return err
}

const upsertVisitorMetadataByFingerprint = `-- name: UpsertVisitorMetadataByFingerprint :execrows
UPDATE visit_sessions
SET metadata_json = ?,
    metadata_expires_at = ?,
    identity_confirmed_at = ?,
    last_seen_at = datetime('now')
WHERE site_id = ? AND fingerprint = ?
`

type UpsertVisitorMetadataByFingerprintParams struct {
	MetadataJson        string `json:"metadata_json"`
	MetadataExpiresAt   string `json:"metadata_expires_at"`
	IdentityConfirmedAt string `json:"identity_confirmed_at"`
	SiteID              string `json:"site_id"`
	Fingerprint         string `json:"fingerprint"`
}

func (q *Queries) UpsertVisitorMetadataByFingerprint(ctx context.Context, arg UpsertVisitorMetadataByFingerprintParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertVisitorMetadataByFingerprint,
		arg.MetadataJson,
		arg.MetadataExpiresAt,
		arg.IdentityConfirmedAt,
		arg.SiteID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertVisitorMetadataByVisitorID = `-- name: UpsertVisitorMetadataByVisitorID :execrows
UPDATE visit_sessions
SET metadata_json = ?,
    metadata_expires_at = ?,
    identity_confirmed_at = ?,
    last_seen_at = datetime('now')
WHERE site_id = ? AND visitor_id = ? AND visitor_id != ''
`

type UpsertVisitorMetadataByVisitorIDParams struct {
	MetadataJson        string `json:"metadata_json"`
	MetadataExpiresAt   string `json:"metadata_expires_at"`
	IdentityConfirmedAt string `json:"identity_confirmed_at"`
	SiteID              string `json:"site_id"`
	VisitorID           string `json:"visitor_id"`
}

func (q *Queries) UpsertVisitorMetadataByVisitorID(ctx context.Context, arg UpsertVisitorMetadataByVisitorIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertVisitorMetadataByVisitorID,
		arg.MetadataJson,
		arg.MetadataExpiresAt,
		arg.IdentityConfirmedAt,
		arg.SiteID,
		arg.VisitorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
