// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package store

import (
	"context"
)

const createWaitlistEntry = `-- name: CreateWaitlistEntry :exec
INSERT OR IGNORE INTO waitlist (id, email, name, use_case, region, source_ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWaitlistEntryParams struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	UseCase   string `json:"use_case"`
	Region    string `json:"region"`
	SourceIp  string `json:"source_ip"`
	UserAgent string `json:"user_agent"`
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, createWaitlistEntry,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.UseCase,
		arg.Region,
		arg.SourceIp,
		arg.UserAgent,
	)
	return err
}

const deleteWaitlistEntry = `-- name: DeleteWaitlistEntry :exec
DELETE FROM waitlist WHERE id = ?
`

func (q *Queries) DeleteWaitlistEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWaitlistEntry, id)
	return err
}

const getWaitlistByEmail = `-- name: GetWaitlistByEmail :one
SELECT id, email, name, use_case, region, source_ip, user_agent,
       invited_at, invite_token, notes, created_at
FROM waitlist WHERE email = ?
`

func (q *Queries) GetWaitlistByEmail(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, getWaitlistByEmail, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UseCase,
		&i.Region,
		&i.SourceIp,
		&i.UserAgent,
		&i.InvitedAt,
		&i.InviteToken,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlistByID = `-- name: GetWaitlistByID :one
SELECT id, email, name, use_case, region, source_ip, user_agent,
       invited_at, invite_token, notes, created_at
FROM waitlist WHERE id = ?
`

func (q *Queries) GetWaitlistByID(ctx context.Context, id string) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, getWaitlistByID, id)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UseCase,
		&i.Region,
		&i.SourceIp,
		&i.UserAgent,
		&i.InvitedAt,
		&i.InviteToken,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingWaitlist = `-- name: ListPendingWaitlist :many
SELECT id, email, name, use_case, region, source_ip, user_agent,
       invited_at, invite_token, notes, created_at
FROM waitlist
WHERE invited_at = ''
ORDER BY created_at ASC
LIMIT 1000
`

func (q *Queries) ListPendingWaitlist(ctx context.Context) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWaitlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Waitlist{}
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.UseCase,
			&i.Region,
			&i.SourceIp,
			&i.UserAgent,
			&i.InvitedAt,
			&i.InviteToken,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitlist = `-- name: ListWaitlist :many
SELECT id, email, name, use_case, region, source_ip, user_agent,
       invited_at, invite_token, notes, created_at
FROM waitlist
ORDER BY created_at DESC
LIMIT 1000
`

func (q *Queries) ListWaitlist(ctx context.Context) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, listWaitlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Waitlist{}
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.UseCase,
			&i.Region,
			&i.SourceIp,
			&i.UserAgent,
			&i.InvitedAt,
			&i.InviteToken,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWaitlistInvited = `-- name: MarkWaitlistInvited :exec
UPDATE waitlist
SET invited_at = datetime('now'), invite_token = ?, notes = ?
WHERE id = ?
`

type MarkWaitlistInvitedParams struct {
	InviteToken string `json:"invite_token"`
	Notes       string `json:"notes"`
	ID          string `json:"id"`
}

func (q *Queries) MarkWaitlistInvited(ctx context.Context, arg MarkWaitlistInvitedParams) error {
	_, err := q.db.ExecContext(ctx, markWaitlistInvited, arg.InviteToken, arg.Notes, arg.ID)
	return err
}
