// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package store

import (
	"context"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, subscription_id, site_id, event_type, payload_json)
VALUES (?, ?, ?, ?, ?)
`

type CreateWebhookDeliveryParams struct {
	ID             string `json:"id"`
	SubscriptionID string `json:"subscription_id"`
	SiteID         string `json:"site_id"`
	EventType      string `json:"event_type"`
	PayloadJson    string `json:"payload_json"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.SiteID,
		arg.EventType,
		arg.PayloadJson,
	)
	return err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :exec
INSERT INTO webhook_subscriptions (id, site_id, target_url, secret, event_types_json, active)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWebhookSubscriptionParams struct {
	ID             string `json:"id"`
	SiteID         string `json:"site_id"`
	TargetUrl      string `json:"target_url"`
	Secret         string `json:"secret"`
	EventTypesJson string `json:"event_types_json"`
	Active         int64  `json:"active"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookSubscription,
		arg.ID,
		arg.SiteID,
		arg.TargetUrl,
		arg.Secret,
		arg.EventTypesJson,
		arg.Active,
	)
	return err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions WHERE id = ?
`

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookSubscription, id)
	return err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, site_id, target_url, secret, event_types_json, active, last_delivered_at, last_error, created_at, updated_at
FROM webhook_subscriptions
WHERE id = ?
`

func (q *Queries) GetWebhookSubscription(ctx context.Context, id string) (WebhookSubscription, error) {
	row := q.db.QueryRowContext(ctx, getWebhookSubscription, id)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypesJson,
		&i.Active,
		&i.LastDeliveredAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhookSubscriptions = `-- name: ListActiveWebhookSubscriptions :many
SELECT id, site_id, target_url, secret, event_types_json, active, last_delivered_at, last_error, created_at, updated_at
FROM webhook_subscriptions
WHERE site_id = ? AND active = 1
`

// Used by the Emit hook to find every subscription on a site that
// should receive a given event. Filtering by event_types_json is
// done in Go because SQLite's JSON1 module isn't a hard dependency.
func (q *Queries) ListActiveWebhookSubscriptions(ctx context.Context, siteID string) ([]WebhookSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhookSubscriptions, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.TargetUrl,
			&i.Secret,
			&i.EventTypesJson,
			&i.Active,
			&i.LastDeliveredAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWebhookDeliveries = `-- name: ListPendingWebhookDeliveries :many
SELECT id, subscription_id, site_id, event_type, payload_json, status, attempts, next_attempt_at, last_response_status, last_error, created_at, completed_at
FROM webhook_deliveries
WHERE status IN ('pending', 'retrying') AND next_attempt_at <= ?
ORDER BY next_attempt_at ASC
LIMIT ?
`

type ListPendingWebhookDeliveriesParams struct {
	NextAttemptAt string `json:"next_attempt_at"`
	Limit         int64  `json:"limit"`
}

// Worker pull: picks up to N rows that are due for delivery (status
// pending or retrying AND next_attempt_at <= now). The status filter
// skips successful + dropped + in-flight rows.
func (q *Queries) ListPendingWebhookDeliveries(ctx context.Context, arg ListPendingWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWebhookDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.SiteID,
			&i.EventType,
			&i.PayloadJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastResponseStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesBySite = `-- name: ListWebhookDeliveriesBySite :many
SELECT id, subscription_id, site_id, event_type, payload_json, status, attempts, next_attempt_at, last_response_status, last_error, created_at, completed_at
FROM webhook_deliveries
WHERE site_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListWebhookDeliveriesBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListWebhookDeliveriesBySite(ctx context.Context, arg ListWebhookDeliveriesBySiteParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveriesBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.SiteID,
			&i.EventType,
			&i.PayloadJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastResponseStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsBySite = `-- name: ListWebhookSubscriptionsBySite :many
SELECT id, site_id, target_url, secret, event_types_json, active, last_delivered_at, last_error, created_at, updated_at
FROM webhook_subscriptions
WHERE site_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookSubscriptionsBySite(ctx context.Context, siteID string) ([]WebhookSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookSubscriptionsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.TargetUrl,
			&i.Secret,
			&i.EventTypesJson,
			&i.Active,
			&i.LastDeliveredAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryDropped = `-- name: MarkWebhookDeliveryDropped :exec
UPDATE webhook_deliveries
SET status = 'dropped', attempts = attempts + 1, last_response_status = ?, last_error = ?, completed_at = datetime('now')
WHERE id = ?
`

type MarkWebhookDeliveryDroppedParams struct {
	LastResponseStatus int64  `json:"last_response_status"`
	LastError          string `json:"last_error"`
	ID                 string `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryDropped(ctx context.Context, arg MarkWebhookDeliveryDroppedParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookDeliveryDropped, arg.LastResponseStatus, arg.LastError, arg.ID)
	return err
}

const markWebhookDeliveryRetrying = `-- name: MarkWebhookDeliveryRetrying :exec
UPDATE webhook_deliveries
SET status = 'retrying', attempts = attempts + 1, last_response_status = ?, last_error = ?, next_attempt_at = ?
WHERE id = ?
`

type MarkWebhookDeliveryRetryingParams struct {
	LastResponseStatus int64  `json:"last_response_status"`
	LastError          string `json:"last_error"`
	NextAttemptAt      string `json:"next_attempt_at"`
	ID                 string `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryRetrying(ctx context.Context, arg MarkWebhookDeliveryRetryingParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookDeliveryRetrying,
		arg.LastResponseStatus,
		arg.LastError,
		arg.NextAttemptAt,
		arg.ID,
	)
	return err
}

const markWebhookDeliverySucceeded = `-- name: MarkWebhookDeliverySucceeded :exec
UPDATE webhook_deliveries
SET status = 'success', attempts = attempts + 1, last_response_status = ?, last_error = '', completed_at = datetime('now')
WHERE id = ?
`

type MarkWebhookDeliverySucceededParams struct {
	LastResponseStatus int64  `json:"last_response_status"`
	ID                 string `json:"id"`
}

func (q *Queries) MarkWebhookDeliverySucceeded(ctx context.Context, arg MarkWebhookDeliverySucceededParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookDeliverySucceeded, arg.LastResponseStatus, arg.ID)
	return err
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :exec
UPDATE webhook_subscriptions
SET target_url = ?, event_types_json = ?, active = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWebhookSubscriptionParams struct {
	TargetUrl      string `json:"target_url"`
	EventTypesJson string `json:"event_types_json"`
	Active         int64  `json:"active"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookSubscription,
		arg.TargetUrl,
		arg.EventTypesJson,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateWebhookSubscriptionStatus = `-- name: UpdateWebhookSubscriptionStatus :exec
UPDATE webhook_subscriptions
SET last_delivered_at = ?, last_error = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWebhookSubscriptionStatusParams struct {
	LastDeliveredAt string `json:"last_delivered_at"`
	LastError       string `json:"last_error"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateWebhookSubscriptionStatus(ctx context.Context, arg UpdateWebhookSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookSubscriptionStatus, arg.LastDeliveredAt, arg.LastError, arg.ID)
	return err
}
