// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_invites.sql

package store

import (
	"context"
)

const backfillSitesWorkspace = `-- name: BackfillSitesWorkspace :exec
UPDATE sites SET workspace_id = ? WHERE workspace_id = ''
`

// Bootstrap helper: assign the given workspace_id to every site that
// currently has an empty workspace_id. Idempotent. Runs once at boot
// after ensureDefaultWorkspace creates the default workspace.
func (q *Queries) BackfillSitesWorkspace(ctx context.Context, workspaceID string) error {
	_, err := q.db.ExecContext(ctx, backfillSitesWorkspace, workspaceID)
	return err
}

const createWorkspaceInvite = `-- name: CreateWorkspaceInvite :exec
INSERT INTO workspace_invites (id, workspace_id, email, role, token, created_by, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceInviteParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Email       string `json:"email"`
	Role        string `json:"role"`
	Token       string `json:"token"`
	CreatedBy   string `json:"created_by"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const deleteWorkspaceInvite = `-- name: DeleteWorkspaceInvite :exec
DELETE FROM workspace_invites WHERE id = ?
`

func (q *Queries) DeleteWorkspaceInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceInvite, id)
	return err
}

const getWorkspaceInviteByToken = `-- name: GetWorkspaceInviteByToken :one
SELECT id, workspace_id, email, role, token, created_by, created_at, expires_at, used_at
FROM workspace_invites WHERE token = ?
`

func (q *Queries) GetWorkspaceInviteByToken(ctx context.Context, token string) (WorkspaceInvite, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceInviteByToken, token)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listPendingWorkspaceInvites = `-- name: ListPendingWorkspaceInvites :many
SELECT id, workspace_id, email, role, token, created_by, created_at, expires_at, used_at
FROM workspace_invites
WHERE workspace_id = ? AND used_at = '' AND expires_at > datetime('now')
ORDER BY created_at DESC
`

func (q *Queries) ListPendingWorkspaceInvites(ctx context.Context, workspaceID string) ([]WorkspaceInvite, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWorkspaceInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvite{}
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByWorkspace = `-- name: ListSitesByWorkspace :many
SELECT id, workspace_id, name, slug, status, created_at, updated_at
FROM sites WHERE workspace_id = ?
ORDER BY created_at ASC
`

type ListSitesByWorkspaceRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) ListSitesByWorkspace(ctx context.Context, workspaceID string) ([]ListSitesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSitesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesByWorkspaceRow{}
	for rows.Next() {
		var i ListSitesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceInviteUsed = `-- name: MarkWorkspaceInviteUsed :exec
UPDATE workspace_invites SET used_at = datetime('now') WHERE id = ?
`

func (q *Queries) MarkWorkspaceInviteUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markWorkspaceInviteUsed, id)
	return err
}
