// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"
)

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT COUNT(*) FROM workspaces
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, slug, plan, region, billing_email, status, trial_ends_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	Plan         string `json:"plan"`
	Region       string `json:"region"`
	BillingEmail string `json:"billing_email"`
	Status       string `json:"status"`
	TrialEndsAt  string `json:"trial_ends_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.Region,
		arg.BillingEmail,
		arg.Status,
		arg.TrialEndsAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, plan, region, billing_email,
       stripe_customer_id, stripe_subscription_id,
       status, trial_ends_at, created_at, updated_at
FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Region,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, plan, region, billing_email,
       stripe_customer_id, stripe_subscription_id,
       status, trial_ends_at, created_at, updated_at
FROM workspaces WHERE slug = ?
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Region,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWorkspaces = `-- name: ListAllWorkspaces :many
SELECT id, name, slug, plan, region, billing_email,
       stripe_customer_id, stripe_subscription_id,
       status, trial_ends_at, created_at, updated_at
FROM workspaces
ORDER BY created_at ASC
`

func (q *Queries) ListAllWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Region,
			&i.BillingEmail,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.Status,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.plan, w.region, w.billing_email,
       w.stripe_customer_id, w.stripe_subscription_id,
       w.status, w.trial_ends_at, w.created_at, w.updated_at,
       wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = ?
ORDER BY w.created_at ASC
`

type ListWorkspacesForUserRow struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	Slug                 string `json:"slug"`
	Plan                 string `json:"plan"`
	Region               string `json:"region"`
	BillingEmail         string `json:"billing_email"`
	StripeCustomerID     string `json:"stripe_customer_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	Status               string `json:"status"`
	TrialEndsAt          string `json:"trial_ends_at"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
	Role                 string `json:"role"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID string) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Region,
			&i.BillingEmail,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.Status,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces
SET name = ?, billing_email = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Name         string `json:"name"`
	BillingEmail string `json:"billing_email"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace, arg.Name, arg.BillingEmail, arg.ID)
	return err
}

const updateWorkspacePlan = `-- name: UpdateWorkspacePlan :exec
UPDATE workspaces
SET plan = ?, status = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkspacePlanParams struct {
	Plan   string `json:"plan"`
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateWorkspacePlan(ctx context.Context, arg UpdateWorkspacePlanParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspacePlan, arg.Plan, arg.Status, arg.ID)
	return err
}

const updateWorkspaceStripe = `-- name: UpdateWorkspaceStripe :exec
UPDATE workspaces
SET stripe_customer_id = ?, stripe_subscription_id = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkspaceStripeParams struct {
	StripeCustomerID     string `json:"stripe_customer_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	ID                   string `json:"id"`
}

func (q *Queries) UpdateWorkspaceStripe(ctx context.Context, arg UpdateWorkspaceStripeParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceStripe, arg.StripeCustomerID, arg.StripeSubscriptionID, arg.ID)
	return err
}
