// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_members.sql

package store

import (
	"context"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES (?, ?, ?)
ON CONFLICT(workspace_id, user_id) DO UPDATE SET role = excluded.role
`

type AddWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const backfillWorkspaceMembersForAdmin = `-- name: BackfillWorkspaceMembersForAdmin :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
SELECT w.id, ?, 'owner' FROM workspaces w
WHERE NOT EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = w.id)
`

// Bootstrap helper: grant the admin owner-role on every existing
// workspace that has zero member rows. Idempotent: once any member
// exists, the workspace is skipped. Used by ensureDefaultWorkspace
// on first boot of a Phase 30+ binary against an existing DB.
func (q *Queries) BackfillWorkspaceMembersForAdmin(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, backfillWorkspaceMembersForAdmin, userID)
	return err
}

const getWorkspaceMembership = `-- name: GetWorkspaceMembership :one
SELECT workspace_id, user_id, role, created_at
FROM workspace_members
WHERE workspace_id = ? AND user_id = ?
`

type GetWorkspaceMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) GetWorkspaceMembership(ctx context.Context, arg GetWorkspaceMembershipParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMembership, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceIDsForUser = `-- name: ListWorkspaceIDsForUser :many
SELECT workspace_id FROM workspace_members WHERE user_id = ?
`

func (q *Queries) ListWorkspaceIDsForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workspace_id string
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.workspace_id, wm.user_id, wm.role, wm.created_at,
       u.email, u.name
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = ?
ORDER BY wm.created_at ASC
`

type ListWorkspaceMembersRow struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
	CreatedAt   string `json:"created_at"`
	Email       string `json:"email"`
	Name        string `json:"name"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members WHERE workspace_id = ? AND user_id = ?
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}
