// This file is auto-generated by Atomicsite. Do not edit manually.
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import svelte from '@astrojs/svelte';

export default defineConfig({
  site: 'ATOMICSITE_SITE_URL',
  output: 'static',
  integrations: [sitemap(), svelte()],
  build: {
    assets: '_assets',
  },
});
